( defstruct ModelElement )
( defstruct Constraint )
( defstruct TaggedValue :dataValue :type )
( defstruct TagDefinition :tagType :multiplicity )
( defstruct Multiplicity :value )
( defstruct GeneralizableElement )
( defstruct Stereotype :icon )
( defstruct Geometry :value )
( defstruct Name :value )
