( defstruct ACMEFile )
( defstruct ACMEEntry )
( defstruct Element :name )
( defstruct Type :name )
( defstruct System :name )
( defstruct Representation )
( defstruct Component :name )
( defstruct ComponentInstance :instanceOf :name )
( defstruct ComponentType :extend :name )
( defstruct Port :name )
( defstruct Connector :system :name )
( defstruct Role :name )
( defstruct Property :name :val )
( defstruct Link :systemBinding :systemAttachment )
( defstruct Attachment :comp :port :con :role :systemBinding :systemAttachment )
( defstruct Binding :compSrc :portSrc :compDest :portDest :systemBinding :systemAttachment )
