( defstruct Classifier )
( defstruct Environnement :element )
( defstruct Element :environnement :action :perception )
( defstruct CooperativeAgent :elementA :elementP :representation :skill :observes )
( defstruct Representation :cooperativeAgentR :element )
( defstruct Skill :cooperativeAgentS )
( defstruct Aptitude :cooperativeAgentA )
( defstruct Characteristic :cooperativeAgentCha )
( defstruct Communication :cooperativeAgentCom )
( defstruct AIP )
( defstruct CooperationRules :detects )
( defstruct NCS :cooperationRules )
( defstruct Incomprehension :cooperationRules )
( defstruct Ambiguity :cooperationRules )
( defstruct Incompetence :cooperationRules )
( defstruct Unproductiveness :cooperationRules )
( defstruct Concurrency :cooperationRules )
( defstruct Conflict :cooperationRules )
( defstruct Uselessness :cooperationRules )
