( defstruct Entity )
( defstruct Object :id )
( defstruct AGATEObject :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Objective :type :priority :indicator :traceability :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct OperationalContext :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Project :moi :moa :director :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Standard :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct GenericStandard :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Threat :nature :DCSSI :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct GenericThreat :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Vulnerability :level :relatesTo )
( defstruct TrafficClass :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct InterfaceCharacteristic :type :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct ConfidentialityLevel :type :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Protocol :isoLevel :type :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Flow :unit :type :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Other :type :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct ProjectContextElement :type :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct DataClass :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Event :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Risk :disponibilityLevel :integrityLevel :confidencialityLevel :isCoveredByCR :isCoveredByAO :isCoveredByMO :isCoveredByDR :relatesToRO :relatesToCO :isGeneratedBy :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Stake :type :relativeDate :unit :date :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Requirement :criticality :priority :state :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct CountermeasureRequirement :type :residualVulnerability :criticality :priority :state :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct TechnicalRequirement :criticality :priority :state :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct PerformanceRequirement :criticality :priority :state :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct InteroperabilityRequirement :criticality :priority :state :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct OperationalRequirement :criticality :priority :state :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct SecurityRequirement :criticality :priority :state :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Means :isProvidedBy :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct DomainRelation :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct HierarchicalRelation :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct FunctionalRelation :necessaryObjectP :dependentObjectP :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Dependence :type :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct ArchitectureObject :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct ReusableObject :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Site :type :localization :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct GenericSite :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Package :isCoveredByLC :isCoveredByTC :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Service :Statut :isASpecializationOf :isCoveredBy :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct TechnicalComponent :type :cots :editor :constructor :version :technology :definedExtension :statut :isASpecializationOf :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct LogicalComponent :type :statut :isASpecializationOf :isCoveredBy :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct OperationalFunction :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct OrganizationObject :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Center :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct GenericCenter :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct InformationSystem :nature :version :membershipCountry :currentLocation :startServiceDate :stopServiceDate :isGeneric :functionalDomain :type :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Role :type :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct GenericRole :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Actor :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct GenericActor :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct TelecomOperator :contractType :subordinate :superior :membership :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct CommunicationObject :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Interface :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Interconnection :linkType :between :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct InformationFlow :priority :frequency :media :continuity :myContainer :time :availabilityRatio :integrity :interoperabilityLevel :mediumFlow :maximumFlow :duration :unitMediumFlow :averageEvent :maximumFlowOverOneDuration :transports :receiverP :transmitterP :receiverOO :transmitterOO :receiverOF :transmitterOF :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Traffic :sequence :type :interoperabilityLevel :trafficClass :dataClass :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct Information :format :storageSupport :persistence :confidentialityLevel :notice :description :sensitivity :name :comment :isValidIn :isAssociatedWith :id )
( defstruct ReferenceObject :name :description :id )
( defstruct ReferenceTechnicalComponent :name :description :id )
( defstruct TechnicalComponentReferenceFrame :name :description :id )
( defstruct ReferenceLogicalComponent :name :description :id )
( defstruct ReferenceService :name :description :id )
( defstruct ServiceReferenceFrame )
( defstruct MADIOSObject :id )
( defstruct Process :id )
( defstruct Procedure :id )
( defstruct Operation :id )
( defstruct Activity :id )
