( defstruct Element :name )
( defstruct Program :name )
( defstruct Process :minId :maxId :instancesNb :name )
( defstruct State :isInitial :name )
( defstruct Transition :source :target )
( defstruct Trans :waitFor :source :target )
( defstruct Strans :source :target )
( defstruct Transall :waitFor :source :target )
( defstruct Guard :name )
( defstruct Action :name )
( defstruct Network :name )
( defstruct Channel :source :target :name )
( defstruct Message :name )
( defstruct Variable :type :initValue :name )
