( defstruct Project :default :targets )
( defstruct Property )
( defstruct PropertyName :name )
( defstruct PropertyValue :value :name )
( defstruct PropertyLocation :location :name )
( defstruct PropertyFile :file )
( defstruct PropertyEnv :environment )
( defstruct Target :name )
( defstruct Pattern )
( defstruct Basic )
( defstruct Mapper )
( defstruct InExcludes :name )
( defstruct Includes :name )
( defstruct Excludes :name )
( defstruct IncludesFile :name )
( defstruct ExcludesFile :name )
( defstruct FileList :dir :files )
( defstruct Filter :token :value )
( defstruct FiltersFile :file )
( defstruct PathElement :path :location )
( defstruct Set )
( defstruct PatternSet :inexcludes )
( defstruct FileSet :dir )
( defstruct FilterSet )
( defstruct Path :id )
( defstruct ClassPath :refid )
( defstruct Task :target )
( defstruct TaskDef :name :classname )
( defstruct NewTask :taskName :target )
( defstruct Attribut :name :value )
( defstruct PreDefinedTask :target )
( defstruct ExecutionTask :target )
( defstruct Exec :executable :dir :target )
( defstruct Java :classname :target )
( defstruct MiscellaneousTask :target )
( defstruct Echo :message :target )
( defstruct Tstamp :target )
( defstruct FormatTstamp :property :pattern )
( defstruct CompileTask :target )
( defstruct Javac :srcdir :target )
( defstruct DocumentationTask :target )
( defstruct Javadoc :sourcepath :destdir :packagenames :defaultexcludes :author :version :use :windowtitle :target )
( defstruct ArchiveTask :target )
( defstruct Jar :jarfile :target )
( defstruct FileTask :target )
( defstruct Mkdir :dir :target )
( defstruct Copy :target )
( defstruct Delete :target )
