( defstruct NamedElement :name )
( defstruct DescribableElement )
( defstruct CommentableElement )
( defstruct Project :name )
( defstruct Property )
( defstruct Target :name )
( defstruct TaskElement :name )
( defstruct Attribute :value :name )
( defstruct Task :name )
( defstruct TaskParameter :name )
