( defstruct ModelElement :id :name :excludeFromBuild )
( defstruct VisualModelElement :position :label :publicFlag :presentationFlag :showLabel :id :name :excludeFromBuild )
( defstruct Point :x :y )
( defstruct Model :engineVersion :javaPackageName :id :name :excludeFromBuild )
( defstruct ActiveObjectClass :clientAreaTopLeft :presentationTopGroupPersistent :iconTopGroupPersistent :generic :genericParameters :agent :environmentDefinesInitialLocation :id :name :excludeFromBuild )
( defstruct Connector :sourceEmbeddedObject :sourceConnectableName :targetEmbeddedObject :targetConnectableName :position :label :publicFlag :presentationFlag :showLabel :id :name :excludeFromBuild )
( defstruct EmbeddedObject :presentation :activeObjectClass :genericParametersSubstitute :position :label :publicFlag :presentationFlag :showLabel :id :name :excludeFromBuild )
( defstruct ActiveObjectClassRef :packageName :className )
( defstruct Parameter :name :value )
( defstruct Shape :asObject :embeddedIcon :rotation :position :label :publicFlag :presentationFlag :showLabel :id :name :excludeFromBuild )
( defstruct EmbeddedObjectPresentation :asObject :embeddedIcon :rotation :position :label :publicFlag :presentationFlag :showLabel :id :name :excludeFromBuild )
( defstruct Experiment :id :name :excludeFromBuild )
( defstruct SimulationExperiment :activeObjectClass :clientAreaTopLeft :presentationTopGroupPersistent :iconTopGroupPersistent :frame :commandLineArguments :maximumMemory :randomSeed :seedValue :vmArgs :absoluteAccuracy :relativeAccuracy :timeAccuracy :fixedTimeStep :enableAdaptiveFrameManagement :enableAntiAliasing :enablePanning :enableZoom :executionMode :cpuRatio :title :framesPerSecond :realTimeScale :useCalendar :stopOption :initialDate :initialTime :finalDate :finalTime :modelTimeUnit :id :name :excludeFromBuild )
( defstruct Control :width :height :asObject :embeddedIcon :fillColor :textColor :enableExpression :actionCode :labelText :font :position :label :publicFlag :presentationFlag :showLabel :id :name :excludeFromBuild )
( defstruct Button :width :height :asObject :embeddedIcon :fillColor :textColor :enableExpression :actionCode :labelText :font :position :label :publicFlag :presentationFlag :showLabel :id :name :excludeFromBuild )
( defstruct Frame :x :y :width :height )
( defstruct Text :color :text :font :alignment :asObject :embeddedIcon :rotation :position :label :publicFlag :presentationFlag :showLabel :id :name :excludeFromBuild )
( defstruct Font :name :size :style )
