( defstruct LocatedElement :location )
( defstruct XAsmFile :location )
( defstruct XAsmSpec :Asm :location )
( defstruct Asm :signature :metaInformation :body :location )
( defstruct Signature :isMain :name :location )
( defstruct Argument :type :name :location )
( defstruct Body :location )
( defstruct MetaInformation :usedAs :location )
( defstruct AccessUpdateFunction :type :functions :location )
( defstruct Declaration :location )
( defstruct Function :returnType :isExternal :location :name :location )
( defstruct Parameter :name :type :location )
( defstruct Universe :name :location )
( defstruct Initialization :rules :location )
( defstruct Term :location )
( defstruct Constant :location )
( defstruct FunctionOrVariableTerm :declaration :location )
( defstruct OperatorTerm :opName :leftExp :location )
( defstruct BooleanConstant :value :location )
( defstruct IntegerConstant :value :location )
( defstruct StringConstant :value :location )
( defstruct UndefConstant :location )
( defstruct Rule :inSequence :location )
( defstruct SkipRule :inSequence :location )
( defstruct AsmInvocation :asmName :inSequence :location )
( defstruct UpdateRule :function :updateTerm :inSequence :location )
( defstruct ChooseRule :chooseId :ifChoosenRules :inSequence :location )
( defstruct DoForallRule :id :doRule :inSequence :location )
( defstruct ConditionalRule :condition :thenRule :inSequence :location )
( defstruct ElseIf :condition :thenRule :location )
( defstruct ExtendRule :extensions :rules :inSequence :location )
( defstruct ElementDecl :name :location )
( defstruct VariableDecl :name :location )
( defstruct Extension :elements :universe :location )
( defstruct ReturnRule :term :inSequence :location )
