( defstruct ATOM :title :id :links :lastUpdate :authors )
( defstruct Entry :title :id :links :lastUpdate :authors :atom )
( defstruct Source )
( defstruct Content )
( defstruct InLineXHTMLContent )
( defstruct InLineOtherContent )
( defstruct OutOfLineContent :src )
( defstruct Generator )
( defstruct Category :term )
( defstruct Link :href )
( defstruct Person :name )
( defstruct Author :name )
( defstruct Contributor :name )
( defstruct Date :day :month :year :hours :minutes :seconds )
