( defstruct BibTeXFile )
( defstruct Author :author )
( defstruct BibTeXEntry :id )
( defstruct AuthoredEntry :authors :id )
( defstruct DatedEntry :year :id )
( defstruct TitledEntry :title :id )
( defstruct BookTitledEntry :booktitle :id )
( defstruct Article :journal :authors :id :year :id :title :id )
( defstruct TechReport :authors :id :year :id :title :id )
( defstruct Unpublished :note :authors :id :title :id )
( defstruct Manual :title :id )
( defstruct Proceedings :year :id :title :id )
( defstruct InProceedings :year :id :title :id :authors :id :booktitle :id )
( defstruct Booklet :year :id )
( defstruct Book :publisher :authors :id :year :id :title :id )
( defstruct InCollection :publisher :authors :id :year :id :title :id :booktitle :id )
( defstruct InBook :chapter :publisher :authors :id :year :id :title :id )
( defstruct Misc :id )
( defstruct ThesisEntry :school :authors :id :year :id :title :id )
( defstruct PhDThesis :school :authors :id :year :id :title :id )
( defstruct MasterThesis :school :authors :id :year :id :title :id )
