( defstruct LocatedElement :location )
( defstruct Bibtex )
( defstruct Entry :key :location )
( defstruct Article :key :location )
( defstruct Book :key :location )
( defstruct Inbook :key :location )
( defstruct Booklet :key :location )
( defstruct Inproceedings :key :location )
( defstruct Proceedings :key :location )
( defstruct Incollection :key :location )
( defstruct Techreport :key :location )
( defstruct PhdThesis :key :location )
( defstruct MastersThesis :key :location )
( defstruct Manual :key :location )
( defstruct Misc :key :location )
( defstruct Field :value )
( defstruct Authors :value )
( defstruct AuthorUrls :value )
( defstruct Title :value )
( defstruct Journal :value )
( defstruct BookTitle :value )
( defstruct Institution :value )
( defstruct Organization :value )
( defstruct Type :value )
( defstruct Day :value )
( defstruct Number :value )
( defstruct Chapter :value )
( defstruct Volume :value )
( defstruct Series :value )
( defstruct Pages :value )
( defstruct Publisher :value )
( defstruct Howpublished :value )
( defstruct School :value )
( defstruct Editor :value )
( defstruct Edition :value )
( defstruct Address :value )
( defstruct Year :value )
( defstruct Month :value )
( defstruct Note :value )
( defstruct Text :value )
( defstruct AbstractField :value )
( defstruct Isbn :value )
( defstruct Issn :value )
( defstruct Url :value )
( defstruct Doi :value )
