( defstruct Assessment :judgedInfluencer :assessingOrganizationUnit :name :description )
( defstruct MotivationElement :name :description )
( defstruct Directive :name :description )
( defstruct Means :name :description )
( defstruct OrganizationUnit :name :description )
( defstruct End :name :description )
( defstruct BusinessProcess :guidingBusinessRule :name :description )
( defstruct Offering :name :description :name :description )
( defstruct Asset :name :description )
( defstruct CourseOfAction :realizingBusinessProcess :name :description )
( defstruct DesiredResult :name :description )
( defstruct Liability :name :description )
( defstruct Resource :name :description )
( defstruct FixedAsset :name :description )
( defstruct BusinessPolicy :name :description )
( defstruct BusinessRule :name :description )
( defstruct Tactic :realizingBusinessProcess :name :description )
( defstruct Strategy :realizingBusinessProcess :name :description )
( defstruct Mission :name :description )
( defstruct Vision :name :description )
( defstruct Goal :name :description )
( defstruct Objective :name :description )
( defstruct Influencer :recognizingOrganizationUnit :name :description )
( defstruct InfluencerCategory :name :description )
( defstruct InfluencingOrganization :name :description )
( defstruct OrganizationCategory :name :description )
( defstruct PotentialImpact :name :description )
( defstruct Regulation :recognizingOrganizationUnit :name :description )
( defstruct AssessmentCategory :name :description )
( defstruct PotentialReward :name :description )
( defstruct Risk :name :description )
