( defstruct BossaProgramm :scheduler )
( defstruct Scheduler :defaultAtt :high_Res :low_Res :id :handlerDef :interfaceDef :functionDef )
( defstruct NormalScheduler :schedulerDecl :defaultAtt :high_Res :low_Res :id :handlerDef :interfaceDef :functionDef )
( defstruct VirtualScheduler :vschedulerDecl :defaultAtt :high_Res :low_Res :id :handlerDef :interfaceDef :functionDef )
( defstruct AbstractSchedulerDecl :stateDef )
( defstruct SchedulerDecl :processDef :stateDef )
( defstruct VSchdulerDecl :schedulerDef :stateDef )
( defstruct ConstDef :id :expr :bossaTypeExpr )
( defstruct TypeDef :enumRang )
( defstruct EnumRange )
( defstruct EnumDef :theIds )
( defstruct BagId :theValue )
( defstruct RangeDef :expr )
( defstruct ProcessDef :processVarDecl )
( defstruct SchedulerDef :processVarDecl )
( defstruct ProcessVarDecl :id :processDef :schedulerDef )
( defstruct Timer_ProcessVarDecl :id :processDef :schedulerDef )
( defstruct System_ProcessVarDecl :system :typeExpr :id :processDef :schedulerDef )
( defstruct Normal_ProcessVarDecl :typeExpr :id :processDef :schedulerDef )
( defstruct HandlerDef :id :scheduler :onHandlerDef )
( defstruct InterfaceDef :composantOfInterFunc :scheduler )
( defstruct FunctionDef :composantOfInterFunc :scheduler )
( defstruct Expression )
( defstruct Integer_Expression :theValue )
( defstruct Id_Expression :id )
( defstruct State_Expression :theValue )
( defstruct True_Expression )
( defstruct False_Expression )
( defstruct Unop_Expression :unop :expr )
( defstruct Etoile_Expression :expr )
( defstruct ExpId_Expression :id :expr )
( defstruct Select_Expression )
( defstruct FnName_Expression )
( defstruct Empty_Expression :classState )
( defstruct SRCOnSched_Expression )
( defstruct SchedulerOf_Expression :expr )
( defstruct In_Expression :in :expr :classState )
( defstruct Parenthese_Expression :expr )
( defstruct Binop_Expression :id_Expression :compo_Binop_Expression )
( defstruct Compo_Binop_Expression :binop :id_Expression )
( defstruct ValDecl :id :abstractSchedulerDecl )
( defstruct Normal_ValDecl :id :abstractSchedulerDecl )
( defstruct System_ValDecl :id :abstractSchedulerDecl )
( defstruct Timer_ValDecl :id :abstractSchedulerDecl )
( defstruct FunDecl :abstractSchedulerDecl )
( defstruct StateDef :classNameStorage :abstractSchedulerDecl )
( defstruct ClassNameStorage :id :className )
( defstruct OrderDef :keyCritDecl :critDecls :abstractSchedulerDecl )
( defstruct AdmissionDef :admCrit :abstractSchedulerDecl )
( defstruct TraceDef :abstractSchedulerDecl )
( defstruct TypeExpr )
( defstruct TypeOrVoid :isVoid )
( defstruct ParameterType :typeExpr )
( defstruct Storage )
( defstruct Process_Storage )
( defstruct Scheduler_Storage )
( defstruct Queue_Storage )
( defstruct KeyCritDecls :compoKeyCritDecls )
( defstruct CompoKeyCritDecls :critDecl )
( defstruct CritDecls :critDecl )
( defstruct CritDecl :critop )
( defstruct CritDeclWhithId :id :critop )
( defstruct CritDeclWhithoutId :expr :critop )
( defstruct ValDef :id :typeExpr :expr )
( defstruct AdmCrit :expr )
( defstruct AttachDetach :procParam1 :procParam2 :seqStmt1 :seqStmt2 )
( defstruct ParamVarDecl :id :typeExpr )
( defstruct SeqStmt )
( defstruct TraceEvent :eventName )
( defstruct TraceExpr :id )
( defstruct TraceTest :expr )
( defstruct ProcParam :id :process :scheduler )
( defstruct Statment )
( defstruct IfStmt :expr :seqStmt )
( defstruct ForStmt )
( defstruct ForeachForStmt :id :isIn :seqStmt )
( defstruct ForEachIncreasingForStmt :id :seqStmt )
( defstruct ForEachDecreasingForStmt :id :seqStmt )
( defstruct ReturnStmt )
( defstruct SwitchStmt :locExpr )
( defstruct AssignStmt :locExpr )
( defstruct MoveStmt :isHead :isTail :moveExpr )
( defstruct NormalMoveStmt :stateRef :isHead :isTail :moveExpr )
( defstruct ForwardMoveStmt :isHead :isTail :moveExpr )
( defstruct StateRef :stateRef )
( defstruct DeferStmt :deferStmt )
( defstruct PrimStmt )
( defstruct ErrorStmt :errorType )
( defstruct BreakStmt )
( defstruct LocExpr :stateName )
( defstruct MoveExpr )
( defstruct Select_MoveExpr )
( defstruct SatateName_MoveExpr )
( defstruct ID_MoveExpr :id )
( defstruct IDSource_MoveExpr :id )
( defstruct IDTarget_MoveExpr :id )
( defstruct ClassState :state )
( defstruct OnHandlerDef :seqStmt )
( defstruct EventName :eventNameLeft :eventNameRight )
( defstruct ComposantOfSwitchStmt :classState :seqStmt )
( defstruct ComposantOfInterFunc :id :typeOrVoid :seqStmt )
( defstruct BossaTypeExpr :bossaTypeExpr )
( defstruct QueueType )
( defstruct Normal_QueueType )
( defstruct Fifo_QueueType )
( defstruct Lifo_QueueType )
( defstruct Critop :lowest :highest )
( defstruct StateVisibility )
( defstruct ClassName :className )
( defstruct NonProcType :system :struct :id :nonProcType )
( defstruct Unop :plus :minus :excl :tild )
( defstruct Binop :plus :minus :star :slash :percentage :doubleAnd :doubleVerticalBar :and :eq :ne :lt :gt :le :ge :doubleLt :doubleGt )
( defstruct AssignUnop :doublePlus :doubleMoins )
( defstruct AssignBinop :affect :plusEqual :moinsEqual :starEqual :slashEqual :percentageEqual :andEqual :orEqual :doubleLtEqual :doubleGtEqual )
