( defstruct Process :activity )
( defstruct PartnerLink )
( defstruct FaultHandler )
( defstruct Activity )
( defstruct CorrelationSet )
( defstruct Invoke :partnerLink :portType :operation )
( defstruct Link )
( defstruct Catch :activity )
( defstruct Reply :partnerLink :portType :operation )
( defstruct PartnerActivity :partnerLink :portType :operation )
( defstruct Receive :variable :partnerLink :portType :operation )
( defstruct Exit )
( defstruct Throw )
( defstruct Wait )
( defstruct Empty )
( defstruct Sequence :activities )
( defstruct Switch :cases )
( defstruct Case :activity :condition )
( defstruct While :activity :condition )
( defstruct Pick :messages )
( defstruct Flow :activities )
( defstruct OnAlarm :activity )
( defstruct Assign :copy )
( defstruct Copy :to :from )
( defstruct Extension )
( defstruct Scope :activity )
( defstruct Compensate )
( defstruct CompensationHandler :activity )
( defstruct To )
( defstruct From )
( defstruct OnMessage :portType :partnerLink :operation )
( defstruct Expression )
( defstruct BooleanExpression )
( defstruct Correlation :set )
( defstruct EventHandler )
( defstruct Source :Link :activity )
( defstruct Target :Link :activity )
( defstruct PartnerLinks )
( defstruct Variables )
( defstruct CorrelationSets )
( defstruct Links )
( defstruct CatchAll :activity )
( defstruct Correlations )
( defstruct Variable )
( defstruct Otherwise :activity )
( defstruct UnknownExtensibilityAttribute )
( defstruct OnEvent :partnerLink :operation :portType :messageType )
( defstruct BPELImport )
( defstruct Rethrow )
( defstruct Condition )
( defstruct Targets )
( defstruct Sources )
( defstruct BPELQuery )
( defstruct ServiceRef )
( defstruct Extensions )
( defstruct ExtensionActivity )
( defstruct FromPart )
( defstruct ToPart )
( defstruct OpaqueActivity )
( defstruct ForEach :counterName :iterator :activity )
( defstruct RepeatUntil :activity :condition )
( defstruct TerminationHandler )
( defstruct Validate )
( defstruct If )
( defstruct Then :activity )
( defstruct ElseIf :activity )
( defstruct Else :activity )
( defstruct CompletionCondition )
( defstruct Branches )
( defstruct BPELExtensibleElement )
( defstruct Documentation )
( defstruct Iterator )
( defstruct Property )
( defstruct PropertyAlias :wsdlPart )
( defstruct messagepropertiesQuery )
( defstruct WSDLElement )
( defstruct PortType )
( defstruct Operation )
( defstruct Message )
( defstruct Part )
( defstruct Binding :ePortType )
( defstruct BindingOperation :eOperation )
( defstruct Service )
( defstruct Port :eBinding )
( defstruct ExtensibilityElement )
( defstruct Definition )
( defstruct WSDLImport )
( defstruct WSDLExtensibleElement )
( defstruct Input :eMessage )
( defstruct Output :eMessage )
( defstruct Fault :eMessage )
( defstruct BindingInput :eInput )
( defstruct BindingOutput :eOutput )
( defstruct BindingFault :eFault )
( defstruct Namespace )
( defstruct IPortType )
( defstruct IOperation )
( defstruct IInput )
( defstruct IOutput )
( defstruct IFault )
( defstruct IMessage )
( defstruct IPart )
( defstruct IService )
( defstruct IPort )
( defstruct IBinding )
( defstruct IBindingOperation )
( defstruct IBindingInput )
( defstruct IBindingOutput )
( defstruct IBindingFault )
( defstruct IExtensibilityElement )
( defstruct IDefinition )
( defstruct IImport )
( defstruct IList )
( defstruct IMap )
( defstruct IURL )
( defstruct IExtensionRegistry )
( defstruct Types )
( defstruct IIterator )
( defstruct ITypes )
( defstruct UnknownExtensibilityElement )
( defstruct XSDSchemaExtensibilityElement )
( defstruct MessageReference :eMessage )
( defstruct PartnerLinkType )
( defstruct Role )
( defstruct EObject )
( defstruct XSDAnnotation :rootContainer :rootContainer )
( defstruct XSDAttributeDeclaration :typeDefinition :resolvedAttributeDeclaration :resolvedFeature :type :rootContainer :rootContainer )
( defstruct XSDAttributeGroupContent :rootContainer )
( defstruct XSDAttributeGroupDefinition :resolvedAttributeGroupDefinition :rootContainer :rootContainer :rootContainer :rootContainer )
( defstruct XSDAttributeUse :attributeDeclaration :content :rootContainer :rootContainer )
( defstruct XSDBoundedFacet :rootContainer )
( defstruct XSDCardinalityFacet :rootContainer )
( defstruct XSDComplexTypeContent :rootContainer )
( defstruct XSDComplexTypeDefinition :baseTypeDefinition :rootTypeDefinition :rootType :baseType :rootContainer :rootContainer :rootContainer :rootContainer )
( defstruct XSDComponent :rootContainer )
( defstruct XSDConcreteComponent :rootContainer )
( defstruct XSDConstrainingFacet :rootContainer )
( defstruct XSDDiagnostic :components :primaryComponent :rootContainer )
( defstruct XSDElementDeclaration :typeDefinition :resolvedElementDeclaration :resolvedFeature :type :rootContainer :rootContainer :rootContainer :rootContainer )
( defstruct XSDEnumerationFacet :rootContainer )
( defstruct XSDFacet :rootContainer )
( defstruct XSDFeature :resolvedFeature :type :rootContainer )
( defstruct XSDFixedFacet :rootContainer )
( defstruct XSDFractionDigitsFacet :rootContainer )
( defstruct XSDFundamentalFacet :rootContainer )
( defstruct XSDIdentityConstraintDefinition :selector :fields :rootContainer )
( defstruct XSDImport :rootContainer )
( defstruct XSDInclude :rootContainer )
( defstruct XSDLengthFacet :rootContainer )
( defstruct XSDMaxExclusiveFacet :rootContainer )
( defstruct XSDMaxFacet :rootContainer )
( defstruct XSDMaxInclusiveFacet :rootContainer )
( defstruct XSDMaxLengthFacet :rootContainer )
( defstruct XSDMinExclusiveFacet :rootContainer )
( defstruct XSDMinFacet :rootContainer )
( defstruct XSDMinInclusiveFacet :rootContainer )
( defstruct XSDMinLengthFacet :rootContainer )
( defstruct XSDModelGroup :particles :rootContainer :rootContainer )
( defstruct XSDModelGroupDefinition :modelGroup :resolvedModelGroupDefinition :rootContainer :rootContainer :rootContainer :rootContainer )
( defstruct XSDNamedComponent :rootContainer )
( defstruct XSDNotationDeclaration :rootContainer :rootContainer )
( defstruct XSDNumericFacet :rootContainer )
( defstruct XSDOrderedFacet :rootContainer )
( defstruct XSDParticle :content :term :rootContainer )
( defstruct XSDParticleContent :rootContainer )
( defstruct XSDPatternFacet :rootContainer )
( defstruct XSDRedefinableComponent :rootContainer :rootContainer )
( defstruct XSDRedefineContent :rootContainer )
( defstruct XSDRedefine :rootContainer )
( defstruct XSDRepeatableFacet :rootContainer )
( defstruct XSDSchema :rootVersion :schemaForSchema :rootContainer )
( defstruct XSDSchemaCompositor :rootContainer )
( defstruct XSDSchemaContent :rootContainer )
( defstruct XSDSchemaDirective :rootContainer )
( defstruct XSDScope :rootContainer )
( defstruct XSDSimpleTypeDefinition :fundamentalFacets :baseTypeDefinition :rootTypeDefinition :cardinalityFacet :numericFacet :orderedFacet :boundedFacet :rootType :baseType :rootContainer :rootContainer :rootContainer :rootContainer )
( defstruct XSDTerm :rootContainer :rootContainer )
( defstruct XSDTotalDigitsFacet :rootContainer )
( defstruct XSDTypeDefinition :rootType :baseType :rootContainer :rootContainer :rootContainer )
( defstruct XSDWhiteSpaceFacet :rootContainer )
( defstruct XSDWildcard :rootContainer :rootContainer )
( defstruct XSDXPathDefinition :rootContainer )
