( defstruct BugzillaRoot :version :urlbase :maintainer :bugs )
( defstruct Bug :bug_bugzillaRoot :bug_id :exporter :urlbase :bug_status :product :priority :version :rep_platform :assigned_to :delta_ts :component :reporter :bug_severity :creation_ts :op_sys )
( defstruct StringElt :value )
( defstruct Keywords :value )
( defstruct Dependson :value )
( defstruct Blocks :value )
( defstruct Cc :value )
( defstruct LongDesc :isPrivate :who :bug_when :thetext )
( defstruct Attachment :isObsolete :isPatch :isPrivate :id :date :desc :type :data )
