( defstruct Namespace )
( defstruct Task :containsDataSet )
( defstruct DataSet )
( defstruct Parameter )
( defstruct DataElement :sink :source )
( defstruct ModelElement )
( defstruct Flow )
( defstruct DataFlow )
( defstruct ControlFlow )
( defstruct ControlPoint )
( defstruct Input :sink :source )
( defstruct Output :sink :source )
( defstruct OutputSet )
( defstruct InputSet )
( defstruct Exception :sink :source )
( defstruct SimpleTask :containsDataSet )
( defstruct CoumpoundTask :realizes :containsDataSet )
( defstruct MutliTask :realizes :containsDataSet )
( defstruct InvokerTask :containsDataSet )
( defstruct TerminatorTask :containsDataSet )
( defstruct ApplicationTask :containsDataSet )
( defstruct Decision :containsDataSet )
( defstruct Clock :containsDataSet )
( defstruct SendCommunication :containsDataSet )
( defstruct ReceiveCommunication :containsDataSet )
( defstruct BusinessProcess :containsDataSet )
