( defstruct DataType )
( defstruct Action )
( defstruct Class )
( defstruct BusinessEntityPropertySet )
( defstruct BusinessRole :characterisedby :typ :fille )
( defstruct Task :associatedWith )
( defstruct ArtifactRole :characterisedby :typ :fille )
( defstruct PerformerRole :perform :characterisedby :typ :fille )
( defstruct OrganisationalUnit :characterisedby :typ :fille )
( defstruct BusinessEntity :placehold )
