( defstruct CDataType )
( defstruct CIntegral )
( defstruct CFloating )
( defstruct CBitField )
( defstruct CVoid )
( defstruct CEnumeration )
( defstruct CInt )
( defstruct CChar )
( defstruct CDouble )
( defstruct CFloat )
( defstruct CLongDouble )
( defstruct CUnsignedInt )
( defstruct CLong )
( defstruct CLongLong )
( defstruct CShort )
( defstruct CSignedChar )
( defstruct CUnsignedChar )
( defstruct CWChar )
( defstruct UnsignedLong )
( defstruct UnsignedLongLong )
( defstruct UnsignedShort )
( defstruct CClassifier )
( defstruct Derived )
( defstruct CStructureContents )
( defstruct CStructured )
( defstruct CStruct )
( defstruct CUnion )
( defstruct CSourceText :source :fileName )
( defstruct CTypedElement :type :source )
( defstruct CStructuralFeature :type :source )
( defstruct CField :type :source )
( defstruct CParameter :type :source )
( defstruct BehavioralFeature )
( defstruct CFunction :isVarArg )
