( defstruct Element :name :content )
( defstruct Architecture :name :content )
( defstruct Organization :name :content )
( defstruct Guidance :name :content )
( defstruct Document :describesArchitecture :name :content )
( defstruct Action :mayBeA :name :content )
( defstruct Agreement :name :content )
( defstruct Standard :name :content )
( defstruct Task :name :content )
( defstruct InformationAsset :name :content )
( defstruct ConceptualDataModel :name :content )
( defstruct ActivityModel :name :content )
( defstruct Node )
( defstruct Network :name :content )
( defstruct Requirement :name :content )
( defstruct InfoExchRequirement :name :content )
( defstruct ExchangeNeedLineReq :name :content )
( defstruct MissionArea :name :content )
( defstruct System :name :content )
( defstruct Mission :isCitedBy :name :content )
( defstruct FunctionalArea :name :content )
( defstruct Capability :name :content )
( defstruct MaterielItem :name :content )
( defstruct EquipmentType :name :content )
( defstruct SoftwareItem :isSourceFor :name :content )
( defstruct Facility :name :content )
