( defstruct IUmlType )
( defstruct ICdeComponentSpec )
( defstruct IUmlClass )
( defstruct IUmlComponent )
( defstruct ICdeServer )
( defstruct ICdeComponent )
( defstruct IUmlMember )
( defstruct ICdeMember )
( defstruct ICdeMemberExe :executionPerformance :resourceNeeded :executionDetails )
