( defstruct LocatedElement )
( defstruct Package :name :problem )
( defstruct Import :fqn )
( defstruct ChocoProblem :name )
( defstruct Element :label )
( defstruct Expression :label )
( defstruct ConstraintDef :op :left :right :label )
( defstruct IntVar :domain :label )
( defstruct Domain :lower :upper )
( defstruct IntConstant :val :label )
( defstruct SymbolicTerm :term :label )
( defstruct IntValue :val :label )
( defstruct IntExp :op :left :right :label )
( defstruct Constraint :op :left :right :label )
( defstruct PostConstraint :op :constraint :label )
