( defstruct PCDATA :value )
( defstruct Any )
( defstruct TitledElement )
( defstruct IdedElement )
( defstruct ConventionnedElement :convention )
( defstruct DictRefElement )
( defstruct SimpleLink_Element :href )
( defstruct Counted_Element :count )
( defstruct Sized_Element )
( defstruct Rows_Element :rows )
( defstruct Columns_Element :colums )
( defstruct Min_Element )
( defstruct Max_Element )
( defstruct Units_Element )
( defstruct AngleUnits_Element :angleUnits )
( defstruct UnitsRef_Element )
( defstruct AtomRefs_Element )
( defstruct _StringBuiltin )
( defstruct _String :value :convention )
( defstruct _Link :value :href :convention )
( defstruct _FloatBuiltin )
( defstruct _Float :value :convention )
( defstruct _IntegerBuiltin )
( defstruct _Integer :value :convention )
( defstruct _StringArray :value :convention )
( defstruct _FloatArray :value :convention )
( defstruct _IntegerArray :value :convention )
( defstruct _FloatMatrix :value :rows :colums :convention )
( defstruct _Coordinate2Builtin )
( defstruct _Coordinate2 :value :convention )
( defstruct _Coordinate3Builtin )
( defstruct _Coordinate3 :value :convention )
( defstruct _Angle :value :angleUnits :convention )
( defstruct _Torsion :value :angleUnits :convention )
( defstruct _List )
( defstruct Molecule :count :convention )
( defstruct Formula :count :convention )
( defstruct Atom :count :convention )
( defstruct Atom_Array :convention )
( defstruct Bond :convention )
( defstruct Bond_Array :convention )
( defstruct Electron :count :convention )
( defstruct Reaction :convention )
( defstruct Crystal :convention )
( defstruct Sequence :convention )
( defstruct Feature :convention )
