( defstruct Thing )
( defstruct Meta-Reviewer )
( defstruct Reviewer )
( defstruct Decision )
( defstruct Person )
( defstruct Document )
( defstruct Preference )
( defstruct ProgramCommittee )
( defstruct Bid )
( defstruct Conference )
( defstruct ConferenceChair )
( defstruct ConferenceMember )
( defstruct AssociatedChair )
( defstruct ProgramCommitteeMember )
( defstruct AuthorNotReviewer )
( defstruct SubjectArea )
( defstruct ExternalReviewer :assignedByReviewer )
( defstruct Chairman )
( defstruct ProgramCommitteeChair )
( defstruct Acceptance )
( defstruct Rejection )
( defstruct Review )
( defstruct Paper :readByReviewer )
( defstruct Author )
( defstruct User )
( defstruct Co-author )
( defstruct PaperAbstract :readByReviewer )
( defstruct PaperFullVersion :readByReviewer )
( defstruct Administrator )
( defstruct Meta-Review )
