( defstruct COBOLElement :level :refined :name :sharedType :source )
( defstruct COBOLClassifier :typeded :name )
( defstruct COBOLSimpleType :usageValue :pictureString :usage :typeded :name )
( defstruct COBOLComposedType :typeded :name )
( defstruct COBOLElementInitialValue :initVal :valueKind )
( defstruct COBOL88Element :name :has )
( defstruct COBOL88ElementValue :lowerLimit :upperLimit :range )
( defstruct COBOLRedefiningElement :redefines :level :refined :name :sharedType :source )
( defstruct COBOL66Element :name :start )
( defstruct COBOLSourceText :source :fileName )
( defstruct COBOLFixedLengthArray :maxUpper )
( defstruct COBOLVariableLengthArray :minUpper :dependingOn :maxUpper )
