( defstruct Thing )
( defstruct Meta-Reviewer )
( defstruct Reviewer )
( defstruct Decision )
( defstruct Preference )
( defstruct ProgramCommittee )
( defstruct Bid )
( defstruct Conference )
( defstruct ConferenceChair )
( defstruct ConferenceMember )
( defstruct AssociatedChair )
( defstruct ProgramCommitteeMember )
( defstruct AuthorNotReviewer )
( defstruct SubjectArea )
( defstruct ExternalReviewer :assignedByReviewer )
( defstruct Chairman )
( defstruct ProgramCommitteeChair )
( defstruct Acceptance )
( defstruct Rejection )
( defstruct Review )
( defstruct Paper :readByReviewer )
( defstruct Author )
( defstruct Co-author )
( defstruct PaperAbstract :readByReviewer )
( defstruct PaperFullVersion :readByReviewer )
( defstruct Administrator )
( defstruct Meta-Review )
( defstruct Workshop )
( defstruct Event )
( defstruct Account )
( defstruct Inforamtion )
( defstruct User )
( defstruct Role )
( defstruct Help_Request )
( defstruct Person )
( defstruct Symposium )
( defstruct Abstract :readByReviewer )
( defstruct Document )
( defstruct Invited_Paper :readByReviewer )
( defstruct Admin_Role )
( defstruct Paper_Typologies )
( defstruct Event_Setup )
( defstruct Event_URL )
( defstruct URL )
( defstruct Notification_Email )
( defstruct Email )
( defstruct Short_Paper :readByReviewer )
( defstruct Author_Role )
( defstruct Preview )
( defstruct Review_Form )
( defstruct Committe_Role )
( defstruct Group_Email )
( defstruct Submission_Template )
( defstruct Review_Form_Setup )
( defstruct Misc )
( defstruct Event_Creation )
( defstruct Approval_Email )
( defstruct Rejection_Email )
( defstruct Submission )
( defstruct Template )
( defstruct Feature_Request )
( defstruct Committee )
( defstruct Event_Tracks )
( defstruct Request )
( defstruct Activity )
( defstruct Head_Role )
( defstruct Detail )
( defstruct Corresponding_Author )
( defstruct Reviewer_Role )
( defstruct Event_Approval )
( defstruct Registration )
( defstruct Full_Paper :readByReviewer )
( defstruct Research_Topic )
( defstruct Description )
( defstruct Assistance )
( defstruct Email_Template )
