( defstruct Package :ownedEltColl )
( defstruct ProviderClause :ownedEltColl )
( defstruct CollaborationPackage :ownedElt )
( defstruct Collaboration :ownedEltAss :ownedEltClass )
( defstruct InteractionPackage :providerClause :ownedElt )
( defstruct Interaction :context :message )
( defstruct AssociationRole :connection )
( defstruct ClassifierRole :receiverMess :senderMess :base )
( defstruct AssociationEndRole :associationRole :type )
( defstruct Message :receiver :sender :specification )
( defstruct Request )
( defstruct Operation :owner )
( defstruct Interface )
