( defstruct Thing )
( defstruct Meta-Reviewer )
( defstruct Reviewer )
( defstruct Decision )
( defstruct Person )
( defstruct Preference )
( defstruct ProgramCommittee )
( defstruct Bid )
( defstruct Conference )
( defstruct ConferenceChair )
( defstruct ConferenceMember )
( defstruct AssociatedChair )
( defstruct ProgramCommitteeMember )
( defstruct AuthorNotReviewer )
( defstruct SubjectArea )
( defstruct ExternalReviewer :assignedByReviewer )
( defstruct Chairman )
( defstruct ProgramCommitteeChair )
( defstruct Acceptance )
( defstruct Rejection )
( defstruct Paper :readByReviewer )
( defstruct Author )
( defstruct Co-author )
( defstruct PaperAbstract :readByReviewer )
( defstruct PaperFullVersion :readByReviewer )
( defstruct Administrator )
( defstruct Meta-Review )
( defstruct Event )
( defstruct Account )
( defstruct Inforamtion )
( defstruct User )
( defstruct Role )
( defstruct Help_Request )
( defstruct Symposium )
( defstruct Abstract :readByReviewer )
( defstruct Document )
( defstruct Invited_Paper :readByReviewer )
( defstruct Admin_Role )
( defstruct Paper_Typologies )
( defstruct Event_Setup )
( defstruct Event_URL )
( defstruct Notification_Email )
( defstruct Email )
( defstruct Short_Paper :readByReviewer )
( defstruct Author_Role )
( defstruct Preview )
( defstruct Review_Form )
( defstruct Committe_Role )
( defstruct Group_Email )
( defstruct Submission_Template )
( defstruct Review_Form_Setup )
( defstruct Misc )
( defstruct Event_Creation )
( defstruct Approval_Email )
( defstruct Rejection_Email )
( defstruct Submission )
( defstruct Template )
( defstruct Feature_Request )
( defstruct Event_Tracks )
( defstruct Request )
( defstruct Activity )
( defstruct Head_Role )
( defstruct Detail )
( defstruct Corresponding_Author )
( defstruct Reviewer_Role )
( defstruct Event_Approval )
( defstruct Registration )
( defstruct Full_Paper :readByReviewer )
( defstruct Research_Topic )
( defstruct Description )
( defstruct Assistance )
( defstruct Email_Template )
( defstruct Conference_participant )
( defstruct Active_conference_participant )
( defstruct Passive_conference_participant )
( defstruct Review_expertise )
( defstruct Submitted_contribution )
( defstruct Regular_author )
( defstruct Conference_contributor )
( defstruct Contribution_1th-author )
( defstruct Contribution_co-author )
( defstruct Conference_contribution )
( defstruct Co-chair )
( defstruct Committee )
( defstruct Committee_member )
( defstruct Abstract )
( defstruct Extended_abstract )
( defstruct Important_dates )
( defstruct Invited_speaker )
( defstruct Conference_proceedings )
( defstruct Information_for_participants )
( defstruct Conference_document )
( defstruct Regular_contribution )
( defstruct Poster )
( defstruct Written_contribution )
( defstruct Conference_applicant )
( defstruct Camera_ready_contribution )
( defstruct Accepted_contribution )
( defstruct Program_committee )
( defstruct Organizing_committee )
( defstruct Steering_committee )
( defstruct Conference_volume )
( defstruct Call_for_paper )
( defstruct Conference_announcement )
( defstruct Invited_talk )
( defstruct Conference_part )
( defstruct Presentation )
( defstruct Chair )
( defstruct Track )
( defstruct Workshop )
( defstruct Tutorial )
( defstruct Rejected_contribution )
( defstruct Reviewed_contribution )
( defstruct Review )
( defstruct Topic )
( defstruct Late_paid_applicant )
( defstruct Paid_applicant )
( defstruct Early_paid_applicant )
( defstruct Organizer )
( defstruct Call_for_participation )
( defstruct Publisher )
( defstruct Registeered_applicant )
( defstruct Track-workshop_chair )
( defstruct Conference_www )
( defstruct Conference_fees )
( defstruct Review_preference )
( defstruct Accepted_Paper :has_author )
( defstruct paper :has_author )
( defstruct Rejected_Paper :has_author )
( defstruct Undecided_Paper :has_author )
( defstruct Manual_Paper_Assignment :is_performed_by )
( defstruct Program_Committee_member )
( defstruct paper_assignment :is_performed_by )
( defstruct intensity )
( defstruct start_date_of_camera-ready_submission )
( defstruct camera-ready_submission_date )
( defstruct date_of_notification )
( defstruct date )
( defstruct article )
( defstruct Contact_Person )
( defstruct conference )
( defstruct bidding_of_reviewer :is_performed_by )
( defstruct activity )
( defstruct URL )
( defstruct conference_setup )
( defstruct human )
( defstruct managing_of_conference_process )
( defstruct Program_Committee_Chair )
( defstruct reviewing_proces )
( defstruct end_date_of_camera-ready_submission )
( defstruct abstract_submission_date )
( defstruct group_email )
( defstruct Senior_Reviewer_URL )
( defstruct notification :has_result :is_performed_by )
( defstruct notification_email )
( defstruct Chair_URL )
( defstruct abstract_of_paper )
( defstruct submission_process :is_performed_by )
( defstruct topic )
( defstruct lower_tier_reviewing_process )
( defstruct start_date_of_conference )
( defstruct date_of_conference )
( defstruct Senior_Program_Committee_member )
( defstruct end_date_of_abstract_submission )
( defstruct phase_of_conference )
( defstruct Regular_Program_Committee_member )
( defstruct review :gives_classification :is_created_in )
( defstruct start_date_of_full_paper_submission )
( defstruct full_paper_submission_date )
( defstruct start_date_of_abstract_submission )
( defstruct end_date_of_conference )
( defstruct review_form :is_created_in )
( defstruct Automatic_Paper_Assignment :is_performed_by )
( defstruct institute )
( defstruct classification )
( defstruct summary_of_reviews :is_created_in )
( defstruct upper_tier_reviewing_process :is_performed_by )
( defstruct end_date_of_full_paper_submission )
( defstruct acceptance_notification_email )
( defstruct rejection_notification_email )
( defstruct Contact_Person_URL )
( defstruct Regular_Reviewer_URL )
( defstruct Trip )
( defstruct Banquet )
( defstruct Reception )
( defstruct Social_event )
( defstruct Contribution )
( defstruct City )
( defstruct Organization )
( defstruct Country )
( defstruct Company )
( defstruct University )
( defstruct Scholar )
( defstruct Poster )
( defstruct Short_paper )
( defstruct Reviewing_results_event )
( defstruct Administrative_event )
( defstruct Reviewing_event )
( defstruct Registration_of_participants_event )
( defstruct Submission_event )
( defstruct Camera_Ready_event )
( defstruct Working_event )
( defstruct Member )
( defstruct Participant )
( defstruct Member_PC )
( defstruct Chair_PC )
( defstruct Student )
( defstruct Science_Worker )
( defstruct Assistant )
( defstruct Volunteer )
( defstruct Regular )
