( defstruct ControllerAttribute :controller )
( defstruct Controller :behavior )
( defstruct StateMachine )
( defstruct State )
( defstruct SubControllerState :controller )
( defstruct ViewState )
( defstruct StateTransition :source :target :trigger )
( defstruct StateMachineAction )
( defstruct Event )
