( defstruct InterfaceDef )
( defstruct OperationDef )
( defstruct ValueDef )
( defstruct ComponentDef :isBasic )
( defstruct ProvidesDef :provides :prd_home )
( defstruct UsesDef :multiple :uses :ud_home )
( defstruct EventDef :type )
( defstruct EmitsDef :ed_home :type )
( defstruct PublishesDef :pud_home :type )
( defstruct ConsumesDef :cd_home :type )
( defstruct HomeDef :manages )
( defstruct FactoryDef :fa_home )
( defstruct FinderDef :fi_home )
( defstruct PrimaryKeyDef :pkd_home :type )
