( defstruct CDerived )
( defstruct CStructured )
( defstruct CBehavorialFeature )
( defstruct CFunction :isVsrArg )
( defstruct CStructureContents )
( defstruct CField )
( defstruct CDerivableType )
( defstruct CPPReference )
( defstruct CPPExtern :linkage )
( defstruct CPPConst )
( defstruct CPPTemplate )
( defstruct CPPClass :isAbstract :isVolatile :visibility )
( defstruct CPPGeneralization :visibility :isVirtual :supertype )
( defstruct CPPOperation :isStatic :isExtern :isInline :isVirtual :isPure :visibility :isCtor :isDtor :isVsrArg )
( defstruct CPPOperator :isInline :visibility )
( defstruct CPPMember :isStatic :isVolatile :isRegister :visibility )
