( defstruct Condition )
( defstruct CompositeParDef )
( defstruct ElementaryPartDef )
( defstruct ElementaryActDef :actCompositeMember )
( defstruct CompositeActDef :actCompositeMember )
( defstruct ActCompositeMember )
( defstruct ActivityDefinition :actCompositeMember )
( defstruct PartDefinition )
( defstruct PartCompositeMember :partDefinitions )
