( defstruct Member :name )
( defstruct TypedAttribute :type :name )
( defstruct Field :type :name )
( defstruct Property :isReadable :isWritable :type :name )
( defstruct MethodBase :visibility :isAbstract :isFinal :isStatic :name )
( defstruct Constructor :visibility :isAbstract :isFinal :isStatic :name )
( defstruct Method :returnType :visibility :isAbstract :isFinal :isStatic :name )
( defstruct Type :qualifiedName :isAbstract :visibility :isSealed :nameSpace :name )
( defstruct Parameter :isIn :isOut :name :position :method :type )
( defstruct Assembly :name )
