( defstruct CSM :step :generalResource :scenarion )
( defstruct GeneralResource )
( defstruct Step :activeResource :step :root )
( defstruct Scenarion :step :root )
( defstruct Start :activeResource :step :root )
( defstruct End :activeResource :step :root )
( defstruct ResourceAcquire :generalResource :activeResource :step :root )
( defstruct ResourceRelease :generalResource :activeResource :step :root )
( defstruct Workload :start )
( defstruct Component )
( defstruct ProcessingResource )
( defstruct ExternalService )
( defstruct ActiveResource )
( defstruct PassiveResource )
( defstruct Message )
( defstruct PathConnection )
( defstruct Join )
( defstruct Fork )
( defstruct Merge )
( defstruct Branch )
( defstruct Seqence )
