( defstruct BooleanExpression :expresssion )
( defstruct ModelElement :name :visibility )
( defstruct Dependency :kind :clients :suppliers :name :visibility )
( defstruct Constraint :body :name :visibility )
( defstruct Feature :name :visibility )
( defstruct StructuralFeature :type :name :visibility )
( defstruct Attribute :type :name :visibility )
( defstruct NameSpace :name :visibility )
( defstruct Classifier :name :visibility )
( defstruct Package :name :visibility )
( defstruct Class :name :visibility )
( defstruct Datatype :name :visibility )
( defstruct Subsystem :name :visibility :name :visibility )
( defstruct Model :name :visibility )
