( defstruct QueryExpression :expresssion )
( defstruct CheckConstraint )
( defstruct Column :precision :scale :isNullable :length :collectionName :characterSetName :type )
( defstruct ColumnSet )
( defstruct NamedColumnSet :optionScopeColumn )
( defstruct QueryColumnSet :query )
( defstruct Table :isTemporary :temporaryScope :isSystem :optionScopeColumn )
( defstruct View :isReadOnly :checkOption :queryExpression :optionScopeColumn )
( defstruct Trigger :namedColumnSet )
( defstruct SQLDataType :typeNumber )
( defstruct SQLDistinctType :length :precision :scale :sqlSimpleType :typeNumber )
( defstruct SQLSimpleType :characterMaximumLength :characterOctetLength :numericPrecision :numericPrecisionRadix :numericScale :dateTimePrecision :typeNumber )
