( defstruct DeploymentReport )
( defstruct DeploymentImport :alias :identity )
( defstruct ImportNamespaceIdentity :import :name )
( defstruct NamespaceIdentity :name )
( defstruct Applications )
( defstruct LogicalServers )
( defstruct OuterSystem :name )
( defstruct Binding )
( defstruct Zone :name )
( defstruct ReportObject :name :definition :extends :instanceId )
( defstruct SequenceReport :report :setting )
( defstruct BoundLogicalServer :name :definition :extends )
( defstruct LogicalServer :name :definition :extends :instanceId )
( defstruct Application :name :definition :extends :instanceId )
( defstruct ReportSystem :name :definition :extends :instanceId )
( defstruct ReportResource :name :definition :extends :instanceId )
( defstruct ReportEndpoint :name :definition :extends :instanceId )
( defstruct Setting :settingAttributes )
( defstruct SettingFacet :settingAttributes )
( defstruct SettingInstanceValue )
( defstruct SettingAttributes :name :definition )
( defstruct SettingValue )
( defstruct ErrorCollection )
( defstruct DocumentError :Code :Level )
( defstruct DocumentResolutionError :Statement :Code :Level )
( defstruct DocumentConstraintError :constraintMember :constraintDefinition :Code :Level )
( defstruct FailedInput )
( defstruct Description )
( defstruct Guid :value )
( defstruct SimpleName :value )
( defstruct Path :value )
( defstruct FourPartVersionType :value )
( defstruct PublicKeyType :value )
( defstruct PublicKeyTokenType :value )
( defstruct Culture :value )
( defstruct CultureNeutral :value )
( defstruct Element :value )
