( defstruct Dimension :width :heigth )
( defstruct Point :x :y )
( defstruct BezierPoint :x :y )
( defstruct Property :key :value )
( defstruct DiagramElement :isVisible )
( defstruct Reference :isIndividualRepresentation :referenced :isVisible )
( defstruct GraphElement :position :semanticModel :isVisible )
( defstruct GraphEdge :anchors :position :semanticModel :isVisible )
( defstruct GraphNode :position :semanticModel :isVisible )
( defstruct GraphConnector :position :gc_graphElement )
( defstruct DiagramLink :zoom :viewPort :dl_graphElement :dl_diagram )
( defstruct SemanticModelBridge :presentation )
( defstruct Diagram :name :zoom :viewPort :namespace :position :semanticModel :isVisible )
( defstruct SimpleSemanticModelElement :typeInfo :presentation )
( defstruct UML1SemanticModelBridge :element :presentation )
( defstruct CoreSemanticModelBridge :element :presentation )
( defstruct CoreElement )
( defstruct ElementsElement )
( defstruct LeafElement :isVisible )
( defstruct TextElement :text :isVisible )
( defstruct Image :uri :mimeType :isVisible )
( defstruct GraphicPrimitive :isVisible )
( defstruct Polyline :waypoints :closed :isVisible )
( defstruct Ellipse :center :radiusX :radiusY :rotation :startAngle :endAngle :isVisible )
