( defstruct Element :name :description :view )
( defstruct DoDAFModel :name :description :view )
( defstruct Document :type :name :description :view )
( defstruct SystemFunctionalityDescription :type :name :description :view )
( defstruct FunctionalSpecification :mayBeA :type :name :description :view )
( defstruct AMSpecification :type :name :description :view )
( defstruct SystemDocument :name :description :view )
( defstruct ArchitectureDocument :name :description :view )
( defstruct System :name :description :view )
( defstruct SystemPA :name :description :view )
( defstruct IE :name :description :view )
( defstruct AMIERole :name :description :view )
( defstruct AMIERoleGraphic :name :description :view )
( defstruct Input :source :destination :information :name :description :view )
( defstruct Output :source :destination :information :name :description :view )
( defstruct InformationAssetDocument :name :description :view )
( defstruct AMPA :name :description :view )
( defstruct AMPAGraphic :name :description :view )
( defstruct PA :name :description :view )
( defstruct PACapability :name :description :view )
( defstruct AM :type :name :description :view )
( defstruct InformationAsset :name :description :view )
( defstruct DataStore :name :description :view )
( defstruct SystemFunction :name :description :view )
( defstruct SystemPAStandard :name :description :view )
( defstruct InformationTechnologyStandard :name :description :view )
( defstruct LineOfBusiness :name :description :view )
( defstruct Task :levelIdentifier :references :cost :name :description :view )
( defstruct HumanBehaviourTask :levelIdentifier :references :cost :name :description :view )
( defstruct OperationalCapabilityTask :levelIdentifier :references :cost :name :description :view )
( defstruct TaskMissionArea :levelIdentifier :references :cost :name :description :view )
( defstruct PATask :levelIdentifier :references :cost :name :description :view )
( defstruct BusinessSubfunction :name :description :view )
( defstruct ArchitectureBusinessSubFunction :name :description :view )
( defstruct OperationalRolePA :name :description :view )
( defstruct OperationalRole :name :description :view )
( defstruct OrganizationTypeOperationalRole :name :description :view )
( defstruct OrganizationOperationalRole :name :description :view )
( defstruct Occupation :name :description :view )
( defstruct PersonType :name :description :view )
( defstruct PersonTypeCapabilityNorm :name :description :view )
( defstruct Skill :name :description :view )
( defstruct Position :name :description :view )
