( defstruct Element :name :description :view )
( defstruct DoDAFModel :name :description :view )
( defstruct Document :type :name :description :view )
( defstruct AMSpecification :type :name :description :view )
( defstruct AMSpecificationElement :name :description :view )
( defstruct PAExchangeRequirement :name :description :view )
( defstruct ArchitectureDocument :name :description :view )
( defstruct IE :name :description :view )
( defstruct AMIERole :name :description :view )
( defstruct Control :source :destination :name :description :view )
( defstruct Input :source :destination :information :name :description :view )
( defstruct Output :source :destination :information :name :description :view )
( defstruct Mechanism :source :destination :resourceType :name :description :view )
( defstruct MechanismSystem :source :destination :resourceType :name :description :view )
( defstruct MechanismReference :source :destination :resourceType :name :description :view )
( defstruct MechanismFacility :source :destination :resourceType :name :description :view )
( defstruct InformationAssetDocument :name :description :view )
( defstruct AMPA :name :description :view )
( defstruct PACapability :name :description :view )
( defstruct PA :name :description :view )
( defstruct AM :type :name :description :view )
( defstruct InformationAsset :name :description :view )
( defstruct Task :levelIdentifier :references :cost :name :description :view )
( defstruct PATask :isCitedBy :levelIdentifier :references :cost :name :description :view )
( defstruct Organization :type :name :description :view )
( defstruct OrganizationType :name :description :view )
( defstruct OperationalRole :name :description :view )
( defstruct Occupation :name :description :view )
( defstruct PersonType :name :description :view )
( defstruct Skill :name :description :view )
( defstruct DOSCR :mayBeAn :name :description :view )
