( defstruct Element :name :description :view )
( defstruct DoDAFModel :name :description :view )
( defstruct Document :type :name :description :view )
( defstruct SystemFunctionTraceabilityMatrix :type :name :description :view )
( defstruct SystemFunctionTraceabilityElement :supportStatusCode :name :description :view )
( defstruct SystemDocument :name :description :view )
( defstruct ArchitectureDocument :name :description :view )
( defstruct PA :name :description :view )
( defstruct SystemFunction :name :description :view )
( defstruct SystemPA :name :description :view )
( defstruct SoftwareApplicationProcedurePA :name :description :view )
( defstruct AM :type :name :description :view )
( defstruct InformationAsset :name :description :view )
( defstruct AMPA :name :description :view )
( defstruct System :name :description :view )
( defstruct Task :levelIdentifier :references :cost :name :description :view )
( defstruct ArchitectureTask :name :description :view )
( defstruct OperationalCapabilityTask :isAccomplishedA :levelIdentifier :references :cost :name :description :view )
( defstruct SystemOperationalCapabilityTask :levelIdentifier :references :cost :name :description :view )
( defstruct PATask :levelIdentifier :references :cost :name :description :view )
( defstruct Capability :name :description :view )
( defstruct CapabilityDocument :name :description :view )
( defstruct SystemCapability :name :description :view )
( defstruct NetworkCapability :name :description :view )
( defstruct NodeLinkCapability :name :description :view )
( defstruct MaterielItemCapabilityNorm :name :description :view )
( defstruct OrganizationTypeCapabilityNorm :name :description :view )
( defstruct RequiredInformationTechnologyCapability :name :description :view )
( defstruct InformationTechnologyRequirement :name :description :view )
( defstruct InformationExchangeRequirement :name :description :view )
( defstruct PAExchangeRequirement :name :description :view )
