( defstruct Element :name :content )
( defstruct System :name :content )
( defstruct SystemRole :terminatesAt :name :content )
( defstruct SystemFunction :terminatesAt :name :content )
( defstruct Service :terminatesAt :name :content )
( defstruct SystemRoleInterface :originatesFrom :name :content )
( defstruct ServiceDependency :originatesFrom :name :content )
( defstruct ServiceProvider :terminatesAt :name :content )
( defstruct ServiceMediator :terminatesAt :name :content )
( defstruct ServiceRegistry :terminatesAt :name :content )
( defstruct ServiceLocator :terminatesAt :name :content )
( defstruct ServiceBroker :terminatesAt :name :content )
( defstruct SystemAtNode :references :terminatesAt :name :content )
( defstruct SystemAtNodeInterface :originatesFrom :name :content )
( defstruct SystemsNode :name :content )
( defstruct COI :defines :name :content )
( defstruct Vocabulary :name :content )
( defstruct DataReference :defineBy :name :content )
( defstruct Performer :name :content )
( defstruct OperationalRole :name :content )
( defstruct OperationalActivity :name :content )
( defstruct Product :name :content )
( defstruct Material :name :content )
( defstruct Data :name :content )
( defstruct SystemProductFlow :originatesFrom :name :content )
( defstruct ConstraintOrRequirement :name :content )
( defstruct Constraint :name :content )
( defstruct QualityRequirement :name :content )
( defstruct DIA :nmjic :higherEchelon :name :content )
( defstruct NMJIC :dia :name :content )
( defstruct HigherEchelon :dia :jfc :name :content )
( defstruct JFC :higherEchelon :f2c2 :componentComand :name :content )
( defstruct F2C2 :jfc :name :content )
( defstruct ComponentCommand :jfc :name :content )
( defstruct DJFLCC :jfc :name :content )
( defstruct JFACC :subordinateAirCommand :jfc :name :content )
( defstruct JFMCC :jfc :name :content )
( defstruct JFSOCC :jfc :name :content )
( defstruct SubordinateAirCommand :jfacc :name :content )
( defstruct MAW :jfacc :name :content )
( defstruct WOC :jfacc :name :content )
( defstruct AOCCID :name :content )
( defstruct AOCCombatPlanStrategyCells :name :content )
( defstruct ResultData :sourceID :timeStamp )
( defstruct CombatReport :friendlyUnitsInvolved :combatLocation :resultsAssessment :duration :sourceID :timeStamp )
( defstruct WSV :missionID :weaponfSystemID :videoType :sourceID :timeStamp )
( defstruct MISREP :missionID :missionObjectives :missionAssesments :sourceID :timeStamp )
( defstruct Imagery :imageType :spectralData :geospacialLocation :imageSize :sourceID :timeStamp )
( defstruct CollectionRequirement :sourceID :collectionTargetID :toBeDoneByTime :specialNeeds )
( defstruct BDAReport :targetID :reportSourceID :assesmentSumart :validityDuration :rd )
( defstruct MunitionsEffectsAssesment :ato :tn )
( defstruct ATO :timePeriod :mea )
( defstruct RestrikeRecommendation :tn )
( defstruct TargetNomination :target )
( defstruct TargetMaterialsAnalysis :targetID :target )
( defstruct Target )
( defstruct MIDB )
