( defstruct Label :element )
( defstruct SimpleLabel :content :element )
( defstruct ComplexLabel :compartments :element )
( defstruct Compartment :complexLabel )
( defstruct VerticalCompartment :complexLabel )
( defstruct HorizontalCompartment :complexLabel )
( defstruct SimpleCompartment :content :complexLabel )
( defstruct Anchor :name )
( defstruct GraphElement :name )
( defstruct Graph :type :name )
( defstruct Layer :graph :name )
( defstruct Nodelike :name )
( defstruct SubGraph :name )
( defstruct Node :name )
( defstruct Arc :fromNode :toNode :name )
( defstruct DirectedArc :fromNode :toNode :name )
( defstruct UndirectedArc :fromNode :toNode :name )
( defstruct Shape :width :height :peripheries :name )
( defstruct NodeShape :width :height :peripheries :name )
( defstruct SimpleNodeShape :width :height :peripheries :name )
( defstruct PointNodeShape :width :height :peripheries :name )
( defstruct ComplexNodeShape :width :height :peripheries :name )
( defstruct PolygonNodeShape :sides :skew :distortion :isRegular :orientation :width :height :peripheries :name )
( defstruct MNodeShape :width :height :peripheries :name )
( defstruct RecordNodeShape :width :height :peripheries :name )
( defstruct ArrowShape :clipping :isPlain :size :width :height :peripheries :name )
