( defstruct NamedElement :name )
( defstruct Assembly :location :imageRuntimeVersion :evidence :codeBase :entryPoint :manifestModule :manifest :name )
( defstruct ManifestResource :content :assembly )
( defstruct Module :qualifiedName :scopeName :assembly :name )
( defstruct MemberInfo :memberType :declaringType :name )
( defstruct PropertyInfo :propertyType :memberType :declaringType :name )
( defstruct FieldInfo :fieldType :memberType :declaringType :name )
( defstruct EventInfo :eventHandlerType :memberType :declaringType :name )
( defstruct ParameterInfo :position :parameterType :member :name )
( defstruct MethodBase :memberType :declaringType :name )
( defstruct MethodInfo :memberType :declaringType :name )
( defstruct ConstructorInfo :memberType :declaringType :name )
( defstruct Type :namespace :module :memberType :declaringType :name )
