( defstruct Model :domainModel )
( defstruct Element :type :id )
( defstruct ModelElement :parentLink :type :id )
( defstruct ModelElementLink :parentLink :type :id )
( defstruct EmbeddingLink :name )
( defstruct ReferenceLink :modelElement :roles :type :id )
( defstruct NamedElement :name )
( defstruct Property :owner :value :name )
( defstruct Role :element :owner :name )
( defstruct Value )
( defstruct IntegerValue :value )
( defstruct DoubleValue :value )
( defstruct BooleanValue :value )
( defstruct StringValue :value )
