( defstruct NamedElement :name :identity )
( defstruct LoadedElement :isLoaded :namespace :name :identity )
( defstruct Namespace :namespace :name :identity )
( defstruct DomainModel :isLoaded :namespace :name :identity )
( defstruct Classifier :isAbstract :domainModel :isLoaded :namespace :name :identity )
( defstruct Class :isSerializationRoot :isAbstract :domainModel :isLoaded :namespace :name :identity )
( defstruct Relationship :isEmbedding :roles :isAbstract :domainModel :isLoaded :namespace :name :identity )
( defstruct Role :min :max :isUnbounded :accepts :isOrdered :isNavigableFrom :isPropertyGenerator :source :type :relation :name :identity )
( defstruct ValueProperty :owner :type :name :identity )
( defstruct Type :namespace :name :identity )
( defstruct SimpleType :namespace :name :identity )
( defstruct EnumerationLiteral :value :name :identity )
( defstruct Enumeration :namespace :name :identity )
