( defstruct TypeDescription :name )
( defstruct Notation :content :name )
( defstruct Entity :content :isInternal :name )
( defstruct Element :name )
( defstruct AnyElement :name )
( defstruct RestrictedElement :name )
( defstruct ElementContent )
( defstruct Mixed :elements )
( defstruct Children :occ )
( defstruct Sequence :children :occ )
( defstruct Leaf :elementName :occ )
( defstruct Choice :childrenChoice :occ )
( defstruct AttributeList :containsAttributes :name )
( defstruct AttributeDescription :attributeList :type :name )
( defstruct NoDefaultValue :isRequired :attributeList :type :name )
( defstruct DefaultValue :value :isFixed :attributeList :type :name )
( defstruct AttributeType )
( defstruct Enumeration :values )
( defstruct OtherAttributeType :type )
