( defstruct RoutingChain )
( defstruct QueuingNetwork :center :workLoad )
( defstruct ExecutionGraph :nodeNested :node )
( defstruct Center :node :queuingNetwork )
( defstruct Node :nested :executionGraph :demand )
( defstruct Special :node :queuingNetwork )
( defstruct ActiveCenter :node :queuingNetwork )
( defstruct PassiveCenter :node :queuingNetwork )
( defstruct Source :node :queuingNetwork )
( defstruct Sink :node :queuingNetwork )
( defstruct Fork :node :queuingNetwork )
( defstruct Join :node :queuingNetwork )
( defstruct Split :node :queuingNetwork )
( defstruct Allocate :node :queuingNetwork )
( defstruct Release :node :queuingNetwork )
