( defstruct Express_metamodel::Rules::ONEOFConstraint :Express_metamodel::Rules::SubtypeConstraint::constrained-subtypes :Express_metamodel::Rules::SubtypeConstraint::equivalent-rule :Express_metamodel::Rules::SubtypeConstraint::collection )
( defstruct Express_metamodel::Rules::SupertypeRule :Express_metamodel::Rules::SupertypeRule::named-supertype :assertsAbstract :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Rules::SubtypeConstraint :Express_metamodel::Rules::SubtypeConstraint::constrained-subtypes :Express_metamodel::Rules::SubtypeConstraint::equivalent-rule :Express_metamodel::Rules::SubtypeConstraint::collection )
( defstruct Express_metamodel::Rules::Extent :Express_metamodel::Rules::Extent::within-population :Express_metamodel::Rules::Extent::for-type :id :Express_metamodel::Instances::SETValue::of-type :Express_metamodel::Instances::AggregateValue::of-type :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Rules::TOTAL_OVERConstraint :Express_metamodel::Rules::SubtypeConstraint::constrained-subtypes :Express_metamodel::Rules::SubtypeConstraint::equivalent-rule :Express_metamodel::Rules::SubtypeConstraint::collection )
( defstruct Express_metamodel::Rules::ANDConstraint :Express_metamodel::Rules::SubtypeConstraint::constrained-subtypes :Express_metamodel::Rules::SubtypeConstraint::equivalent-rule :Express_metamodel::Rules::SubtypeConstraint::collection )
( defstruct Express_metamodel::Rules::GlobalRule :Express_metamodel::Rules::GlobalRule::constrained-extents :Express_metamodel::Rules::GlobalRule::contains-rules :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Rules::NamedRule :Express_metamodel::Rules::NamedRule::namespace :Express_metamodel::Rules::NamedRule::asserts-expression :position :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Statements::ProcedureCall :Express_metamodel::Statements::ProcedureCall::invokes )
( defstruct Express_metamodel::Statements::SkipStatement :Express_metamodel::Statements::SkipStatement::in-block )
( defstruct Express_metamodel::Statements::AliasStatement :Express_metamodel::Statements::AliasStatement::binds-to-reference :Express_metamodel::Statements::AliasStatement::body :Express_metamodel::Statements::AliasStatement::alias-variable )
( defstruct Express_metamodel::Statements::ControlVariable :Express_metamodel::Statements::ControlVariable::bound-value :Express_metamodel::Statements::ControlVariable::initial-value :Express_metamodel::Statements::ControlVariable::namespace :Express_metamodel::Statements::ControlVariable::increment :Express_metamodel::Algorithms::NamedVariable::variable-type :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Statements::AliasVariable :Express_metamodel::Algorithms::NamedVariable::variable-type :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Statements::ControlStatement )
( defstruct Express_metamodel::Statements::VARCell :Express_metamodel::Statements::VARCell::refers-to :id )
( defstruct Express_metamodel::Statements::NullStatement )
( defstruct Express_metamodel::Statements::VARExpression )
( defstruct Express_metamodel::Statements::AttributeCell :Express_metamodel::Statements::AttributeCell::refers-to :Express_metamodel::Statements::AttributeCell::base-entity :id )
( defstruct Express_metamodel::Statements::StatementBlock :delimited )
( defstruct Express_metamodel::Statements::CaseAction :isDefault )
( defstruct Express_metamodel::Statements::MemberCell :Express_metamodel::Statements::MemberCell::index-value :Express_metamodel::Statements::MemberCell::base-aggregate )
( defstruct Express_metamodel::Statements::RepeatStatement :Express_metamodel::Statements::RepeatStatement::body )
( defstruct Express_metamodel::Statements::GroupCell :Express_metamodel::Statements::GroupCell::base-entity :Express_metamodel::Statements::GroupCell::refers-to :id )
( defstruct Express_metamodel::Statements::VariableCell :Express_metamodel::Statements::VariableCell::refers-to :id )
( defstruct Express_metamodel::Statements::CaseStatement :Express_metamodel::Statements::CaseStatement::cases :Express_metamodel::Statements::CaseStatement::selection-expression )
( defstruct Express_metamodel::Statements::IfStatement :Express_metamodel::Statements::IfStatement::if-condition :Express_metamodel::Statements::IfStatement::then-actions )
( defstruct Express_metamodel::Statements::EscapeStatement :Express_metamodel::Statements::EscapeStatement::in-block )
( defstruct Express_metamodel::Statements::ReturnStatement )
( defstruct Express_metamodel::Statements::Assignment :Express_metamodel::Statements::Assignment::assigned-value :Express_metamodel::Statements::Assignment::variable )
( defstruct Express_metamodel::Expressions::Selector :Express_metamodel::Expressions::Selector::entity-instance )
( defstruct Express_metamodel::Expressions::RepeatCount )
( defstruct Express_metamodel::Expressions::EnumItemRef :Express_metamodel::Expressions::EnumItemRef::refers-to :id )
( defstruct Express_metamodel::Expressions::Literal :Express_metamodel::Expressions::Literal::refers-to )
( defstruct Express_metamodel::Expressions::BinaryIndex :Express_metamodel::Expressions::BinaryIndex::first-bit :Express_metamodel::Expressions::IndexOperation::base-value )
( defstruct Express_metamodel::Expressions::IndeterminateRef :Express_metamodel::Expressions::IndeterminateRef::refers-to )
( defstruct Express_metamodel::Expressions::SELFRef )
( defstruct Express_metamodel::Expressions::IndexOperation :Express_metamodel::Expressions::IndexOperation::base-value )
( defstruct Express_metamodel::Expressions::BinaryOperation :Express_metamodel::Expressions::BinaryOperation::left-operand :Express_metamodel::Expressions::BinaryOperation::right-operand :operator )
( defstruct Express_metamodel::Expressions::AggregateInitializer )
( defstruct Express_metamodel::Expressions::StringIndex :Express_metamodel::Expressions::StringIndex::first-code :Express_metamodel::Expressions::IndexOperation::base-value )
( defstruct Express_metamodel::Expressions::PartialEntityConstructor :Express_metamodel::Expressions::PartialEntityConstructor::attribute-group :id )
( defstruct Express_metamodel::Expressions::Coercion :Express_metamodel::Expressions::Coercion::operand :Express_metamodel::Expressions::Coercion::target-type )
( defstruct Express_metamodel::Expressions::Primary )
( defstruct Express_metamodel::Expressions::ActualParameter :Express_metamodel::Expressions::ActualParameter::formal-parameter :position )
( defstruct Express_metamodel::Expressions::ParameterRef :Express_metamodel::Expressions::ParameterRef::refers-to :id )
( defstruct Express_metamodel::Expressions::AttributeRef :Express_metamodel::Expressions::AttributeRef::refers-to :id :Express_metamodel::Expressions::Selector::entity-instance )
( defstruct Express_metamodel::Expressions::AggregateIndex :Express_metamodel::Expressions::AggregateIndex::index-value :Express_metamodel::Expressions::IndexOperation::base-value )
( defstruct Express_metamodel::Expressions::GroupRef :Express_metamodel::Expressions::GroupRef::refers-to :id :Express_metamodel::Expressions::Selector::entity-instance )
( defstruct Express_metamodel::Expressions::UnaryOperation :Express_metamodel::Expressions::UnaryOperation::unary-operand :operator )
( defstruct Express_metamodel::Expressions::UsedInRef :Express_metamodel::Expressions::UsedInRef::inverse-of :Express_metamodel::Expressions::Selector::entity-instance )
( defstruct Express_metamodel::Expressions::ConstantRef :Express_metamodel::Expressions::ConstantRef::refers-to :id )
( defstruct Express_metamodel::Expressions::QueryExpression :Express_metamodel::Expressions::QueryExpression::select-condition :Express_metamodel::Expressions::QueryExpression::query-variable :Express_metamodel::Expressions::QueryExpression::aggregate-operand )
( defstruct Express_metamodel::Expressions::QueryVariable :Express_metamodel::Expressions::QueryVariable::namespace :Express_metamodel::Algorithms::NamedVariable::variable-type :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Expressions::Operation )
( defstruct Express_metamodel::Expressions::AttributeBinding :Express_metamodel::Expressions::AttributeBinding::attribute-value :Express_metamodel::Expressions::AttributeBinding::attribute :position )
( defstruct Express_metamodel::Expressions::FunctionCall :Express_metamodel::Expressions::FunctionCall::invokes-function :Express_metamodel::Expressions::FunctionCall::/returns-result )
( defstruct Express_metamodel::Expressions::MemberBinding :Express_metamodel::Expressions::MemberBinding::member-value :position )
( defstruct Express_metamodel::Expressions::ExtentRef :Express_metamodel::Expressions::ExtentRef::refers-to :id )
( defstruct Express_metamodel::Expressions::VariableRef :Express_metamodel::Expressions::VariableRef::refers-to :id )
( defstruct Express_metamodel::Core::TypeElement :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::SingleEntityType :Express_metamodel::Core::SingleEntityType::declared-in :Express_metamodel::Core::SingleEntityType::equivalent :id )
( defstruct Express_metamodel::Core::AGGREGATEType :Express_metamodel::Core::AGGREGATEType::member-type :Express_metamodel::Core::GeneralizedType::occurs-in )
( defstruct Express_metamodel::Core::GeneralBAGType :Express_metamodel::Core::GeneralAggregationType::member-type :Express_metamodel::Core::GeneralizedType::occurs-in :isUnique :ordering )
( defstruct Express_metamodel::Core::DomainRule :Express_metamodel::Core::DomainRule::domain :position :Express_metamodel::Core::DomainConstraint::domain :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::GeneralAggregationType :Express_metamodel::Core::GeneralAggregationType::member-type :Express_metamodel::Core::GeneralizedType::occurs-in :isUnique :ordering )
( defstruct Express_metamodel::Core::ConcreteType :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::Expression )
( defstruct Express_metamodel::Core::InverseAttribute :Express_metamodel::Core::InverseAttribute::models-role :Express_metamodel::Core::InverseAttribute::explicit :isUnique :Express_metamodel::Core::Attribute::attribute-type :Express_metamodel::Core::Attribute::of-entity :isAbstract :position :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::EnumerationType :Express_metamodel::Core::EnumerationType::base :isExtensible :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::NamedElement::namespace :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::VariableType )
( defstruct Express_metamodel::Core::ArrayBound :Express_metamodel::Core::ArrayBound::bound-expression )
( defstruct Express_metamodel::Core::GeneralSETType :Express_metamodel::Core::GeneralAggregationType::member-type :Express_metamodel::Core::GeneralizedType::occurs-in :isUnique :ordering )
( defstruct Express_metamodel::Core::LISTType :Express_metamodel::Core::ConcreteAggregationType::member-type :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type :isUnique :ordering )
( defstruct Express_metamodel::Core::Redeclaration :Express_metamodel::Core::Redeclaration::restricted-type :Express_metamodel::Core::Redeclaration::scope :Express_metamodel::Core::Redeclaration::original-attribute :position )
( defstruct Express_metamodel::Core::EntityType :Express_metamodel::Core::EntityType::declares :isAbstract :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::NamedElement::namespace :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::DataType )
( defstruct Express_metamodel::Core::PartialEntityType :Express_metamodel::Core::PartialEntityType::components )
( defstruct Express_metamodel::Core::Schema :name )
( defstruct Express_metamodel::Core::InvertibleAttribute :Express_metamodel::Core::InvertibleAttribute::range-type :Express_metamodel::Core::InvertibleAttribute::creates-relationship :Express_metamodel::Core::InvertibleAttribute::referencing-type :Express_metamodel::Core::InvertibleAttribute::models-role :Express_metamodel::Core::ExplicitAttribute::of-entity :isOptional :Express_metamodel::Core::Attribute::attribute-type :Express_metamodel::Core::Attribute::of-entity :isAbstract :position :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::GeneralizedType :Express_metamodel::Core::GeneralizedType::occurs-in )
( defstruct Express_metamodel::Core::InterfacedElement :Express_metamodel::Core::InterfacedElement::interfacing-schema :Express_metamodel::Core::InterfacedElement::refers-to :isUSE )
( defstruct Express_metamodel::Core::NumericType :id :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::DefinedType :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::NamedElement::namespace :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::UniqueRule :Express_metamodel::Core::UniqueRule::domain :Express_metamodel::Core::UniqueRule::key-component :position :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::DomainRole :Express_metamodel::Core::DomainRole::domain :Express_metamodel::Core::DomainRole::in-relationship :Express_metamodel::Core::Role::in-relationship :Express_metamodel::Core::Role::of-entity )
( defstruct Express_metamodel::Core::DomainConstraint :Express_metamodel::Core::DomainConstraint::domain )
( defstruct Express_metamodel::Core::InstantiableType :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::GeneralLISTType :Express_metamodel::Core::GeneralAggregationType::member-type :Express_metamodel::Core::GeneralizedType::occurs-in :isUnique :ordering )
( defstruct Express_metamodel::Core::NamedElement :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::Attribute :Express_metamodel::Core::Attribute::attribute-type :Express_metamodel::Core::Attribute::of-entity :isAbstract :position :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::BAGType :Express_metamodel::Core::ConcreteAggregationType::member-type :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type :isUnique :ordering )
( defstruct Express_metamodel::Core::RealType :id :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::LogicType :id :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::GenericType :isEntity :Express_metamodel::Core::GeneralizedType::occurs-in )
( defstruct Express_metamodel::Core::StringType :id :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::AnonymousType :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::AlgorithmScope )
( defstruct Express_metamodel::Core::Instance :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Core::AttributeType )
( defstruct Express_metamodel::Core::DerivedAttribute :Express_metamodel::Core::DerivedAttribute::derivation :Express_metamodel::Core::Attribute::attribute-type :Express_metamodel::Core::Attribute::of-entity :isAbstract :position :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::RangeRole :Express_metamodel::Core::RangeRole::domain-view :Express_metamodel::Core::RangeRole::in-relationship :Express_metamodel::Core::RangeRole::range :id :Express_metamodel::Core::Role::in-relationship :Express_metamodel::Core::Role::of-entity )
( defstruct Express_metamodel::Core::LocalElement :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::Remark :Express_metamodel::Core::Remark::appears-in :isTagged :isTail :text )
( defstruct Express_metamodel::Core::SizeConstraint :Express_metamodel::Core::DomainConstraint::domain )
( defstruct Express_metamodel::Core::Role :Express_metamodel::Core::Role::in-relationship :Express_metamodel::Core::Role::of-entity )
( defstruct Express_metamodel::Core::SETType :Express_metamodel::Core::ConcreteAggregationType::member-type :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type :isUnique :ordering )
( defstruct Express_metamodel::Core::SpecializedType :Express_metamodel::Core::SpecializedType::underlying-type :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::NamedElement::namespace :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::GeneralARRAYType :isOptional :Express_metamodel::Core::GeneralAggregationType::member-type :Express_metamodel::Core::GeneralizedType::occurs-in :isUnique :ordering )
( defstruct Express_metamodel::Core::Relationship :Express_metamodel::Core::Relationship::domain :Express_metamodel::Core::Relationship::roles :Express_metamodel::Core::Relationship::based-on :Express_metamodel::Core::Relationship::range )
( defstruct Express_metamodel::Core::LengthConstraint :isFixed :Express_metamodel::Core::DomainConstraint::domain )
( defstruct Express_metamodel::Core::LocalScope )
( defstruct Express_metamodel::Core::NamedType :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::BinaryType :id :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::ScopedId :localName :definingScope )
( defstruct Express_metamodel::Core::AggregationType :isUnique :ordering )
( defstruct Express_metamodel::Core::Scope )
( defstruct Express_metamodel::Core::ParameterType )
( defstruct Express_metamodel::Core::SelectType :Express_metamodel::Core::SelectType::base :isExtensible :isEntity :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::NamedElement::namespace :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::ActualType :Express_metamodel::Core::ActualType::scope )
( defstruct Express_metamodel::Core::ExplicitAttribute :Express_metamodel::Core::ExplicitAttribute::of-entity :isOptional :Express_metamodel::Core::Attribute::attribute-type :Express_metamodel::Core::Attribute::of-entity :isAbstract :position :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::SimpleType :id :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type )
( defstruct Express_metamodel::Core::CommonElement :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::SchemaElement :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Core::ConcreteAggregationType :Express_metamodel::Core::ConcreteAggregationType::member-type :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type :isUnique :ordering )
( defstruct Express_metamodel::Core::ARRAYType :Express_metamodel::Core::ARRAYType::lo-index :Express_metamodel::Core::ARRAYType::hi-index :isOptional :Express_metamodel::Core::ConcreteAggregationType::member-type :Express_metamodel::Core::InstantiableType::fundamental-type :Express_metamodel::Core::InstantiableType::fundamental-type :isUnique :ordering )
( defstruct Express_metamodel::Algorithms::ActualTypeConstraint :Express_metamodel::Algorithms::ActualTypeConstraint::matching-type :Express_metamodel::Algorithms::ActualTypeConstraint::required-type :label )
( defstruct Express_metamodel::Algorithms::FunctionResult :Express_metamodel::Algorithms::FunctionResult::namespace :Express_metamodel::Algorithms::Variable::namespace :Express_metamodel::Algorithms::NamedVariable::variable-type :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::Function :Express_metamodel::Algorithms::Function::result :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::InParameter :Express_metamodel::Algorithms::InParameter::variable :Express_metamodel::Algorithms::Parameter::namespace :Express_metamodel::Algorithms::Parameter::formal-parameter-type :inout :position :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::LocalVariable :Express_metamodel::Algorithms::Variable::namespace :Express_metamodel::Algorithms::NamedVariable::variable-type :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::ActualStructure :Express_metamodel::Algorithms::GenericElement::occurs-in :Express_metamodel::Algorithms::GenericElement::source :Express_metamodel::Algorithms::GenericElement::namespace :label :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace :Express_metamodel::Core::AGGREGATEType::member-type :Express_metamodel::Core::GeneralizedType::occurs-in )
( defstruct Express_metamodel::Algorithms::ActualGenericType :Express_metamodel::Algorithms::ActualGenericType::refers-to :isEntity :label :Express_metamodel::Core::ActualType::scope )
( defstruct Express_metamodel::Algorithms::Statement )
( defstruct Express_metamodel::Algorithms::NamedVariable :Express_metamodel::Algorithms::NamedVariable::variable-type :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::InVariable :Express_metamodel::Algorithms::InVariable::source :Express_metamodel::Algorithms::Variable::namespace :Express_metamodel::Algorithms::NamedVariable::variable-type :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::Procedure :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::ActualARRAYType :Express_metamodel::Algorithms::ActualARRAYType::hi-index :Express_metamodel::Algorithms::ActualARRAYType::lo-index :isOptional :Express_metamodel::Algorithms::ActualAggregationType::member-type :Express_metamodel::Core::ActualType::scope :isUnique :ordering )
( defstruct Express_metamodel::Algorithms::ActualSETType :Express_metamodel::Algorithms::ActualAggregationType::member-type :Express_metamodel::Core::ActualType::scope :isUnique :ordering )
( defstruct Express_metamodel::Algorithms::ActualAGGREGATEType :Express_metamodel::Algorithms::ActualAGGREGATEType::refers-to :Express_metamodel::Algorithms::ActualAGGREGATEType::member-type :label :Express_metamodel::Core::ActualType::scope )
( defstruct Express_metamodel::Algorithms::Parameter :Express_metamodel::Algorithms::Parameter::namespace :Express_metamodel::Algorithms::Parameter::formal-parameter-type :inout :position :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::ActualStructureConstraint :Express_metamodel::Algorithms::ActualStructureConstraint::matching-structure :Express_metamodel::Algorithms::ActualStructureConstraint::required-structure :label )
( defstruct Express_metamodel::Algorithms::Algorithm :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::ActualAggregationType :Express_metamodel::Algorithms::ActualAggregationType::member-type :Express_metamodel::Core::ActualType::scope :isUnique :ordering )
( defstruct Express_metamodel::Algorithms::VARVariable )
( defstruct Express_metamodel::Algorithms::ActualLISTType :Express_metamodel::Algorithms::ActualAggregationType::member-type :Express_metamodel::Core::ActualType::scope :isUnique :ordering )
( defstruct Express_metamodel::Algorithms::Variable :Express_metamodel::Algorithms::Variable::namespace :Express_metamodel::Algorithms::NamedVariable::variable-type :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::GenericElement :Express_metamodel::Algorithms::GenericElement::occurs-in :Express_metamodel::Algorithms::GenericElement::source :Express_metamodel::Algorithms::GenericElement::namespace :label :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::VARParameter :Express_metamodel::Algorithms::Parameter::namespace :Express_metamodel::Algorithms::Parameter::formal-parameter-type :inout :position :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::ActualDataType :isEntity :Express_metamodel::Core::GeneralizedType::occurs-in :Express_metamodel::Algorithms::GenericElement::occurs-in :Express_metamodel::Algorithms::GenericElement::source :Express_metamodel::Algorithms::GenericElement::namespace :label :Express_metamodel::Core::LocalElement::namespace :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Algorithms::ActualBAGType :Express_metamodel::Algorithms::ActualAggregationType::member-type :Express_metamodel::Core::ActualType::scope :isUnique :ordering )
( defstruct Express_metamodel::Instances::AttributeValue :Express_metamodel::Instances::AttributeValue::attribute )
( defstruct Express_metamodel::Instances::ARRAYValue :Express_metamodel::Instances::ARRAYValue::of-type :Express_metamodel::Instances::ARRAYValue::member-slot :Express_metamodel::Instances::AggregateValue::of-type :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::RoleName :Express_metamodel::Instances::RoleName::refers-to :represents :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::EntityInstance :Express_metamodel::Instances::EntityInstance::state :Express_metamodel::Instances::EntityInstance::instance-of :Express_metamodel::Instances::EntityInstance::appears-in-population :id :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::IntegerValue :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::AggregateValue :Express_metamodel::Instances::AggregateValue::of-type :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::Constant :Express_metamodel::Instances::Constant::value-expression :Express_metamodel::Instances::Constant::data-type :Express_metamodel::Core::NamedElement::namespace )
( defstruct Express_metamodel::Instances::LogicalValue :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::TypedInstance :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::ListMember :Express_metamodel::Instances::ListMember::member-value :position )
( defstruct Express_metamodel::Instances::BagMember :Express_metamodel::Instances::BagMember::member-value :count )
( defstruct Express_metamodel::Instances::SingleEntityValue :Express_metamodel::Instances::SingleEntityValue::equivalent :Express_metamodel::Instances::SingleEntityValue::of-type )
( defstruct Express_metamodel::Instances::Indeterminate :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::SingleLeafInstance :Express_metamodel::Instances::SingleLeafInstance::characterizing-type :Express_metamodel::Instances::EntityInstance::state :Express_metamodel::Instances::EntityInstance::instance-of :Express_metamodel::Instances::EntityInstance::appears-in-population :id :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::GenericAggregate :Express_metamodel::Instances::LISTValue::of-type :Express_metamodel::Core::Instance::of-type :Express_metamodel::Instances::AggregateValue::of-type :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::BinaryValue :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::SpecializedValue :Express_metamodel::Instances::SpecializedValue::of-type :Express_metamodel::Instances::SpecializedValue::fundamental-value :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::BAGValue :Express_metamodel::Instances::BAGValue::of-type :Express_metamodel::Instances::AggregateValue::of-type :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::EnumerationItem :Express_metamodel::Instances::EnumerationItem::of-type :Express_metamodel::Instances::EnumerationItem::declared-in :position :Express_metamodel::Core::TypeElement::namespace :Express_metamodel::Core::NamedElement::namespace :Express_metamodel::Core::Instance::of-type :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::EntityValue :Express_metamodel::Instances::EntityValue::corresponds to :Express_metamodel::Instances::PartialEntityValue::of-type :Express_metamodel::Instances::PartialEntityValue::components :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::SETValue :Express_metamodel::Instances::SETValue::of-type :Express_metamodel::Instances::AggregateValue::of-type :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::ArrayMember :index )
( defstruct Express_metamodel::Instances::Population )
( defstruct Express_metamodel::Instances::RealValue :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::BooleanValue :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::LISTValue :Express_metamodel::Instances::LISTValue::of-type :Express_metamodel::Core::Instance::of-type :Express_metamodel::Instances::AggregateValue::of-type :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::StringValue :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::TypeName :Express_metamodel::Instances::TypeName::refers-to :represents :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::PartialEntityValue :Express_metamodel::Instances::PartialEntityValue::of-type :Express_metamodel::Instances::PartialEntityValue::components :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::NumberValue :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::MultiLeafInstance :Express_metamodel::Instances::EntityInstance::state :Express_metamodel::Instances::EntityInstance::instance-of :Express_metamodel::Instances::EntityInstance::appears-in-population :id :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::SimpleValue :Express_metamodel::Instances::SimpleValue::of-type :name :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::Instances::ConcreteValue :Express_metamodel::Core::Instance::of-type )
( defstruct Express_metamodel::java::lang::void )
( defstruct Express_metamodel::java::lang::int )
