( defstruct ModelElement :name )
( defstruct Name )
( defstruct AssociationEnd :isNavigable :isOrdered :aggregation :multiplicity :changeable :TargetScope :rfIntegrety :rlIntegrety :name )
( defstruct AggregationKind )
( defstruct Multiplicity )
( defstruct ChangeableKind )
( defstruct ScopeKind )
( defstruct RfIntegretyKind )
( defstruct RlIntegretyKind )
( defstruct Namespace :name )
( defstruct GeneralizableElement :name )
( defstruct Classifier :name )
( defstruct Class :isActive :mutliplicity :name )
( defstruct Key :classOwner :name )
( defstruct Feature :name )
( defstruct StructureFeature :name )
( defstruct Constraint :name )
( defstruct Attribute :initialValue :isKey :isUnique :name )
( defstruct Expression )
