( defstruct Project :name :company :viewDate :viewIndex :ganttDividerLocation :ressourceDividerLocation :webLink :tasks )
( defstruct Tasks :color )
( defstruct Task :id :name :meeting :color :expand :complete :duration :priority :start )
( defstruct Depend :id :type :difference :hardness :task )
( defstruct Ressource :Id :name :fonction :contact :phone )
( defstruct Date :year :month :day )
( defstruct Allocation :taskId :ressourceId :name :function :responsible :load )
( defstruct Vacation )
( defstruct Description )
( defstruct Previous )
