( defstruct LocatedElement :location )
( defstruct Editor :extension :location )
( defstruct AbstractElement :type :location )
( defstruct Block :blockbegin :blockend :type :location )
( defstruct GroupElement :type :location )
( defstruct Element :element :groupElement :location )
( defstruct Format :location )
( defstruct Color :red :green :blue :location )
( defstruct Font :font :bold :italic :location )
( defstruct Indent :retrait :groupElementIndent :location )
