( defstruct LocatedElement )
( defstruct Root )
( defstruct Element :id )
( defstruct Key :for :attrName :type :defValue :id )
( defstruct Graph :edgeDefault :id )
( defstruct Edge :source :target :sourceport :targetport :id )
( defstruct HyperEdge :id )
( defstruct Node :subgraph :id )
( defstruct Port :name )
( defstruct EndPoint :node :port )
( defstruct Data :key :value )
