( defstruct LocatedElement :location )
( defstruct Named :name :location )
( defstruct GUI :name :location )
( defstruct Tab :title :gui :group :name :location )
( defstruct Composant :composantGroup :name :location )
( defstruct Group :title :layout :description :composantGroup :name :location )
( defstruct Label :text :composantGroup :name :location )
( defstruct TextArea :text :nbRows :composantGroup :name :location )
( defstruct Table :composantGroup :name :location )
( defstruct Column :title :columnTab :location )
( defstruct ComboBox :composantGroup :name :location )
( defstruct Row :rowList :text :composantGroup :name :location )
( defstruct Item :itemList :text :composantGroup :name :location )
( defstruct Button :title :composantGroup :name :location )
