( defstruct HAL :connexion )
( defstruct Connexion :login :password )
( defstruct Entry :autLab )
( defstruct Article :metaArt :autLab )
( defstruct ArticleRecent :fichiers :metaArt :autLab )
( defstruct ArticleRetro :dateRedaction :fichiers :metaArt :autLab )
( defstruct Notice :metaArtNotice :autLab )
( defstruct ReferenceBiblioType )
( defstruct ArtRevueType :journal :volume :page :annee )
( defstruct WorkshopType :titconf :pays :annee )
( defstruct ArtOuvrageType :titouv :annee )
( defstruct OuvrageType :annee :page )
( defstruct TheseType :orgthe :niveau :defencedate :directeur )
( defstruct BrevetType :datebrevet :numbrevet :page :pays )
( defstruct AutreType :description )
( defstruct ArtRevue :journal :volume :page :annee )
( defstruct ArtJournal :journal :volume :page :annee )
( defstruct Workshop :titconf :pays :annee )
( defstruct Communication :titconf :pays :annee )
( defstruct Conference :titconf :pays :annee )
( defstruct ArtOuvrage :titouv :annee )
( defstruct Ouvrage :annee :page )
( defstruct Brevet :datebrevet :numbrevet :page :pays )
( defstruct Autre :description )
( defstruct These :orgthe :niveau :defencedate :directeur )
( defstruct MetaType :langue :title )
( defstruct MetaArtType :domain :abstract :langue :title )
( defstruct MetaArtNoticeType :referenceBiblio :langue :title )
( defstruct AutLabType :auteurs :laboratoires )
( defstruct Auteur :nom :prenom )
( defstruct Laboratoire :id :metas )
( defstruct AbstractMetaLab )
( defstruct MetaLab :id )
( defstruct AffiliationType )
( defstruct TamponType :id )
( defstruct AbstractDepot :nom )
( defstruct Depot :format :nom )
( defstruct DepotWeb :format :nom )
( defstruct AbstractDepotType )
( defstruct DepotsType :depots )
( defstruct WebLink :identifiant :server )
( defstruct Server )
