( defstruct MgaObject )
( defstruct StateBase :defaultTransition :marked :associationStateStatedst :associationStateStatesrc :associationDataStateBase )
( defstruct DataVar :orState :associationDataStateBase )
( defstruct Transition :guard :trigger :action :isSync :orState :associationStateState )
( defstruct StateDateRelation :value :color )
( defstruct RootFolder )
( defstruct OrState :rootFolder :init :andState :orState :defaultTransition :marked :associationStateStatedst :associationStateStatesrc :associationDataStateBase )
( defstruct AndState :andState :orState :defaultTransition :marked :associationStateStatedst :associationStateStatesrc :associationDataStateBase )
( defstruct CompoundState :andState :orState :defaultTransition :marked :associationStateStatedst :associationStateStatesrc :associationDataStateBase )
( defstruct PrimitiveState :defaultTransition :marked :associationStateStatedst :associationStateStatesrc :associationDataStateBase )
( defstruct Init :orState :defaultTransition :marked :associationStateStatedst :associationStateStatesrc :associationDataStateBase )
( defstruct State :orState :defaultTransition :marked :associationStateStatedst :associationStateStatesrc :associationDataStateBase )
( defstruct StateDataRelation :value :color :orState :associationDataStateBase1 :defaultTransition :marked :associationStateStatedst :associationStateStatesrc :associationDataStateBase )
( defstruct AssociationStateState :transition :dstTransition :srcTransition )
( defstruct AssociationDataStateBase :stateDataRelation :dataVar :stateBase )
