( defstruct LocatedElement )
( defstruct Profile :header :times )
( defstruct Method :fullyQualifiedName )
( defstruct ThreadAction :id )
( defstruct ThreadStart :obj :name :group :id )
( defstruct ThreadEnd :id )
( defstruct Trace :id :threadId )
( defstruct StackTraceElement :method :line :trace )
( defstruct Times :unit :total :date )
( defstruct Time :rank :self :accum :count :trace :method )
( defstruct Date :day :month :dayOfMonth :hour :minutes :seconds :year )
