( defstruct HTML :head :body )
( defstruct HTMLElement :value :parent )
( defstruct HEAD :html :value :parent )
( defstruct HEADElement :head :value :parent )
( defstruct LINK :rel :title :ahref :type :head :value :parent )
( defstruct TITLE :head :value :parent )
( defstruct BODY :background :bgcolor :text :link :alink :vlink :html :value :parent )
( defstruct BODYElement :body :value :parent )
( defstruct H1 :body :value :parent )
( defstruct H2 :body :value :parent )
( defstruct H3 :body :value :parent )
( defstruct H4 :body :value :parent )
( defstruct EM :body :value :parent )
( defstruct STRONG :body :value :parent )
( defstruct B :body :value :parent )
( defstruct I :body :value :parent )
( defstruct TT :body :value :parent )
( defstruct PRE :body :value :parent )
( defstruct BIG :body :value :parent )
( defstruct SMALL :body :value :parent )
( defstruct SUB :body :value :parent )
( defstruct SUP :body :value :parent )
( defstruct STRIKE :body :value :parent )
( defstruct FONT :color :face :size :body :value :parent )
( defstruct IMG :src :width :height :alt :align :vspace :hspace :ismap :usemap :border :body :value :parent )
( defstruct BR :clear :body :value :parent )
( defstruct MAP :body :value :parent )
( defstruct AREA :shape :coords :ahref :body :value :parent )
( defstruct STYLE :body :value :parent )
( defstruct EMBED :src :width :height :align :vspace :hspace :border :body :value :parent )
( defstruct NOEMBED :body :value :parent )
( defstruct SPAN :style :body :value :parent )
( defstruct A :ahref :name :id :body :value :parent )
( defstruct DIV :align :body :value :parent )
( defstruct P :body :value :parent )
( defstruct TABLEElement :bgcolor :background :body :value :parent )
( defstruct TABLE :border :width :cellspacing :cellpadding :bgcolor :background :body :value :parent )
( defstruct TR :valign :align :table :bgcolor :background :body :value :parent )
( defstruct TD :colspan :rowspan :valign :align :width :tr :bgcolor :background :body :value :parent )
( defstruct TH :colspan :rowspan :valign :align :width :tr :bgcolor :background :body :value :parent )
( defstruct FORM :action :method )
( defstruct INPUT :align :maxlength :size :checked :src :inputValue :name :type )
( defstruct TEXTAREA :name :rows :cols )
( defstruct SELECT :multiple :size :name )
( defstruct OPTION :selected :optionValue )
( defstruct ListElement :type )
( defstruct OL :start :type )
( defstruct UL :type )
( defstruct LI :liValue :type )
( defstruct DL )
( defstruct DT )
( defstruct DD )
( defstruct APPLET :applet :class :src :align :width :height )
( defstruct PARAM :name :paramValue )
( defstruct OBJECT :classid :id :data :type :standby )
( defstruct FRAMESET :rows :cols :framespacing :frameborder :border )
( defstruct FRAME :src :name :marginwidth :marginheight :scrolling :noresize )
( defstruct NOFRAME )
( defstruct IFRAME :src :name :marginwidth :marginheight :scrolling :noresize )
