( defstruct Viewpoint :source :covers :process )
( defstruct Concern )
( defstruct Stakeholder )
( defstruct ViewpointImport )
( defstruct ViewpointDependency :supplier :client )
( defstruct Process :methodology )
( defstruct Technique :applies )
( defstruct AnalysisMethod :analysis )
( defstruct ArchitecturalConstruct )
( defstruct Rule :techniques :guidance )
( defstruct ModelOrganization :techniques :guidance )
( defstruct ModellingRule )
( defstruct Language )
( defstruct Mapping :input :ouput )
( defstruct Pattern )
