( defstruct IfcActorSelect )
( defstruct IfcAxis2Placement )
( defstruct IfcBooleanOperand )
( defstruct IfcCharacterStyleSelect )
( defstruct IfcClassificationNotationSelect )
( defstruct IfcColour )
( defstruct IfcCsgSelect )
( defstruct IfcCurveFontOrScaledCurveFontSelect )
( defstruct IfcCurveOrEdgeCurve )
( defstruct IfcCurveStyleFontSelect )
( defstruct IfcDateTimeSelect )
( defstruct IfcDefinedSymbolSelect )
( defstruct IfcDocumentSelect )
( defstruct IfcDraughtingCalloutElement )
( defstruct IfcFillAreaStyleTileShapeSelect )
( defstruct IfcFillStyleSelect )
( defstruct IfcGeometricSetSelect )
( defstruct IfcLayeredItem :LayerAssignments )
( defstruct IfcLibrarySelect )
( defstruct IfcLightDistributionDataSourceSelect )
( defstruct IfcMaterialSelect )
( defstruct IfcObjectReferenceSelect )
( defstruct IfcPointOrVertexPoint )
( defstruct IfcShell )
( defstruct IfcStructuralActivityAssignmentSelect :AssignedStructuralActivity )
( defstruct IfcSurfaceOrFaceSurface )
( defstruct IfcSurfaceStyleElementSelect )
( defstruct IfcSymbolStyleSelect )
( defstruct IfcTextFontSelect )
( defstruct IfcTextStyleSelect )
( defstruct IfcUnit )
( defstruct IfcVectorOrDirection )
( defstruct IfcValue )
( defstruct IfcTrimmingSelect )
( defstruct IfcSpecularHighlightSelect )
( defstruct IfcSizeSelect )
( defstruct IfcSimpleValue )
( defstruct IfcPresentationStyleSelect )
( defstruct IfcOrientationSelect )
( defstruct IfcMetricValueSelect )
( defstruct IfcMeasureValue )
( defstruct IfcHatchLineDistanceSelect )
( defstruct IfcDerivedMeasureValue )
( defstruct IfcConditionCriterionSelect )
( defstruct IfcColourOrFactor )
( defstruct IfcAppliedValueSelect )
( defstruct Ifc2DCompositeCurve :Segments :SelfIntersect :StyledByItem :LayerAssignments )
( defstruct IfcActionRequest :RequestID :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcActor :IsActingUpon :TheActor :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcActorRole :Role )
( defstruct IfcActuatorType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcAddress :OfPerson :OfOrganization )
( defstruct IfcAirTerminalBoxType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcAirTerminalType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcAirToAirHeatRecoveryType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcAlarmType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcAngularDimension :IsRelatedFromCallout :IsRelatedToCallout :Contents :StyledByItem :LayerAssignments )
( defstruct IfcAnnotation :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcAnnotationCurveOccurrence :AnnotatedBySymbols :Styles :StyledByItem :LayerAssignments )
( defstruct IfcAnnotationFillArea :OuterBoundary :StyledByItem :LayerAssignments )
( defstruct IfcAnnotationFillAreaOccurrence :Styles :StyledByItem :LayerAssignments )
( defstruct IfcAnnotationOccurrence :Styles :StyledByItem :LayerAssignments )
( defstruct IfcAnnotationSurface :Item :StyledByItem :LayerAssignments )
( defstruct IfcAnnotationSurfaceOccurrence :Styles :StyledByItem :LayerAssignments )
( defstruct IfcAnnotationSymbolOccurrence :Styles :StyledByItem :LayerAssignments )
( defstruct IfcAnnotationTextOccurrence :Styles :StyledByItem :LayerAssignments )
( defstruct IfcApplication :Version :ApplicationFullName :ApplicationIdentifier :ApplicationDeveloper )
( defstruct IfcAppliedValue :ValuesReferenced :ValueOfComponents :IsComponentIn )
( defstruct IfcAppliedValueRelationship :ArithmeticOperator :ComponentOfTotal :Components )
( defstruct IfcApproval :Name :Identifier :Actors :IsRelatedWith :Relates :ApprovalDateTime )
( defstruct IfcApprovalActorRelationship :Actor :Approval :Role )
( defstruct IfcApprovalPropertyRelationship :ApprovedProperties :Approval )
( defstruct IfcApprovalRelationship :Name :RelatedApproval :RelatingApproval )
( defstruct IfcArbitraryClosedProfileDef :OuterCurve :ProfileType )
( defstruct IfcArbitraryOpenProfileDef :Curve :ProfileType )
( defstruct IfcArbitraryProfileDefWithVoids :InnerCurves :OuterCurve :ProfileType )
( defstruct IfcAsset :OriginalValue :CurrentValue :TotalReplacementCost :Owner :User :ResponsiblePerson :IncorporationDate :DepreciatedValue :AssetID :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcAsymmetricIShapeProfileDef :TopFlangeWidth :OverallWidth :OverallDepth :WebThickness :FlangeThickness :Position :ProfileType )
( defstruct IfcAxis1Placement :Location :StyledByItem :LayerAssignments )
( defstruct IfcAxis2Placement2D :Location :StyledByItem :LayerAssignments )
( defstruct IfcAxis2Placement3D :Location :StyledByItem :LayerAssignments )
( defstruct IfcBSplineCurve :Degree :CurveForm :ClosedCurve :SelfIntersect :ControlPointsList :StyledByItem :LayerAssignments )
( defstruct IfcBeam :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBeamType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBezierCurve :Degree :CurveForm :ClosedCurve :SelfIntersect :ControlPointsList :StyledByItem :LayerAssignments )
( defstruct IfcBlobTexture :RasterFormat :RasterCode :RepeatS :RepeatT :TextureType )
( defstruct IfcBlock :XLength :YLength :ZLength :Position :StyledByItem :LayerAssignments )
( defstruct IfcBoilerType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBooleanClippingResult :FirstOperand :SecondOperand :Operator :StyledByItem :LayerAssignments )
( defstruct IfcBooleanResult :FirstOperand :SecondOperand :Operator :StyledByItem :LayerAssignments )
( defstruct IfcBoundaryCondition )
( defstruct IfcBoundaryEdgeCondition )
( defstruct IfcBoundaryFaceCondition )
( defstruct IfcBoundaryNodeCondition )
( defstruct IfcBoundaryNodeConditionWarping )
( defstruct IfcBoundedCurve :StyledByItem :LayerAssignments )
( defstruct IfcBoundedSurface :StyledByItem :LayerAssignments )
( defstruct IfcBoundingBox :XDim :YDim :ZDim :Corner :StyledByItem :LayerAssignments )
( defstruct IfcBoxedHalfSpace :Enclosure :BaseSurface :AgreementFlag :StyledByItem :LayerAssignments )
( defstruct IfcBuilding :CompositionType :ReferencesElements :ServicedBySystems :ContainsElements :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBuildingElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBuildingElementComponent :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBuildingElementPart :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBuildingElementProxy :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBuildingElementProxyType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBuildingElementType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcBuildingStorey :CompositionType :ReferencesElements :ServicedBySystems :ContainsElements :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCShapeProfileDef :Depth :Width :WallThickness :Girth :Position :ProfileType )
( defstruct IfcCableCarrierFittingType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCableCarrierSegmentType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCableSegmentType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCalendarDate :DayComponent :MonthComponent :YearComponent )
( defstruct IfcCartesianPoint :Coordinates :StyledByItem :LayerAssignments )
( defstruct IfcCartesianTransformationOperator :LocalOrigin :StyledByItem :LayerAssignments )
( defstruct IfcCartesianTransformationOperator2D :LocalOrigin :StyledByItem :LayerAssignments )
( defstruct IfcCartesianTransformationOperator2DnonUniform :LocalOrigin :StyledByItem :LayerAssignments )
( defstruct IfcCartesianTransformationOperator3D :LocalOrigin :StyledByItem :LayerAssignments )
( defstruct IfcCartesianTransformationOperator3DnonUniform :LocalOrigin :StyledByItem :LayerAssignments )
( defstruct IfcCenterLineProfileDef :Thickness :Curve :ProfileType )
( defstruct IfcChamferEdgeFeature :VoidsElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcChillerType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCircle :Radius :Position :StyledByItem :LayerAssignments )
( defstruct IfcCircleHollowProfileDef :WallThickness :Radius :Position :ProfileType )
( defstruct IfcCircleProfileDef :Radius :Position :ProfileType )
( defstruct IfcClassification :Source :Edition :Name :Contains )
( defstruct IfcClassificationItem :IsClassifiedItemIn :IsClassifyingItemIn :Notation :Title )
( defstruct IfcClassificationItemRelationship :RelatingItem :RelatedItems )
( defstruct IfcClassificationNotation :NotationFacets )
( defstruct IfcClassificationNotationFacet :NotationValue )
( defstruct IfcClassificationReference )
( defstruct IfcClosedShell :CfsFaces :StyledByItem :LayerAssignments )
( defstruct IfcCoilType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcColourRgb :Red :Green :Blue )
( defstruct IfcColourSpecification )
( defstruct IfcColumn :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcColumnType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcComplexProperty :HasProperties :UsageName :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcCompositeCurve :Segments :SelfIntersect :StyledByItem :LayerAssignments )
( defstruct IfcCompositeCurveSegment :Transition :SameSense :UsingCurves :ParentCurve :StyledByItem :LayerAssignments )
( defstruct IfcCompositeProfileDef :Profiles :ProfileType )
( defstruct IfcCompressorType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCondenserType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCondition :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcConditionCriterion :Criterion :CriterionDateTime :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcConic :Position :StyledByItem :LayerAssignments )
( defstruct IfcConnectedFaceSet :CfsFaces :StyledByItem :LayerAssignments )
( defstruct IfcConnectionCurveGeometry :CurveOnRelatingElement )
( defstruct IfcConnectionGeometry )
( defstruct IfcConnectionPointEccentricity :PointOnRelatingElement )
( defstruct IfcConnectionPointGeometry :PointOnRelatingElement )
( defstruct IfcConnectionPortGeometry :LocationAtRelatingElement :ProfileOfPort )
( defstruct IfcConnectionSurfaceGeometry :SurfaceOnRelatingElement )
( defstruct IfcConstraint :Name :ConstraintGrade :ClassifiedAs :RelatesConstraints :IsRelatedWith :PropertiesForConstraint :Aggregates :IsAggregatedIn )
( defstruct IfcConstraintAggregationRelationship :LogicalAggregator :RelatingConstraint :RelatedConstraints )
( defstruct IfcConstraintClassificationRelationship :ClassifiedConstraint :RelatedClassifications )
( defstruct IfcConstraintRelationship :RelatingConstraint :RelatedConstraints )
( defstruct IfcConstructionEquipmentResource :ResourceOf :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcConstructionMaterialResource :ResourceOf :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcConstructionProductResource :ResourceOf :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcConstructionResource :ResourceOf :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcContextDependentUnit :Name :Dimensions :UnitType )
( defstruct IfcControl :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcControllerType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcConversionBasedUnit :ConversionFactor :Name :Dimensions :UnitType )
( defstruct IfcCooledBeamType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCoolingTowerType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCoordinatedUniversalTimeOffset :HourOffset :Sense )
( defstruct IfcCostItem :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCostSchedule :ID :PredefinedType :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCostValue :CostType :ValuesReferenced :ValueOfComponents :IsComponentIn )
( defstruct IfcCovering :CoversSpaces :Covers :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCoveringType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCraneRailAShapeProfileDef :OverallHeight :BaseWidth2 :HeadWidth :HeadDepth2 :HeadDepth3 :WebThickness :BaseWidth4 :BaseDepth1 :BaseDepth2 :BaseDepth3 :Position :ProfileType )
( defstruct IfcCraneRailFShapeProfileDef :OverallHeight :HeadWidth :HeadDepth2 :HeadDepth3 :WebThickness :BaseDepth1 :BaseDepth2 :Position :ProfileType )
( defstruct IfcCrewResource :ResourceOf :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCsgPrimitive3D :Position :StyledByItem :LayerAssignments )
( defstruct IfcCsgSolid :TreeRootExpression :StyledByItem :LayerAssignments )
( defstruct IfcCurrencyRelationship :RelatingMonetaryUnit :RelatedMonetaryUnit :RateDateTime :ExchangeRate )
( defstruct IfcCurtainWall :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCurtainWallType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcCurve :StyledByItem :LayerAssignments )
( defstruct IfcCurveBoundedPlane :BasisSurface :OuterBoundary :StyledByItem :LayerAssignments )
( defstruct IfcCurveStyle )
( defstruct IfcCurveStyleFont :PatternList )
( defstruct IfcCurveStyleFontAndScaling :CurveFontScaling :CurveFont )
( defstruct IfcCurveStyleFontPattern :VisibleSegmentLength :InvisibleSegmentLength )
( defstruct IfcDamperType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDateAndTime :DateComponent :TimeComponent )
( defstruct IfcDefinedSymbol :Definition :Target :StyledByItem :LayerAssignments )
( defstruct IfcDerivedProfileDef :ParentProfile :Operator :ProfileType )
( defstruct IfcDerivedUnit :UnitType :Elements )
( defstruct IfcDerivedUnitElement :Unit :Exponent )
( defstruct IfcDiameterDimension :IsRelatedFromCallout :IsRelatedToCallout :Contents :StyledByItem :LayerAssignments )
( defstruct IfcDimensionCalloutRelationship :RelatingDraughtingCallout :RelatedDraughtingCallout )
( defstruct IfcDimensionCurve :AnnotatedBySymbols :Styles :StyledByItem :LayerAssignments )
( defstruct IfcDimensionCurveDirectedCallout :IsRelatedFromCallout :IsRelatedToCallout :Contents :StyledByItem :LayerAssignments )
( defstruct IfcDimensionCurveTerminator :Role :AnnotatedCurve :Styles :StyledByItem :LayerAssignments )
( defstruct IfcDimensionPair :RelatingDraughtingCallout :RelatedDraughtingCallout )
( defstruct IfcDimensionalExponents :LengthExponent :MassExponent :TimeExponent :ElectricCurrentExponent :ThermodynamicTemperatureExponent :AmountOfSubstanceExponent :LuminousIntensityExponent )
( defstruct IfcDirection :DirectionRatios :StyledByItem :LayerAssignments )
( defstruct IfcDiscreteAccessory :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDiscreteAccessoryType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionChamberElement :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionChamberElementType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionControlElement :AssignedToFlowElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionControlElementType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionElementType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionFlowElement :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionFlowElementType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDistributionPort :ContainedIn :ConnectedFrom :ConnectedTo :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDocumentElectronicFormat )
( defstruct IfcDocumentInformation :DocumentId :Name :IsPointedTo :IsPointer )
( defstruct IfcDocumentInformationRelationship :RelatingDocument :RelatedDocuments )
( defstruct IfcDocumentReference :ReferenceToDocument )
( defstruct IfcDoor :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDoorLiningProperties :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDoorPanelProperties :PanelOperation :PanelPosition :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDoorStyle :OperationType :ConstructionType :ParameterTakesPrecedence :Sizeable :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDraughtingCallout :IsRelatedFromCallout :IsRelatedToCallout :Contents :StyledByItem :LayerAssignments )
( defstruct IfcDraughtingCalloutRelationship :RelatingDraughtingCallout :RelatedDraughtingCallout )
( defstruct IfcDraughtingPreDefinedColour :Name )
( defstruct IfcDraughtingPreDefinedCurveFont :Name )
( defstruct IfcDraughtingPreDefinedTextFont :Name )
( defstruct IfcDuctFittingType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDuctSegmentType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcDuctSilencerType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcEdge :EdgeStart :EdgeEnd :StyledByItem :LayerAssignments )
( defstruct IfcEdgeCurve :EdgeGeometry :SameSense :EdgeStart :EdgeEnd :StyledByItem :LayerAssignments )
( defstruct IfcEdgeFeature :VoidsElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcEdgeLoop :EdgeList :StyledByItem :LayerAssignments )
( defstruct IfcElectricApplianceType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricDistributionPoint :DistributionPointFunction :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricFlowStorageDeviceType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricGeneratorType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricHeaterType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricMotorType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricTimeControlType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricalBaseProperties :InputVoltage :InputFrequency :InputPhase :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricalCircuit :ServicesBuildings :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElectricalElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElementAssembly :PredefinedType :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElementComponent :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElementComponentType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElementQuantity :Quantities :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElementType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcElementarySurface :Position :StyledByItem :LayerAssignments )
( defstruct IfcEllipse :SemiAxis1 :SemiAxis2 :Position :StyledByItem :LayerAssignments )
( defstruct IfcEllipseProfileDef :SemiAxis1 :SemiAxis2 :Position :ProfileType )
( defstruct IfcEnergyConversionDevice :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcEnergyConversionDeviceType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcEnergyProperties :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcEnvironmentalImpactValue :ImpactType :Category :ValuesReferenced :ValueOfComponents :IsComponentIn )
( defstruct IfcEquipmentElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcEquipmentStandard :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcEvaporativeCoolerType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcEvaporatorType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcExtendedMaterialProperties :Name :ExtendedProperties :Material )
( defstruct IfcExternalReference )
( defstruct IfcExternallyDefinedHatchStyle )
( defstruct IfcExternallyDefinedSurfaceStyle )
( defstruct IfcExternallyDefinedSymbol )
( defstruct IfcExternallyDefinedTextFont )
( defstruct IfcExtrudedAreaSolid :ExtrudedDirection :Depth :SweptArea :Position :StyledByItem :LayerAssignments )
( defstruct IfcFace :Bounds :StyledByItem :LayerAssignments )
( defstruct IfcFaceBasedSurfaceModel :FbsmFaces :StyledByItem :LayerAssignments )
( defstruct IfcFaceBound :Bound :Orientation :StyledByItem :LayerAssignments )
( defstruct IfcFaceOuterBound :Bound :Orientation :StyledByItem :LayerAssignments )
( defstruct IfcFaceSurface :FaceSurface :SameSense :Bounds :StyledByItem :LayerAssignments )
( defstruct IfcFacetedBrep :Outer :StyledByItem :LayerAssignments )
( defstruct IfcFacetedBrepWithVoids :Voids :Outer :StyledByItem :LayerAssignments )
( defstruct IfcFailureConnectionCondition )
( defstruct IfcFanType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFastener :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFastenerType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFeatureElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFeatureElementAddition :ProjectsElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFeatureElementSubtraction :VoidsElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFillAreaStyle :FillStyles )
( defstruct IfcFillAreaStyleHatching :StartOfNextHatchLine :HatchLineAppearance :HatchLineAngle :StyledByItem :LayerAssignments )
( defstruct IfcFillAreaStyleTileSymbolWithStyle :Symbol :StyledByItem :LayerAssignments )
( defstruct IfcFillAreaStyleTiles :TilingPattern :Tiles :TilingScale :StyledByItem :LayerAssignments )
( defstruct IfcFilterType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFireSuppressionTerminalType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowController :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowControllerType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowFitting :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowFittingType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowInstrumentType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowMeterType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowMovingDevice :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowMovingDeviceType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowSegment :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowSegmentType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowStorageDevice :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowStorageDeviceType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowTerminal :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowTerminalType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowTreatmentDevice :HasControlElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFlowTreatmentDeviceType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFluidFlowProperties :PropertySource :Fluid :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFooting :PredefinedType :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFuelProperties :Material )
( defstruct IfcFurnishingElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFurnishingElementType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFurnitureStandard :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcFurnitureType :AssemblyPlace :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcGasTerminalType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcGeneralMaterialProperties :Material )
( defstruct IfcGeneralProfileProperties )
( defstruct IfcGeometricCurveSet :Elements :StyledByItem :LayerAssignments )
( defstruct IfcGeometricRepresentationContext :CoordinateSpaceDimension :HasSubContexts :WorldCoordinateSystem :RepresentationsInContext )
( defstruct IfcGeometricRepresentationItem :StyledByItem :LayerAssignments )
( defstruct IfcGeometricRepresentationSubContext :TargetView :ParentContext :CoordinateSpaceDimension :HasSubContexts :WorldCoordinateSystem :RepresentationsInContext )
( defstruct IfcGeometricSet :Elements :StyledByItem :LayerAssignments )
( defstruct IfcGrid :UAxes :VAxes :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcGridAxis :SameSense :PartOfW :PartOfV :PartOfU :HasIntersections :AxisCurve )
( defstruct IfcGridPlacement :PlacementLocation :PlacesObject :ReferencedByPlacements )
( defstruct IfcGroup :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcHalfSpaceSolid :BaseSurface :AgreementFlag :StyledByItem :LayerAssignments )
( defstruct IfcHeatExchangerType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcHumidifierType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcHygroscopicMaterialProperties :Material )
( defstruct IfcIShapeProfileDef :OverallWidth :OverallDepth :WebThickness :FlangeThickness :Position :ProfileType )
( defstruct IfcImageTexture :UrlReference :RepeatS :RepeatT :TextureType )
( defstruct IfcInventory :Jurisdiction :ResponsiblePersons :LastUpdateDate :InventoryType :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcIrregularTimeSeries :Values :Name :TimeSeriesDataType :DataOrigin :DocumentedBy :StartTime :EndTime )
( defstruct IfcIrregularTimeSeriesValue :ListValues :TimeStamp )
( defstruct IfcJunctionBoxType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcLShapeProfileDef :Depth :Thickness :Position :ProfileType )
( defstruct IfcLaborResource :ResourceOf :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcLampType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcLibraryInformation :Name )
( defstruct IfcLibraryReference :ReferenceIntoLibrary )
( defstruct IfcLightDistributionData :MainPlaneAngle :SecondaryPlaneAngle :LuminousIntensity )
( defstruct IfcLightFixtureType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcLightIntensityDistribution :DistributionData :LightDistributionCurve )
( defstruct IfcLightSource :LightColour :StyledByItem :LayerAssignments )
( defstruct IfcLightSourceAmbient :LightColour :StyledByItem :LayerAssignments )
( defstruct IfcLightSourceDirectional :Orientation :LightColour :StyledByItem :LayerAssignments )
( defstruct IfcLightSourceGoniometric :ColourTemperature :LuminousFlux :LightEmissionSource :Position :LightDistributionDataSource :LightColour :StyledByItem :LayerAssignments )
( defstruct IfcLightSourcePositional :Radius :ConstantAttenuation :DistanceAttenuation :QuadricAttenuation :Position :LightColour :StyledByItem :LayerAssignments )
( defstruct IfcLightSourceSpot :SpreadAngle :BeamWidthAngle :Orientation :Radius :ConstantAttenuation :DistanceAttenuation :QuadricAttenuation :Position :LightColour :StyledByItem :LayerAssignments )
( defstruct IfcLine :Pnt :Dir :StyledByItem :LayerAssignments )
( defstruct IfcLinearDimension :IsRelatedFromCallout :IsRelatedToCallout :Contents :StyledByItem :LayerAssignments )
( defstruct IfcLocalPlacement :RelativePlacement :PlacesObject :ReferencedByPlacements )
( defstruct IfcLocalTime :HourComponent )
( defstruct IfcLoop :StyledByItem :LayerAssignments )
( defstruct IfcManifoldSolidBrep :Outer :StyledByItem :LayerAssignments )
( defstruct IfcMappedItem :MappingSource :MappingTarget :StyledByItem :LayerAssignments )
( defstruct IfcMaterial :HasRepresentation :ClassifiedAs :Name )
( defstruct IfcMaterialClassificationRelationship :MaterialClassifications :ClassifiedMaterial )
( defstruct IfcMaterialDefinitionRepresentation :RepresentedMaterial :ShapeOfProduct :Representations )
( defstruct IfcMaterialLayer :LayerThickness :ToMaterialLayerSet )
( defstruct IfcMaterialLayerSet :MaterialLayers )
( defstruct IfcMaterialLayerSetUsage :LayerSetDirection :DirectionSense :OffsetFromReferenceLine :ForLayerSet )
( defstruct IfcMaterialList :Materials )
( defstruct IfcMaterialProperties :Material )
( defstruct IfcMeasureWithUnit :ValueComponent :UnitComponent )
( defstruct IfcMechanicalConcreteMaterialProperties :Material )
( defstruct IfcMechanicalFastener :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcMechanicalFastenerType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcMechanicalMaterialProperties :Material )
( defstruct IfcMechanicalSteelMaterialProperties :Material )
( defstruct IfcMember :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcMemberType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcMetric :Benchmark :DataValue :Name :ConstraintGrade :ClassifiedAs :RelatesConstraints :IsRelatedWith :PropertiesForConstraint :Aggregates :IsAggregatedIn )
( defstruct IfcMonetaryUnit :Currency )
( defstruct IfcMotorConnectionType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcMove :MoveFrom :MoveTo :TaskId :IsMilestone :OperatesOn :IsSuccessorFrom :IsPredecessorTo :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcNamedUnit :Dimensions :UnitType )
( defstruct IfcObject :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcObjectDefinition :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcObjectPlacement :PlacesObject :ReferencedByPlacements )
( defstruct IfcObjective :ObjectiveQualifier :Name :ConstraintGrade :ClassifiedAs :RelatesConstraints :IsRelatedWith :PropertiesForConstraint :Aggregates :IsAggregatedIn )
( defstruct IfcOccupant :PredefinedType :IsActingUpon :TheActor :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcOffsetCurve2D :Distance :SelfIntersect :BasisCurve :StyledByItem :LayerAssignments )
( defstruct IfcOffsetCurve3D :Distance :SelfIntersect :BasisCurve :RefDirection :StyledByItem :LayerAssignments )
( defstruct IfcOneDirectionRepeatFactor :RepeatFactor :StyledByItem :LayerAssignments )
( defstruct IfcOpenShell :CfsFaces :StyledByItem :LayerAssignments )
( defstruct IfcOpeningElement :HasFillings :VoidsElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcOpticalMaterialProperties :Material )
( defstruct IfcOrderAction :ActionID :TaskId :IsMilestone :OperatesOn :IsSuccessorFrom :IsPredecessorTo :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcOrganization :Name :IsRelatedBy :Relates :Engages )
( defstruct IfcOrganizationRelationship :Name :RelatingOrganization :RelatedOrganizations )
( defstruct IfcOrientedEdge :EdgeElement :Orientation :EdgeStart :EdgeEnd :StyledByItem :LayerAssignments )
( defstruct IfcOutletType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcOwnerHistory :ChangeAction :CreationDate :OwningUser :OwningApplication )
( defstruct IfcParameterizedProfileDef :Position :ProfileType )
( defstruct IfcPath :EdgeList :StyledByItem :LayerAssignments )
( defstruct IfcPerformanceHistory :LifeCyclePhase :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPermeableCoveringProperties :OperationType :PanelPosition :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPermit :PermitID :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPerson :EngagedIn )
( defstruct IfcPersonAndOrganization :ThePerson :TheOrganization )
( defstruct IfcPhysicalComplexQuantity :Discrimination :HasQuantities :Name :PartOfComplex )
( defstruct IfcPhysicalQuantity :Name :PartOfComplex )
( defstruct IfcPhysicalSimpleQuantity :Name :PartOfComplex )
( defstruct IfcPile :PredefinedType :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPipeFittingType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPipeSegmentType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPixelTexture :Width :Height :ColourComponents :Pixel :RepeatS :RepeatT :TextureType )
( defstruct IfcPlacement :Location :StyledByItem :LayerAssignments )
( defstruct IfcPlanarBox :Placement :SizeInX :SizeInY :StyledByItem :LayerAssignments )
( defstruct IfcPlanarExtent :SizeInX :SizeInY :StyledByItem :LayerAssignments )
( defstruct IfcPlane :Position :StyledByItem :LayerAssignments )
( defstruct IfcPlate :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPlateType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPoint :StyledByItem :LayerAssignments )
( defstruct IfcPointOnCurve :BasisCurve :PointParameter :StyledByItem :LayerAssignments )
( defstruct IfcPointOnSurface :PointParameterU :PointParameterV :BasisSurface :StyledByItem :LayerAssignments )
( defstruct IfcPolyLoop :Polygon :StyledByItem :LayerAssignments )
( defstruct IfcPolygonalBoundedHalfSpace :Position :PolygonalBoundary :BaseSurface :AgreementFlag :StyledByItem :LayerAssignments )
( defstruct IfcPolyline :Points :StyledByItem :LayerAssignments )
( defstruct IfcPort :ContainedIn :ConnectedFrom :ConnectedTo :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPostalAddress :OfPerson :OfOrganization )
( defstruct IfcPreDefinedColour :Name )
( defstruct IfcPreDefinedCurveFont :Name )
( defstruct IfcPreDefinedDimensionSymbol :Name )
( defstruct IfcPreDefinedItem :Name )
( defstruct IfcPreDefinedPointMarkerSymbol :Name )
( defstruct IfcPreDefinedSymbol :Name )
( defstruct IfcPreDefinedTerminatorSymbol :Name )
( defstruct IfcPreDefinedTextFont :Name )
( defstruct IfcPresentationLayerAssignment :Name :AssignedItems )
( defstruct IfcPresentationLayerWithStyle :LayerOn :LayerFrozen :LayerBlocked :Name :AssignedItems )
( defstruct IfcPresentationStyle )
( defstruct IfcPresentationStyleAssignment :Styles )
( defstruct IfcProcedure :ProcedureID :ProcedureType :OperatesOn :IsSuccessorFrom :IsPredecessorTo :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcProcess :OperatesOn :IsSuccessorFrom :IsPredecessorTo :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcProduct :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcProductDefinitionShape :HasShapeAspects :ShapeOfProduct :Representations )
( defstruct IfcProductRepresentation :ShapeOfProduct :Representations )
( defstruct IfcProductsOfCombustionProperties :Material )
( defstruct IfcProfileDef :ProfileType )
( defstruct IfcProfileProperties )
( defstruct IfcProject :RepresentationContexts :UnitsInContext :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcProjectOrder :ID :PredefinedType :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcProjectOrderRecord :Records :PredefinedType :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcProjectionCurve :AnnotatedBySymbols :Styles :StyledByItem :LayerAssignments )
( defstruct IfcProjectionElement :ProjectsElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcProperty :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcPropertyBoundedValue :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcPropertyConstraintRelationship :RelatingConstraint :RelatedProperties )
( defstruct IfcPropertyDefinition :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPropertyDependencyRelationship :DependingProperty :DependantProperty )
( defstruct IfcPropertyEnumeratedValue :EnumerationValues :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcPropertyEnumeration :EnumerationValues :Name )
( defstruct IfcPropertyListValue :ListValues :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcPropertyReferenceValue :PropertyReference :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcPropertySet :HasProperties :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPropertySetDefinition :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPropertySingleValue :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcPropertyTableValue :DefiningValues :DefinedValues :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcProtectiveDeviceType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcProxy :ProxyType :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcPumpType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcQuantityArea :AreaValue :Name :PartOfComplex )
( defstruct IfcQuantityCount :CountValue :Name :PartOfComplex )
( defstruct IfcQuantityLength :LengthValue :Name :PartOfComplex )
( defstruct IfcQuantityTime :TimeValue :Name :PartOfComplex )
( defstruct IfcQuantityVolume :VolumeValue :Name :PartOfComplex )
( defstruct IfcQuantityWeight :WeightValue :Name :PartOfComplex )
( defstruct IfcRadiusDimension :IsRelatedFromCallout :IsRelatedToCallout :Contents :StyledByItem :LayerAssignments )
( defstruct IfcRailing :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRailingType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRamp :ShapeType :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRampFlight :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRampFlightType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRationalBezierCurve :WeightsData :Degree :CurveForm :ClosedCurve :SelfIntersect :ControlPointsList :StyledByItem :LayerAssignments )
( defstruct IfcRectangleHollowProfileDef :WallThickness :XDim :YDim :Position :ProfileType )
( defstruct IfcRectangleProfileDef :XDim :YDim :Position :ProfileType )
( defstruct IfcRectangularPyramid :XLength :YLength :Height :Position :StyledByItem :LayerAssignments )
( defstruct IfcRectangularTrimmedSurface :U1 :V1 :U2 :V2 :Usense :Vsense :BasisSurface :StyledByItem :LayerAssignments )
( defstruct IfcReferencesValueDocument :ReferencedDocument :ReferencingValues )
( defstruct IfcRegularTimeSeries :Values :TimeStep :Name :TimeSeriesDataType :DataOrigin :DocumentedBy :StartTime :EndTime )
( defstruct IfcReinforcementBarProperties :TotalCrossSectionArea :SteelGrade )
( defstruct IfcReinforcementDefinitionProperties :ReinforcementSectionDefinitions :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcReinforcingBar :NominalDiameter :CrossSectionArea :BarRole :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcReinforcingElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcReinforcingMesh :LongitudinalBarNominalDiameter :TransverseBarNominalDiameter :LongitudinalBarCrossSectionArea :TransverseBarCrossSectionArea :LongitudinalBarSpacing :TransverseBarSpacing :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAggregates :RelatingObject :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssigns :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssignsTasks :RelatingControl :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssignsToActor :RelatingActor :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssignsToControl :RelatingControl :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssignsToGroup :RelatingGroup :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssignsToProcess :RelatingProcess :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssignsToProduct :RelatingProduct :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssignsToProjectOrder :RelatingControl :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssignsToResource :RelatingResource :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociates :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociatesAppliedValue :RelatingAppliedValue :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociatesApproval :RelatingApproval :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociatesClassification :RelatingClassification :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociatesConstraint :RelatingConstraint :Intent :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociatesDocument :RelatingDocument :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociatesLibrary :RelatingLibrary :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociatesMaterial :RelatingMaterial :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelAssociatesProfileProperties :RelatingProfileProperties :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsElements :RelatingElement :RelatedElement :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsPathElements :RelatedConnectionType :RelatingConnectionType :RelatingElement :RelatedElement :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsPortToElement :RelatingPort :RelatedElement :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsPorts :RelatingPort :RelatedPort :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsStructuralActivity :RelatingElement :RelatedStructuralActivity :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsStructuralElement :RelatingElement :RelatedStructuralMember :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsStructuralMember :RelatingStructuralMember :RelatedStructuralConnection :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsWithEccentricity :ConnectionConstraint :RelatingStructuralMember :RelatedStructuralConnection :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelConnectsWithRealizingElements :RealizingElements :RelatingElement :RelatedElement :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelContainedInSpatialStructure :RelatedElements :RelatingStructure :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelCoversBldgElements :RelatingBuildingElement :RelatedCoverings :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelCoversSpaces :RelatedSpace :RelatedCoverings :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelDecomposes :RelatingObject :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelDefines :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelDefinesByProperties :RelatingPropertyDefinition :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelDefinesByType :RelatingType :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelFillsElement :RelatingOpeningElement :RelatedBuildingElement :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelFlowControlElements :RelatedControlElements :RelatingFlowElement :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelInteractionRequirements :RelatedSpaceProgram :RelatingSpaceProgram :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelNests :RelatingObject :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelOccupiesSpaces :RelatingActor :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelOverridesProperties :OverridingProperties :RelatingPropertyDefinition :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelProjectsElement :RelatingElement :RelatedFeatureElement :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelReferencedInSpatialStructure :RelatedElements :RelatingStructure :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelSchedulesCostItems :RelatingControl :RelatedObjects :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelSequence :TimeLag :SequenceType :RelatingProcess :RelatedProcess :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelServicesBuildings :RelatingSystem :RelatedBuildings :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelSpaceBoundary :PhysicalOrVirtualBoundary :InternalOrExternalBoundary :RelatingSpace :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelVoidsElement :RelatingBuildingElement :RelatedOpeningElement :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelationship :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRelaxation :RelaxationValue :InitialStress )
( defstruct IfcRepresentation :RepresentationMap :OfProductRepresentation :ContextOfItems :Items :LayerAssignments )
( defstruct IfcRepresentationContext :RepresentationsInContext )
( defstruct IfcRepresentationItem :StyledByItem :LayerAssignments )
( defstruct IfcRepresentationMap :MapUsage :MappingOrigin :MappedRepresentation )
( defstruct IfcResource :ResourceOf :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRevolvedAreaSolid :Axis :Angle :SweptArea :Position :StyledByItem :LayerAssignments )
( defstruct IfcRibPlateProfileProperties :Direction )
( defstruct IfcRightCircularCone :Height :BottomRadius :Position :StyledByItem :LayerAssignments )
( defstruct IfcRightCircularCylinder :Height :Radius :Position :StyledByItem :LayerAssignments )
( defstruct IfcRoof :ShapeType :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRoot :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRoundedEdgeFeature :VoidsElements :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcRoundedRectangleProfileDef :RoundingRadius :XDim :YDim :Position :ProfileType )
( defstruct IfcSIUnit :Name :Dimensions :UnitType )
( defstruct IfcSanitaryTerminalType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcScheduleTimeControl :ScheduleTimeControlAssigned :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSectionProperties :StartProfile :SectionType )
( defstruct IfcSectionReinforcementProperties :LongitudinalStartPosition :LongitudinalEndPosition :ReinforcementRole :SectionDefinition :CrossSectionReinforcementDefinitions )
( defstruct IfcSectionedSpine :SpineCurve :CrossSections :CrossSectionPositions :StyledByItem :LayerAssignments )
( defstruct IfcSensorType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcServiceLife :ServiceLifeType :ServiceLifeDuration :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcServiceLifeFactor :MostUsedValue :PredefinedType :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcShapeAspect :ProductDefinitional :ShapeRepresentations :PartOfProductDefinitionShape )
( defstruct IfcShapeModel :OfShapeAspect :RepresentationMap :OfProductRepresentation :ContextOfItems :Items :LayerAssignments )
( defstruct IfcShapeRepresentation :OfShapeAspect :RepresentationMap :OfProductRepresentation :ContextOfItems :Items :LayerAssignments )
( defstruct IfcShellBasedSurfaceModel :SbsmBoundary :StyledByItem :LayerAssignments )
( defstruct IfcSimpleProperty :Name :PropertyForDependance :PropertyDependsOn :PartOfComplex )
( defstruct IfcSite :CompositionType :ReferencesElements :ServicedBySystems :ContainsElements :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSlab :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSlabType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSlippageConnectionCondition )
( defstruct IfcSolidModel :StyledByItem :LayerAssignments )
( defstruct IfcSoundProperties :IsAttenuating :SoundValues :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSoundValue :Frequency :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSpace :InteriorOrExteriorSpace :HasCoverings :BoundedBy :CompositionType :ReferencesElements :ServicedBySystems :ContainsElements :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSpaceHeaterType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSpaceProgram :SpaceProgramIdentifier :StandardRequiredArea :HasInteractionReqsFrom :HasInteractionReqsTo :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSpaceThermalLoadProperties :ThermalLoadSource :PropertySource :MaximumValue :ThermalLoadType :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSpaceType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSpatialStructureElement :CompositionType :ReferencesElements :ServicedBySystems :ContainsElements :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSpatialStructureElementType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSphere :Radius :Position :StyledByItem :LayerAssignments )
( defstruct IfcStackTerminalType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStair :ShapeType :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStairFlight :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStairFlightType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralAction :DestabilizingLoad :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralActivity :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralAnalysisModel :PredefinedType :ServicesBuildings :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralConnection :ConnectsStructuralMembers :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralConnectionCondition )
( defstruct IfcStructuralCurveConnection :ConnectsStructuralMembers :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralCurveMember :PredefinedType :ReferencesElement :ConnectedBy :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralCurveMemberVarying :PredefinedType :ReferencesElement :ConnectedBy :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralItem :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralLinearAction :ProjectedOrTrue :DestabilizingLoad :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralLinearActionVarying :VaryingAppliedLoadLocation :SubsequentAppliedLoads :ProjectedOrTrue :DestabilizingLoad :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralLoad )
( defstruct IfcStructuralLoadGroup :PredefinedType :ActionType :ActionSource :SourceOfResultGroup :LoadGroupFor :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralLoadLinearForce )
( defstruct IfcStructuralLoadPlanarForce )
( defstruct IfcStructuralLoadSingleDisplacement )
( defstruct IfcStructuralLoadSingleDisplacementDistortion )
( defstruct IfcStructuralLoadSingleForce )
( defstruct IfcStructuralLoadSingleForceWarping )
( defstruct IfcStructuralLoadStatic )
( defstruct IfcStructuralLoadTemperature )
( defstruct IfcStructuralMember :ReferencesElement :ConnectedBy :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralPlanarAction :ProjectedOrTrue :DestabilizingLoad :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralPlanarActionVarying :VaryingAppliedLoadLocation :SubsequentAppliedLoads :ProjectedOrTrue :DestabilizingLoad :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralPointAction :DestabilizingLoad :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralPointConnection :ConnectsStructuralMembers :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralPointReaction :Causes :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralProfileProperties )
( defstruct IfcStructuralReaction :Causes :AssignedToStructuralItem :AppliedLoad :GlobalOrLocal :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralResultGroup :TheoryType :IsLinear :ResultGroupFor :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralSteelProfileProperties )
( defstruct IfcStructuralSurfaceConnection :ConnectsStructuralMembers :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralSurfaceMember :PredefinedType :ReferencesElement :ConnectedBy :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuralSurfaceMemberVarying :VaryingThicknessLocation :SubsequentThickness :PredefinedType :ReferencesElement :ConnectedBy :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcStructuredDimensionCallout :IsRelatedFromCallout :IsRelatedToCallout :Contents :StyledByItem :LayerAssignments )
( defstruct IfcStyleModel :RepresentationMap :OfProductRepresentation :ContextOfItems :Items :LayerAssignments )
( defstruct IfcStyledItem :Styles :StyledByItem :LayerAssignments )
( defstruct IfcStyledRepresentation :RepresentationMap :OfProductRepresentation :ContextOfItems :Items :LayerAssignments )
( defstruct IfcSubContractResource :ResourceOf :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSubedge :ParentEdge :EdgeStart :EdgeEnd :StyledByItem :LayerAssignments )
( defstruct IfcSurface :StyledByItem :LayerAssignments )
( defstruct IfcSurfaceCurveSweptAreaSolid :StartParam :EndParam :Directrix :ReferenceSurface :SweptArea :Position :StyledByItem :LayerAssignments )
( defstruct IfcSurfaceOfLinearExtrusion :ExtrudedDirection :Depth :SweptCurve :Position :StyledByItem :LayerAssignments )
( defstruct IfcSurfaceOfRevolution :AxisPosition :SweptCurve :Position :StyledByItem :LayerAssignments )
( defstruct IfcSurfaceStyle :Styles :Side )
( defstruct IfcSurfaceStyleLighting :DiffuseTransmissionColour :DiffuseReflectionColour :TransmissionColour :ReflectanceColour )
( defstruct IfcSurfaceStyleRefraction )
( defstruct IfcSurfaceStyleRendering :ReflectanceMethod :SurfaceColour )
( defstruct IfcSurfaceStyleShading :SurfaceColour )
( defstruct IfcSurfaceStyleWithTextures :Textures )
( defstruct IfcSurfaceTexture :RepeatS :RepeatT :TextureType )
( defstruct IfcSweptAreaSolid :SweptArea :Position :StyledByItem :LayerAssignments )
( defstruct IfcSweptDiskSolid :Radius :StartParam :EndParam :Directrix :StyledByItem :LayerAssignments )
( defstruct IfcSweptSurface :SweptCurve :Position :StyledByItem :LayerAssignments )
( defstruct IfcSwitchingDeviceType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSymbolStyle :StyleOfSymbol )
( defstruct IfcSystem :ServicesBuildings :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcSystemFurnitureElementType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTShapeProfileDef :Depth :FlangeWidth :WebThickness :FlangeThickness :Position :ProfileType )
( defstruct IfcTable :Rows :Name )
( defstruct IfcTableRow :RowCells :OfTable :IsHeading )
( defstruct IfcTankType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTask :TaskId :IsMilestone :OperatesOn :IsSuccessorFrom :IsPredecessorTo :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTelecomAddress :OfPerson :OfOrganization )
( defstruct IfcTendon :PredefinedType :NominalDiameter :CrossSectionArea :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTendonAnchor :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTerminatorSymbol :AnnotatedCurve :Styles :StyledByItem :LayerAssignments )
( defstruct IfcTextLiteral :Literal :Path :Placement :StyledByItem :LayerAssignments )
( defstruct IfcTextLiteralWithExtent :Extent :BoxAlignment :Literal :Path :Placement :StyledByItem :LayerAssignments )
( defstruct IfcTextStyle :TextFontStyle )
( defstruct IfcTextStyleFontModel :FontSize :Name )
( defstruct IfcTextStyleForDefinedFont :Colour )
( defstruct IfcTextStyleTextModel )
( defstruct IfcTextStyleWithBoxCharacteristics )
( defstruct IfcTextureCoordinate :AnnotatedSurface )
( defstruct IfcTextureCoordinateGenerator :Parameter :Mode :AnnotatedSurface )
( defstruct IfcTextureMap :TextureMaps :AnnotatedSurface )
( defstruct IfcTextureVertex :Coordinates )
( defstruct IfcThermalMaterialProperties :Material )
( defstruct IfcTimeSeries :Name :TimeSeriesDataType :DataOrigin :DocumentedBy :StartTime :EndTime )
( defstruct IfcTimeSeriesReferenceRelationship :ReferencedTimeSeries :TimeSeriesReferences )
( defstruct IfcTimeSeriesSchedule :TimeSeries :TimeSeriesScheduleType :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTimeSeriesValue :ListValues )
( defstruct IfcTopologicalRepresentationItem :StyledByItem :LayerAssignments )
( defstruct IfcTopologyRepresentation :OfShapeAspect :RepresentationMap :OfProductRepresentation :ContextOfItems :Items :LayerAssignments )
( defstruct IfcTransformerType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTransportElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTransportElementType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTrapeziumProfileDef :BottomXDim :TopXDim :YDim :TopXOffset :Position :ProfileType )
( defstruct IfcTrimmedCurve :SenseAgreement :MasterRepresentation :Trim1 :Trim2 :BasisCurve :StyledByItem :LayerAssignments )
( defstruct IfcTubeBundleType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTwoDirectionRepeatFactor :SecondRepeatFactor :RepeatFactor :StyledByItem :LayerAssignments )
( defstruct IfcTypeObject :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcTypeProduct :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcUShapeProfileDef :Depth :FlangeWidth :WebThickness :FlangeThickness :Position :ProfileType )
( defstruct IfcUnitAssignment :Units )
( defstruct IfcUnitaryEquipmentType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcValveType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcVector :Orientation :Magnitude :StyledByItem :LayerAssignments )
( defstruct IfcVertex :StyledByItem :LayerAssignments )
( defstruct IfcVertexBasedTextureMap :TextureVertices :TexturePoints )
( defstruct IfcVertexLoop :LoopVertex :StyledByItem :LayerAssignments )
( defstruct IfcVertexPoint :VertexGeometry :StyledByItem :LayerAssignments )
( defstruct IfcVibrationIsolatorType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcVirtualElement :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcVirtualGridIntersection :IntersectingAxes :OffsetDistances )
( defstruct IfcWall :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWallStandardCase :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWallType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWasteTerminalType :PredefinedType :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWaterProperties :Material )
( defstruct IfcWindow :FillsVoids :ConnectedTo :HasCoverings :HasProjections :HasStructuralMember :HasPorts :HasOpenings :IsConnectionRealization :ProvidesBoundaries :ConnectedFrom :AssignedStructuralActivity :ReferencedBy :ReferencedInStructures :ContainedInStructure :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWindowLiningProperties :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWindowPanelProperties :OperationType :PanelPosition :PropertyDefinitionOf :DefinesType :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWindowStyle :ConstructionType :OperationType :ParameterTakesPrecedence :Sizeable :ObjectTypeOf :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWorkControl :Identifier :CreationDate :StartTime :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWorkPlan :Identifier :CreationDate :StartTime :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcWorkSchedule :Identifier :CreationDate :StartTime :Controls :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
( defstruct IfcZShapeProfileDef :Depth :FlangeWidth :WebThickness :FlangeThickness :Position :ProfileType )
( defstruct IfcZone :IsGroupedBy :IsDefinedBy :HasAssignments :IsDecomposedBy :Decomposes :GlobalId :OwnerHistory :HasAssociations )
