( defstruct TwoByteField )
( defstruct VariableLengthField )
( defstruct IMSTransactionMessage :OIMAPrefixFormat :standardFieldsFlag :messageComponent )
( defstruct OIMAPrefix :controlDataComponent :stateDataComponent )
( defstruct ControlData )
( defstruct StateData )
( defstruct SecurityData )
( defstruct UserData )
( defstruct StandardFields :length :reservedField :transactionCode )
( defstruct ApplicationData :fieldComponents )
( defstruct Field :fieldContainer )
( defstruct TDLangElement )
