( defstruct Element :location )
( defstruct NamedElement :name :location )
( defstruct ExtendedIdentifier :extendedIdentifierOwner :name :location )
( defstruct Extended :extendedIdentifier :location )
( defstruct Definition :extendedIdentifier :location )
( defstruct RuleSet :name :location )
( defstruct ImportDefinition :importDefinitionOwners :dotStar :extendedIdentifier :location )
( defstruct Expression :expressionOwner :ruleConditionExpression :type :location )
( defstruct PropertyCallExpression :expressionOwner :ruleConditionExpression :type :location )
( defstruct IteratorExp :name :body :iterators :expressionOwner :ruleConditionExpression :type :location )
( defstruct LoopExpression :body :iterators :expressionOwner :ruleConditionExpression :type :location )
( defstruct OperatorCallExpression :operationName :expressionOwner :ruleConditionExpression :type :location )
( defstruct OperationCallExpression :operationName :expressionOwner :ruleConditionExpression :type :location )
( defstruct PrimitiveExpression :expressionOwner :ruleConditionExpression :type :location )
( defstruct Iterator :varName :type :location )
( defstruct NumericExpression :expressionOwner :ruleConditionExpression :type :location )
( defstruct IntegerExpression :integerSymbol :expressionOwner :ruleConditionExpression :type :location )
( defstruct RealExpression :realSymbol :expressionOwner :ruleConditionExpression :type :location )
( defstruct BooleanExpression :booleanSymbol :expressionOwner :ruleConditionExpression :type :location )
( defstruct NavigationOrAttributeCallExpression :name :expressionOwner :ruleConditionExpression :type :location )
( defstruct VariableExpression :referredVariable :name :expressionOwner :ruleConditionExpression :type :location )
( defstruct StringExpression :stringSymbol :expressionOwner :ruleConditionExpression :type :location )
( defstruct Type :typeOwner :name :location )
( defstruct Typed :type :location )
( defstruct Primitive :typeOwner :name :location )
( defstruct StringType :typeOwner :name :location )
( defstruct NumericType :typeOwner :name :location )
( defstruct IntegerType :typeOwner :name :location )
( defstruct RealType :typeOwner :name :location )
( defstruct BooleanType :typeOwner :name :location )
( defstruct ClassType :typeOwner :name :location )
( defstruct PropertyDefinition :propertyDefinitionOwner :semicoloneOpt :extendedIdentifier :location )
( defstruct RuleSetDeclaration :ruleSetDeclarationOwner :location )
( defstruct ClassInstancesDeclaration :ruleSetDeclarationOwner :location :extendedIdentifier :location )
( defstruct PropertyDeclaration :ruleSetDeclarationOwner :location )
( defstruct VariableDeclaration :varName :type :location )
( defstruct RulesetElementDefinition :rulesetElementDefinitionOwner :name :location )
( defstruct RuleDefinition :rulesetElementDefinitionOwner :name :location )
( defstruct Binding :bindingOwner :location )
( defstruct RuleVariable :ruleVariableOwner :varName :type :location )
( defstruct CollectionOperationRuleVariable :operationName :ruleVariableOwner :varName :type :location )
( defstruct SimpleRuleVariable :ruleVariableOwner :varName :type :location )
( defstruct RuleCondition :ruleDefinitionCondition :location )
( defstruct RuleAction :location )
( defstruct DeleteAction :objValue :location )
( defstruct CreateAction :location :varName :type :location )
( defstruct ModifyAction :objValue :location )
( defstruct UpdateAction :objValue :location )
( defstruct InvokeAction :invocation :location )
