( defstruct JavaElement :name )
( defstruct ClassFeature :isFinal :name )
( defstruct ClassMember :owner :type :isStatic :isPublic :isFinal :name )
( defstruct Field :owner :type :isStatic :isPublic :isFinal :name )
( defstruct JavaClass :package :isAbstract :isStatic :isPublic :isFinal :name )
( defstruct Method :owner :type :isStatic :isPublic :isFinal :name )
( defstruct Package :name )
( defstruct PrimitiveType :package :isAbstract :isStatic :isPublic :isFinal :name )
( defstruct FeatureParameter :type :method :isFinal :name )
