( defstruct Modifier :visibility :state :name )
( defstruct Class :visibility :state :name )
( defstruct Interface :visibility :state :name )
( defstruct Method :share :class :interface :visibility :state :name )
( defstruct Field :share :class :interface :value :typeOf :visibility :state :name )
( defstruct Value )
( defstruct Parameter :name :owner )
( defstruct Type )
( defstruct ReferenceType :reference )
( defstruct PrimitiveType )
( defstruct Int )
