( defstruct LocatedElement )
( defstruct Root )
( defstruct Expression )
( defstruct Integ :val )
( defstruct Floa :val )
( defstruct Str :val )
( defstruct Ident )
( defstruct ValidIdentifier :val )
( defstruct SlotName :val )
( defstruct JessVariable :val )
( defstruct TemplateExpression :templateName :firstSlot )
( defstruct SlotOp :slotIdent :operator :exp )
( defstruct DefinitionExp )
( defstruct GlobalDefinition )
( defstruct VarDefinition :jessVar :eq :expression )
( defstruct FunctionDefinition :funcName )
( defstruct AdviceDefinition :direction :op )
( defstruct UnDefAdvice :op )
( defstruct FactDefinition :factName )
( defstruct RuleDefinition :ruleName )
( defstruct DeclareRule )
( defstruct ModuleDefinition :moduleName )
( defstruct QueryDefinition :queryName )
( defstruct DeclareVar :node :max )
( defstruct TemplateDefinition :templateName )
( defstruct DeclareBloc )
( defstruct ASlotDef :slotName )
( defstruct SlotDef :slotName )
( defstruct MultiSlotDef :slotName )
( defstruct SlotOptions :type :def :defaultDyn )
( defstruct UseFuncExp )
( defstruct WhileExp :hasDo :boolExp )
( defstruct ForExp :initializer :condition :increment )
( defstruct ForeachExp :var :list )
( defstruct FuncCall :funcName )
( defstruct EngineExp )
( defstruct ExitExp )
( defstruct IfExpression :ifthen )
( defstruct ConditionAction :condition )
( defstruct ElifConditionAction :condAct )
