( defstruct Element )
( defstruct ModelElement )
( defstruct KDMEntity :name :model )
( defstruct KDMContainer :name :model )
( defstruct KDMGroup :name :model )
( defstruct KDMRelationship :to :from :model )
( defstruct Annotation :note )
( defstruct Attribute :tag :value )
( defstruct KDMExtensionFamily :name )
( defstruct Stereotype :baseClass :name :family :extendedElement )
( defstruct TagDefinition :tag :type )
( defstruct TaggedValue :value :tag )
( defstruct KDMFramework :name )
( defstruct KDMModel :name )
