( defstruct LocatedElement :location )
( defstruct ModelElement :name :package :location )
( defstruct Classifier :name :package :location )
( defstruct DataType :name :package :location )
( defstruct Enumeration :name :package :location )
( defstruct EnumLiteral :name :package :location )
( defstruct Class :isAbstract :name :package :location )
( defstruct StructuralFeature :lower :upper :isOrdered :isUnique :owner :type :name :package :location )
( defstruct Attribute :lower :upper :isOrdered :isUnique :owner :type :name :package :location )
( defstruct Reference :isContainer :lower :upper :isOrdered :isUnique :owner :type :name :package :location )
( defstruct Package :metamodel :name :package :location )
( defstruct Metamodel :location )
