( defstruct Node :name )
( defstruct ElementNode :name )
( defstruct AttributeNode :value :name )
( defstruct RootNode :name )
( defstruct TextNode :name )
( defstruct KMLNode :name )
( defstruct KMLRootNode :name )
( defstruct Address :value :name )
( defstruct AltitudeMode :value :name )
( defstruct BalloonStyle :name )
( defstruct Color :value :name )
( defstruct ColorMode :value :name )
( defstruct Cookie :value :name )
( defstruct Coordinates :name )
( defstruct Coordinate :name )
( defstruct Description :value :name )
( defstruct Document :name )
( defstruct DrawOrder :value :name )
( defstruct East :value :name )
( defstruct Extrude :value :name )
( defstruct Fill :value :name )
( defstruct FlyToView :value :name )
( defstruct Folder :name )
( defstruct GroundOverlay :name )
( defstruct H :value :name )
( defstruct Heading :value :name )
( defstruct Href :value :name )
( defstruct Icon :name )
( defstruct IconStyle :name )
( defstruct InnerBoundaryIs :name )
( defstruct Key :value :name )
( defstruct LabelStyle :name )
( defstruct Latitude :value :name )
( defstruct LatLonBox :name )
( defstruct LinearRing :name )
( defstruct LineString :name )
( defstruct LineStyle :id :name )
( defstruct LinkDescription :value :name )
( defstruct LinkName :value :name )
( defstruct Longitude :value :name )
( defstruct LookAt :name )
( defstruct Message :name )
( defstruct MinRefreshPeriod :value :name )
( defstruct MultiGeometry :name )
( defstruct Name :value :name )
( defstruct NetworkLink :name )
( defstruct NetworkLinkControl :name )
( defstruct North :value :name )
( defstruct ObjArrayField :name )
( defstruct ObjField :name )
( defstruct Open :value :name )
( defstruct OuterBoundaryIs :name )
( defstruct Outline :value :name )
( defstruct OverlayXY :x :y :xunits :yunits :name )
( defstruct Pair :name )
( defstruct Parent :value :name )
( defstruct Placemark :name )
( defstruct Point :name )
( defstruct Polygon :name )
( defstruct PolyStyle :name )
( defstruct Range :value :name )
( defstruct RefreshInterval :value :name )
( defstruct RefreshMode :value :name )
( defstruct RefreshVisibility :value :name )
( defstruct Rotation :value :name )
( defstruct Schema :name )
( defstruct Scale :value :name )
( defstruct ScreenOverlay :id :name )
( defstruct ScreenXY :x :y :xunits :yunits :name )
( defstruct SimpleArrayField :name )
( defstruct SimpleField :name )
( defstruct Size :x :y :xunits :yunits :name )
( defstruct South :value :name )
( defstruct Snippet :name )
( defstruct Style :id :name )
( defstruct StyleMap :name )
( defstruct StyleUrl :value :name )
( defstruct Tessellate :value :name )
( defstruct Text :name )
( defstruct TextColor :value :name )
( defstruct Tilt :value :name )
( defstruct Type :value :name )
( defstruct Url :name )
( defstruct ViewBoundScale :value :name )
( defstruct ViewRefreshMode :value :name )
( defstruct ViewRefreshTime :value :name )
( defstruct ViewFormat :value :name )
( defstruct Visibility :value :name )
( defstruct W :value :name )
( defstruct West :value :name )
( defstruct Width :value :name )
( defstruct X :value :name )
( defstruct Y :value :name )
