( defstruct Makefile :name :elements )
( defstruct Element :name )
( defstruct Rule :shellLines :name )
( defstruct Macro :value :name )
( defstruct ShellLine :command :display :ruleShellLine )
( defstruct Comment :text )
( defstruct Dependency )
( defstruct RuleDep :ruledep )
( defstruct FileDep :name )
