( defstruct MantisRoot )
( defstruct IdentifiedElt :id )
( defstruct PrivateElt )
( defstruct Issue :i_mantisRoot :project :category :priority :severity :status :reporter :summary :description :reproducibility :dateSubmitted :lastUpdate :id )
( defstruct ValueWithId :value :id )
( defstruct Person :login :value :id )
( defstruct Relationship :type :id )
( defstruct TimeStampedElt :timestamp )
( defstruct Note :author :text :timestamp )
( defstruct Attachment :filename :size :contentType :downloadUrl :timestamp )
