( defstruct NFP :base_Property )
( defstruct Unit :base_EnumerationLiteral )
( defstruct NfpConstraint :base_Constraint )
( defstruct NfpType :base_DataType )
( defstruct Allocated :base_NamedElement )
( defstruct ApplicationAllocationEnd :base_NamedElement )
( defstruct ExecutionPlatformAllocationEnd :base_NamedElement )
( defstruct AllocateActivityGroup :base_ActivityPartition )
( defstruct ClockRefine :base_Dependency )
( defstruct Allocate :base_Abstraction )
( defstruct TimedDomain :base_Package )
( defstruct Clock :base_InstanceSpecification )
( defstruct ClockType :nature :isLogical :base_Class )
( defstruct TimedElement :on )
( defstruct TimedValueSpecification :base_ValueSpecification :on )
( defstruct TimedConstraint :base_Constraint :on )
( defstruct TimedObservation :on )
( defstruct TimedInstantObservation :base_TimeObservation :on )
( defstruct TimedDurationObservation :base_DurationObservation :on )
( defstruct TimedEvent :base_TimeEvent :on )
( defstruct TimedProcessing :base_Action :base_Behavior :base_Message :on )
( defstruct ClockConstraint :base_Constraint :on )
( defstruct Resource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct StorageResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct CommunicationEndPoint :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SynchronizationResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct ConcurrencyResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct Scheduler :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct ProcessingResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct ComputingResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct MutualExclusionResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SecondaryScheduler :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SchedulableResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct CommunicationMedia :base_Connector :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct DeviceResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct TimingResource :nature :isLogical :base_Class :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct ClockResource :nature :isLogical :base_Class :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct TimerResource :nature :isLogical :base_Class :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct GRService :base_ExecutionSpecification :base_BehavioralFeature :base_Behavior :base_Collaboration :base_CollaborationUse )
( defstruct Release :base_ExecutionSpecification :base_BehavioralFeature :base_Behavior :base_Collaboration :base_CollaborationUse )
( defstruct Acquire :base_ExecutionSpecification :base_BehavioralFeature :base_Behavior :base_Collaboration :base_CollaborationUse )
( defstruct ResourceUsage :base_NamedElement )
( defstruct FlowProperty :direction :base_Property )
( defstruct FlowPort :isAtomic :isConjugated :base_Port )
( defstruct MessagePort :base_Port :isAtomic :isConjugated )
( defstruct SendFlowAction :base_InvocationAction )
( defstruct FlowSpecification :base_Interface )
( defstruct SignalSpecification :base_Interface )
( defstruct FlowBFeature :kind :base_BehavioralFeature )
( defstruct LinkTopology :base_Connector )
( defstruct DefaultLink :base_Connector )
( defstruct InterRepetition :repetitionShapeDependence :base_Connector )
( defstruct Distribute :patternShape :repetitionSpace :fromTiler :toTiler :base_Abstraction )
( defstruct Reshape :patternShape :repetitonShape :srcTiler :targetTiler :base_Connector )
( defstruct Tiler :base_Connector )
( defstruct Var :base_Property )
( defstruct ExpressionContext :base_NamedElement )
( defstruct BoundedSubtype :baseType :minValue :maxValue :isMinOpen :isMaxOpen :base_DataType )
( defstruct IntervalType :intervalAttrib :base_DataType )
( defstruct CollectionType :collectionAttrib :base_DataType )
( defstruct ChoiceType :base_DataType )
( defstruct TupleType :base_DataType )
( defstruct RtUnit :isDynamic :base_BehavioredClassifier )
( defstruct PpUnit :base_BehavioredClassifier )
( defstruct RtBehavior :base_Behavior )
( defstruct rtf :base_BehavioralFeature :base_Action :base_Message :base_Signal )
( defstruct RtAction :isAtomic :base_BehavioralFeature :base_InvocationAction )
( defstruct RtService :isAtomic :base_BehavioralFeature )
( defstruct RteConnector :base_Connector )
( defstruct HwResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwResourceService :base_ExecutionSpecification :base_BehavioralFeature :base_Behavior :base_Collaboration :base_CollaborationUse )
( defstruct HwCommunicationResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwArbiter :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwMedia :base_Association :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Connector :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwBus :base_Association :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Connector :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwBridge :base_Association :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Connector :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwEndPoint :base_Port :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct PLD_Organization )
( defstruct HwProcessor :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwComputingResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwISA :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwBranchPredictor :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwASIC :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwPLD :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwMemory :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct Timing )
( defstruct CacheStructure )
( defstruct MemoryOrganization )
( defstruct HwRAM :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwROM :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwDrive :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HWCache :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwStorageManager :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwDMA :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwMMU :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwTimingResource :nature :isLogical :base_Class :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwClock :nature :isLogical :base_Class :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwTimer :nature :isLogical :base_Class :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwDevice :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwI_O :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwSupport :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwComponent :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct Env_Condition )
( defstruct HwPowerSupply :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct HwCoolingSupply :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SwResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SwAccessService :accessedElement :base_ExecutionSpecification :base_BehavioralFeature :base_Behavior :base_Collaboration :base_CollaborationUse )
( defstruct EntryPoint :routine :base_BehavioralFeature :base_Dependency )
( defstruct SwConcurrentResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct InterruptResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SwSchedulableResource :schedulers :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SwTimerResource :nature :isLogical :base_Class :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct MemoryPartition :base_Namespace :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct Alarm :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct DeviceBroker :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct MemoryBroker :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SwInteractionResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SwCommunicationResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Connector :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SwSynchronizationResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SharedDataComResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Connector :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct MessageComResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Connector :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct NotificationResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SwMutualExclusionResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct GaWorkloadGenerator :base_Behavior )
( defstruct GaEventTrace :base_NamedElement )
( defstruct GaWorkloadEvent :base_NamedElement )
( defstruct GaScenario :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct GaStep :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct GaExecHost :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct GaRequestedService :base_Operation :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct GaTimingObs :base_Constraint )
( defstruct GaCommStep :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct GaAcqStep :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct GaRelStep :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct GaLatencyObs :base_Constraint )
( defstruct GaCommHost :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct GaCommChannel :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct GaWorkloadBehavior :base_NamedElement )
( defstruct GaAnalysisContext :workload :platform :base_NamedElement )
( defstruct GaResourcesPlatform :base_Classifier )
( defstruct SaAnalysisContext :workload :platform :base_NamedElement )
( defstruct SaEnd2EndFlow :base_NamedElement )
( defstruct SaCommStep :base_BehavioralFeature :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct SaExecStep :base_BehavioralFeature :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct SaSchedObs :base_Constraint )
( defstruct SaSharedResource :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SaCommHost :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct SaExecHost :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct PaStep :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct PaRequestedStep :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on :base_Operation :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct PaCommStep :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct PaResPassStep :rep :base_NamedElement :base_Action :base_Behavior :base_Message :on )
( defstruct PaLogicalResource :poolSize :base_Property :base_InstanceSpecification :base_Classifier :base_Lifeline :base_ConnectableElement )
( defstruct PaRunTInstance :base_NamedElement )
( defstruct EDFParameters )
( defstruct SchedParameters )
( defstruct FixedPriorityParameters )
( defstruct PoolingParameters )
( defstruct PeriodicServerParameters )
( defstruct NFP_CommonType )
( defstruct NFP_Frequency )
( defstruct NFP_Real )
( defstruct NFP_Natural )
( defstruct NFP_Boolean )
( defstruct NFP_String )
( defstruct NFP_Integer )
( defstruct NFP_DateTime )
( defstruct NFP_DataTxRate )
( defstruct NFP_Power )
( defstruct NFP_DataSize )
( defstruct NFP_Energy )
( defstruct NFP_Length )
( defstruct NFP_Area )
( defstruct ArrivalPattern )
( defstruct PeriodicPattern )
( defstruct AperiodicPattern )
( defstruct BurstPattern )
( defstruct IrregularPattern )
( defstruct ClosedPattern )
( defstruct SporadicPattern )
( defstruct NFP_BoundedDuration )
( defstruct NFP_Percentage )
( defstruct NFP_Duration )
( defstruct IntegerVector )
( defstruct IntegerMatrix )
( defstruct IntegerInterval :bound )
( defstruct UtilityType )
( defstruct Array )
( defstruct Realnterval :bound )
( defstruct NFP_FrequencyInterval :bound )
( defstruct MARTE_DataTypes_Interval )
( defstruct NFP_NaturalInterval :bound )
( defstruct TimedValueType )
( defstruct IdealClock )
( defstruct TilerSpecification :paving )
( defstruct ShapeSpecification )
( defstruct Element )
( defstruct Comment )
( defstruct Package )
( defstruct NamedElement )
( defstruct StructuralFeature :isReadOnly :isStatic :isLeaf :isOrdered :isUnique )
( defstruct ConnectableElement )
( defstruct TemplateableElement )
( defstruct Property :isDerived :isDerivedUnion :aggregation :isComposite :isReadOnly :isStatic :isLeaf :isOrdered :isUnique )
( defstruct Dependency :supplier :client :source :target :relatedElement )
( defstruct DirectedRelationship :source :target :relatedElement )
( defstruct Relationship :relatedElement )
( defstruct Namespace )
( defstruct ElementImport :visibility :importedElement :importingNamespace :source :target :relatedElement )
( defstruct PackageImport :visibility :importedPackage :importingNamespace :source :target :relatedElement )
( defstruct Constraint :specification )
( defstruct TypedElement )
( defstruct Type )
( defstruct Association :isDerived :endType :memberEnd :isAbstract :isLeaf :relatedElement )
( defstruct Classifier :isAbstract :isLeaf )
( defstruct RedefinableElement :isLeaf )
( defstruct TemplateBinding :signature :boundElement :source :target :relatedElement )
( defstruct TemplateSignature :parameter :template )
( defstruct TemplateParameter :signature :parameteredElement )
( defstruct ParameterableElement )
( defstruct TemplateParameterSubstitution :formal :actual :templateBinding )
( defstruct Generalization :general :specific :source :target :relatedElement )
( defstruct GeneralizationSet :isCovering :isDisjoint )
( defstruct Feature :isStatic :isLeaf )
( defstruct Substitution :contract :substitutingClassifier :supplier :client :source :target :relatedElement )
( defstruct PackageableElement )
( defstruct PackageMerge :mergedPackage :receivingPackage :source :target :relatedElement )
( defstruct ProfileApplication :appliedProfile :isStrict :applyingPackage :source :target :relatedElement )
( defstruct Profile )
( defstruct Stereotype :isActive :isAbstract :isLeaf :isAbstract :isLeaf )
( defstruct Class :isActive :isAbstract :isLeaf :isAbstract :isLeaf )
( defstruct StringExpression )
( defstruct Expression )
( defstruct ValueSpecification )
( defstruct BehavioredClassifier :isAbstract :isLeaf )
( defstruct Behavior :isReentrant :isActive :isAbstract :isLeaf :isAbstract :isLeaf )
( defstruct MultiplicityElement :isOrdered :isUnique )
( defstruct DeploymentTarget )
( defstruct DataType :isAbstract :isLeaf )
( defstruct CollaborationUse :type )
( defstruct UseCase :isAbstract :isLeaf )
( defstruct Realization :supplier :client :source :target :relatedElement )
( defstruct Abstraction :supplier :client :source :target :relatedElement )
( defstruct Image )
( defstruct OpaqueExpression )
( defstruct Parameter :direction :isException :isStream :isOrdered :isUnique )
( defstruct EncapsulatedClassifier :isAbstract :isLeaf )
( defstruct Operation :isQuery :isOrdered :isUnique :isAbstract :concurrency :isStatic :isLeaf )
( defstruct Reception :isAbstract :concurrency :isStatic :isLeaf )
( defstruct Extension :isRequired :metaclass :isDerived :endType :memberEnd :isAbstract :isLeaf :relatedElement )
( defstruct EnumerationLiteral )
( defstruct ActivityPartition :isDimension :isExternal )
( defstruct Enumeration :isAbstract :isLeaf )
( defstruct InstanceSpecification )
( defstruct BehavioralFeature :isAbstract :concurrency :isStatic :isLeaf )
( defstruct Signal :isAbstract :isLeaf )
( defstruct TimeExpression )
( defstruct Observation )
( defstruct Duration )
( defstruct DurationInterval :min :max )
( defstruct Interval :min :max )
( defstruct TimeConstraint :specification )
( defstruct IntervalConstraint :specification )
( defstruct TimeInterval :min :max )
( defstruct DurationConstraint :specification )
( defstruct TimeObservation :event :firstEvent )
( defstruct DurationObservation :event )
( defstruct ConnectorEnd :role :isOrdered :isUnique )
( defstruct TimeEvent :isRelative :when )
( defstruct Event )
( defstruct Port :isBehavior :isService :isDerived :isDerivedUnion :aggregation :isComposite :isReadOnly :isStatic :isLeaf :isOrdered :isUnique )
( defstruct Action :isLeaf )
( defstruct Message :messageKind :messageSort :interaction )
( defstruct Lifeline :interaction )
( defstruct ExecutionSpecification :start :finish )
( defstruct InvocationAction :isLeaf )
( defstruct Connector :end :isStatic :isLeaf )
( defstruct Collaboration :isAbstract :isLeaf :isAbstract :isLeaf )
( defstruct Interface :isAbstract :isLeaf )
( defstruct InterfaceRealization :contract :implementingClassifier :supplier :client :source :target :relatedElement )
( defstruct Trigger :event )
( defstruct ProtocolStateMachine :region :isReentrant :isActive :isAbstract :isLeaf :isAbstract :isLeaf )
( defstruct StateMachine :region :isReentrant :isActive :isAbstract :isLeaf :isAbstract :isLeaf )
( defstruct ProtocolConformance :generalMachine :specificMachine :source :target :relatedElement )
( defstruct Deployment :location :supplier :client :source :target :relatedElement )
( defstruct Include :addition :includingCase :source :target :relatedElement )
( defstruct Extend :extendedCase :extensionLocation :extension :source :target :relatedElement )
( defstruct ExtensionPoint :useCase :isLeaf )
( defstruct Region :isLeaf )
( defstruct StructuredClassifier :isAbstract :isLeaf )
( defstruct Vertex )
( defstruct Transition :kind :container :target :source :isLeaf )
( defstruct State :isComposite :isOrthogonal :isSimple :isSubmachineState :isLeaf )
( defstruct ParameterSet :parameter )
( defstruct ActivityNode :isLeaf )
( defstruct ActivityGroup )
( defstruct ActivityEdge :source :target :guard :weight :isLeaf )
( defstruct InterruptibleActivityRegion )
( defstruct DeployedArtifact )
( defstruct Slot :definingFeature :owningInstance )
( defstruct ExecutableNode :isLeaf )
( defstruct OutputPin :isControl :ordering :isControlType :upperBound :isLeaf :isOrdered :isUnique )
( defstruct Pin :isControl :ordering :isControlType :upperBound :isLeaf :isOrdered :isUnique )
( defstruct InputPin :isControl :ordering :isControlType :upperBound :isLeaf :isOrdered :isUnique )
( defstruct ExceptionHandler :handlerBody :exceptionInput :exceptionType :protectedNode )
( defstruct ObjectNode :ordering :isControlType :upperBound :isLeaf )
( defstruct MessageEnd )
( defstruct Interaction :isReentrant :isActive :isAbstract :isLeaf :isAbstract :isLeaf )
( defstruct PartDecomposition :refersTo )
( defstruct InteractionUse :refersTo )
( defstruct InteractionFragment )
( defstruct Pseudostate :kind )
( defstruct ConnectionPointReference )
( defstruct StructuredActivityNode :mustIsolate :isLeaf )
( defstruct Variable :isOrdered :isUnique )
( defstruct Activity :isReadOnly :isSingleExecution :isReentrant :isActive :isAbstract :isLeaf :isAbstract :isLeaf )
( defstruct OccurrenceSpecification :event )
( defstruct DeploymentSpecification :isAbstract :isLeaf )
( defstruct Gate )
( defstruct Artifact :isAbstract :isLeaf )
( defstruct GeneralOrdering :before :after )
( defstruct Manifestation :utilizedElement :supplier :client :source :target :relatedElement )
( defstruct InteractionOperand )
( defstruct InteractionConstraint :specification )
