( defstruct Agent :requirement :fipa_Platform_Agent :role )
( defstruct Service :inputs :outputs :pre-conditions :post-conditions )
( defstruct Non Functionnal Requirement )
( defstruct Requirement )
( defstruct Organization :organizational_Structure )
( defstruct Organizational Structure )
( defstruct SafetyRule )
( defstruct LivenessRule )
( defstruct CooperationRules :ncs )
( defstruct NCS :cooperationRules )
( defstruct FIPA-Platform Agent :agentF )
( defstruct FIPA-Platform Task :fipa_Platform_AgentF :task )
( defstruct Task :name :fipa_Platform_TaskT )
( defstruct Role :agentR :activity :scenario :has )
( defstruct Representation :agentRep :environnement )
( defstruct Characteristic :agentC )
( defstruct Skill :agentS )
( defstruct Aptitude :agentA )
( defstruct Ontology :environnement )
( defstruct Concept :environnement )
( defstruct Predicat :environnement )
( defstruct Action :environnement )
( defstruct Environnement :resource )
( defstruct Responsibility )
( defstruct LivenessProperty )
( defstruct SafetyProperty )
( defstruct Resource :name :environnement :action )
( defstruct Communication :name :Exchanged Knoledge :scenario :aip )
( defstruct AIP :name :performative )
( defstruct Performative :aip )
( defstruct Message :communication :Comm_Act )
( defstruct Scenario )
