( defstruct METAHFile )
( defstruct METAHEntry )
( defstruct Package :packName )
( defstruct PackageImplementation :implementationName :implements )
( defstruct Data :dataName )
( defstruct Attribute :attName :attValue :attValueType :attType )
( defstruct ProcessDeclaration :procDecName )
( defstruct ProcessImplementation :procImpName :declaration )
( defstruct ProcessAttribute :attName :attValue :attValueType )
( defstruct Process :procName :periodic :declaration :implementation )
( defstruct Port :portName :portCom :portPackage :portType )
( defstruct Connection :compSrc :portSrc :compDest :portDest )
( defstruct MacroDeclaration :name )
( defstruct MacroImplementation :macroImpName :declaration )
