( defstruct ModelElement )
( defstruct Classifier )
( defstruct StructuralFeature )
( defstruct Class :name :attributes )
( defstruct DataType :attribute )
( defstruct Attribute :class :has )
( defstruct Case :name :caseMode :caseInput :documentation :listOfStep )
( defstruct Step :name :description :belongsToCase :embedsOperator )
( defstruct LoopStep :name :description :belongsToCase :embedsOperator )
( defstruct MultiStep :iterationCondition :name :description :belongsToCase :embedsOperator )
( defstruct Operator :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Parameter :name :place :parameterType :belongsToOperator )
( defstruct FeatureConstruction :scalingFactor :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct DataMinStep :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct TimeOperator :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct FeatureSelection :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct MultiRelFeatureConstr :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct RowSelection :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Agregation :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Scaling :scalingFactor :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Discretization :scalingFactor :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Segmentation :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Sampling :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct ExecutionElement :source :target )
( defstruct DataObject :source :target )
( defstruct MSL-Tool :source :target )
( defstruct TransformationGroup :source :target )
( defstruct Transformation :transformationGroup :source :target )
( defstruct Function :nameOf :signature :transformationGroup :source :target )
( defstruct StoredProcedure :nameOf :signature :transformationGroup :source :target )
( defstruct SQLQuery :transformationGroup :source :target )
