( defstruct ModelElement )
( defstruct Classifier )
( defstruct StructuralFeature )
( defstruct Class :name :attributes )
( defstruct DataType :attribute )
( defstruct Attribute :class :has )
( defstruct Concept :name :attributes )
( defstruct ColumnSet :name :attributes )
( defstruct Column :class :has )
( defstruct FeatureAttribute :class :has )
( defstruct Value :class :has )
( defstruct RoleRestriction :class :has )
( defstruct Integer :attribute )
( defstruct String :attribute )
( defstruct DomainDataType :attribute )
