( defstruct ModelElement )
( defstruct Classifier )
( defstruct StructuralFeature )
( defstruct Class :name :attributes )
( defstruct DataType :attribute )
( defstruct Attribute :class :has )
( defstruct Column :name :dataType :belongsToColumnSet :corespondsToBaseAttribute :class :has )
( defstruct ColumnSet :number :file :dbConnectString :user :hasColumn :hasKey :name :attributes )
( defstruct ColumnStatistics :unique :missing :min :max :average :standarDeviation :distributionValue :distributionCount :distributionMin :distributionMax :forColumn )
( defstruct ColumnSetStatistics :allNumber :ordinalNumber :nominalNumber :timeNumber :forColumnSet )
( defstruct Snapshot :number :file :dbConnectString :user :hasColumn :hasKey :name :attributes )
( defstruct Table :number :file :dbConnectString :user :hasColumn :hasKey :name :attributes )
( defstruct View :number :file :dbConnectString :user :hasColumn :hasKey :name :attributes )
( defstruct Key :isUsedForIndex :hasColumn :isAssociatedToColumnSet )
( defstruct ForeignKey :isUsedForIndex :hasColumn :isAssociatedToColumnSet )
( defstruct PrimaryKey :isUsedForIndex :hasColumn :isAssociatedToColumnSet )
( defstruct Concept :subConceptRestriction :isA :FromConcept :ToConcept :name :attributes )
( defstruct RelationShip :name :subRelationShipRestriction :defined :isA :correspondsToForeignKey :FromConcept :ToConcept )
( defstruct FeatureAttribute :name :relevanceForMining :attributeType :belongsToConcept :correspondsToColumns :class :has )
( defstruct BaseAttribute :domainDataType :name :relevanceForMining :attributeType :belongsToConcept :correspondsToColumns :class :has )
( defstruct MultiColumnFeature :name :relevanceForMining :attributeType :belongsToConcept :correspondsToColumns :class :has )
( defstruct Value :name :domainDataType :belongsToUserInput :class :has )
( defstruct UserInput :containsValues :name :attributes )
( defstruct Ordinal :baseAttributeD :attribute )
( defstruct Scalar :baseAttributeD :attribute )
( defstruct Time :baseAttributeD :attribute )
( defstruct Binary :baseAttributeD :attribute :baseAttributeD :attribute )
( defstruct Categorial :baseAttributeD :attribute )
( defstruct KeyAttribute :baseAttributeD :attribute )
( defstruct TimeGroup :baseAttributeD :attribute )
( defstruct Spatial :baseAttributeD :attribute )
( defstruct Constant :baseAttributeD :attribute )
( defstruct RoleRestriction :name :restrictionForRelationShip :restrictionForConcept :restrictionToConcept :min :max :belongsToConcept :class :has )
( defstruct DomainDataType :baseAttributeD :attribute )
( defstruct Nominal :baseAttributeD :attribute )
( defstruct Parameter )
