( defstruct ModelElement )
( defstruct Classifier )
( defstruct StructuralFeature )
( defstruct Class :name :attributes )
( defstruct DataType :attribute )
( defstruct Attribute :class :has )
( defstruct Column :name :dataType :belongsToColumnSet :corespondsToBaseAttribute :class :has )
( defstruct ColumnSet :number :file :dbConnectString :user :hasColumn :hasKey :name :attributes )
( defstruct ColumnStatistics :unique :missing :min :max :average :standarDeviation :distributionValue :distributionCount :distributionMin :distributionMax :forColumn )
( defstruct ColumnSetStatistics :allNumber :ordinalNumber :nominalNumber :timeNumber :forColumnSet )
( defstruct Snapshot :number :file :dbConnectString :user :hasColumn :hasKey :name :attributes )
( defstruct Table :number :file :dbConnectString :user :hasColumn :hasKey :name :attributes )
( defstruct View :number :file :dbConnectString :user :hasColumn :hasKey :name :attributes )
( defstruct Key :isUsedForIndex :hasColumn :isAssociatedToColumnSet )
( defstruct ForeignKey :isUsedForIndex :hasColumn :isAssociatedToColumnSet )
( defstruct PrimaryKey :isUsedForIndex :hasColumn :isAssociatedToColumnSet )
( defstruct Concept :subConceptRestriction :isA :FromConcept :ToConcept :name :attributes :name :place :parameterType :belongsToOperator )
( defstruct RelationShip :subRelationShipRestriction :defined :isA :correspondsToForeignKey :FromConcept :ToConcept :name :place :parameterType :belongsToOperator )
( defstruct FeatureAttribute :name :relevanceForMining :attributeType :belongsToConcept :correspondsToColumns :class :has )
( defstruct BaseAttribute :domainDataType :name :relevanceForMining :attributeType :belongsToConcept :correspondsToColumns :class :has )
( defstruct MultiColumnFeature :name :relevanceForMining :attributeType :belongsToConcept :correspondsToColumns :class :has )
( defstruct Value :domainDataType :belongsToUserInput :class :has :name :place :parameterType :belongsToOperator )
( defstruct UserInput :containsValues :name :attributes )
( defstruct Ordinal :baseAttributeD :attribute )
( defstruct Scalar :baseAttributeD :attribute )
( defstruct Time :baseAttributeD :attribute )
( defstruct Binary :baseAttributeD :attribute :baseAttributeD :attribute )
( defstruct Categorial :baseAttributeD :attribute )
( defstruct KeyAttribute :baseAttributeD :attribute )
( defstruct TimeGroup :baseAttributeD :attribute )
( defstruct Spatial :baseAttributeD :attribute )
( defstruct Constant :baseAttributeD :attribute )
( defstruct RoleRestriction :name :restrictionForRelationShip :restrictionForConcept :restrictionToConcept :min :max :belongsToConcept :class :has )
( defstruct DomainDataType :baseAttributeD :attribute )
( defstruct Nominal :baseAttributeD :attribute )
( defstruct Case :name :caseMode :caseInput :caseOutput :documentation :listOfStep :population :targetAttributes )
( defstruct Step :name :description :belongsToCase :embedsOperator )
( defstruct LoopStep :name :description :belongsToCase :embedsOperator )
( defstruct MultiStep :iterationCondition :name :description :belongsToCase :embedsOperator )
( defstruct Operator :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Parameter :name :place :parameterType :belongsToOperator )
( defstruct FeatureConstruction :scalingFactor :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct DataMinStep :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct TimeOperator :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct FeatureSelection :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct MultiRelFeatureConstr :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct RowSelection :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Agregation :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Scaling :scalingFactor :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Discretization :scalingFactor :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Segmentation :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct Sampling :loopable :numberOfInputParameters :numberOfOutputParameters :manual :tool :input :output :realizes )
( defstruct ExecutionElement :source :target )
( defstruct DataObject :source :target :linkPackageCaseRepresentation )
( defstruct MSL-Tool :source :target )
( defstruct TransformationGroup :source :target )
( defstruct Transformation :transformationGroup :source :target )
( defstruct Function :nameOf :signature :transformationGroup :source :target )
( defstruct StoredProcedure :nameOf :signature :transformationGroup :source :target )
( defstruct SQLQuery :select :from :transformationGroup :source :target )
( defstruct LinkPackage :type :dataObject )
