( defstruct Action :description :language :name :uuid )
( defstruct Activity :description :timing :actions :name :uuid )
( defstruct AdminEntry :data :language :name :uuid )
( defstruct ASKR :evName :evMeaning )
( defstruct ASKU :evName :evMeaning )
( defstruct Attestation :proof :reason :commiter :timeCommited :isPending :name :uuid )
( defstruct CareEntry :language :name :uuid )
( defstruct CCD :definition :metaData :ontology )
( defstruct Cluster :items :name :uuid )
( defstruct Composition :attestation :created :composer :language :context :content :name :uuid )
( defstruct ContentItem :name :uuid )
( defstruct DataStructure :name :uuid )
( defstruct DER :evName :evMeaning )
( defstruct Device :details :name :uuid )
( defstruct DvAny )
( defstruct DvBoolean )
( defstruct DvByte )
( defstruct DvChar )
( defstruct DvCodedString :uuid )
( defstruct DvCount :count :error :accuracy )
( defstruct DvDate )
( defstruct DvDateTime )
( defstruct DvDecimal )
( defstruct DvDuration )
( defstruct DvEncapsulated :size )
( defstruct DvIdentifier :uuid )
( defstruct DvInt )
( defstruct DvInteger )
( defstruct DvInterval :lowerIncluded :upperIncluded :lowerUnbounded :upperUnbounded )
( defstruct DvLanguage )
( defstruct DvLong )
( defstruct DvMedia :mimeType :size )
( defstruct DvMediaApp :mimeType :size )
( defstruct DvMediaAudio :mimeType :size )
( defstruct DvMediaImage :mimeType :size )
( defstruct DvMediaModel :mimeType :size )
( defstruct DvMediaMsg :mimeType :size )
( defstruct DvMediaMultipart :mimeType :size )
( defstruct DvMediaText :mimeType :size )
( defstruct DvMediaVideo :mimeType :size )
( defstruct DvNegativeInteger )
( defstruct DvNonNegativeInteger )
( defstruct DvNonPositiveInteger )
( defstruct DvNormalizedString :uuid )
( defstruct DvNumeric )
( defstruct DvOrdered )
( defstruct DvOrdinal )
( defstruct DvParagraph )
( defstruct DvParsable :size )
( defstruct DvPositiveInteger )
( defstruct DvProportion :numerator :denominator :error :accuracy )
( defstruct DvQuantified :error :accuracy )
( defstruct DvQuantity :units :error :accuracy )
( defstruct DvRate :numerator :denominator :error :accuracy )
( defstruct DvRatio :numerator :denominator :error :accuracy )
( defstruct DvShort )
( defstruct DvString :uuid )
( defstruct DvTemporal )
( defstruct DvTime )
( defstruct DvToken )
( defstruct DvUnsignedByte )
( defstruct DvUnsignedInt )
( defstruct DvUnsignedLong )
( defstruct DvUnsignedShort )
( defstruct DvURI )
( defstruct Element :dv :name :uuid )
( defstruct EntityRef :uuid :namespace :objType )
( defstruct Entry :language :name :uuid )
( defstruct Evaluation :data :language :name :uuid )
( defstruct Event :time :data :name :uuid )
( defstruct EventContext :startTime :name :uuid )
( defstruct ExceptionalValue :evName :evMeaning )
( defstruct FeederAudit :originatingSystemAudit :originatingSystemItemIds :feederSystemAudit :feederSystemIds :originalContent )
( defstruct FeederAuditDetails :systemId )
( defstruct Folder :name :uuid )
( defstruct Group :name :uuid )
( defstruct History :origin :events :name :uuid )
( defstruct Instruction :narrative :activities :language :name :uuid )
( defstruct IntervalEvent :width :mathFunction :time :data :name :uuid )
( defstruct INV :evName :evMeaning )
( defstruct Item :name :uuid )
( defstruct ItemList :name :uuid )
( defstruct ItemSingle :item :name :uuid )
( defstruct ItemStructure :name :uuid )
( defstruct ItemTable :rows :name :uuid )
( defstruct ItemTree :items :name :uuid )
( defstruct Link :relation :target )
( defstruct Locatable :name :uuid )
( defstruct Location :details :description :isPrimary :name :uuid )
( defstruct MetaDataEntry :title :contents )
( defstruct MetaDataSet :name :entries )
( defstruct MSK :evName :evMeaning )
( defstruct NA :evName :evMeaning )
( defstruct NASK :evName :evMeaning )
( defstruct NAV :evName :evMeaning )
( defstruct NI :evName :evMeaning )
( defstruct NINF :evName :evMeaning )
( defstruct NonHuman :details :name :uuid )
( defstruct ObjectRef :uuid :namespace :objType )
( defstruct Observation :data :language :name :uuid )
( defstruct Ontology )
( defstruct OntologyEntry :contents )
( defstruct Organization :details :name :uuid )
( defstruct OTH :evName :evMeaning )
( defstruct Participation :function :mode :time )
( defstruct Party :name :uuid )
( defstruct PartyIdentified :identifiers )
( defstruct PartyProxy )
( defstruct PartyRelated :relationship :identifiers )
( defstruct PartySelf )
( defstruct Person :details :name :uuid )
( defstruct PINF :evName :evMeaning )
( defstruct PointEvent :time :data :name :uuid )
( defstruct QS :evName :evMeaning )
( defstruct ReferenceRange :definition :dataRange )
( defstruct Relationship :targets :name :uuid )
( defstruct Role :details :description :isPrimary :name :uuid )
( defstruct Section :name :uuid )
( defstruct Slot :ccd :allowedCcds :name :uuid )
( defstruct TRC :evName :evMeaning )
( defstruct UNC :evName :evMeaning )
( defstruct UNK :evName :evMeaning )
