( defstruct Element :name )
( defstruct MoDAFModel :enterprise :environment :operationalMissions :architectures :architecturalDescription :architecturalReferences :architecturalFrameworks :stakeholders :stakeholderHasConcerns :name )
( defstruct Enterprise :inhabits :fulfills :name )
( defstruct Environment :influences :taxonomy :name )
( defstruct OperationalMission :name )
( defstruct Architecture :enterprise :describedBy :name )
( defstruct ArchitecturalDescription :approvialAuthority :architect :assumptionAndConstraints :creatingOrganisation :dateCompleted :purpose :recommendations :summaryOfFindings :tollsUsed :viewpoints :products :taxonomy :name )
( defstruct ArchitecturalReference :referred :referrer :name )
( defstruct ArchitecturalProduct :description :architecturalElements :definingView :name )
( defstruct Elements :name )
( defstruct ArchitecturalFramework :ownedMember :name )
( defstruct View :framework :frameworkWebsite :viewCode :viewDescription :viewName :definingFramework :name )
( defstruct Concern :name )
( defstruct StakeholderHasConcern :client :supplier :owner )
( defstruct Stakeholder :name )
( defstruct MetaData :dublinCoreElement :modMetaDataElement :name :body )
( defstruct ArchitectureMetaData :annotatedArchitecture :dublinCoreElement :modMetaDataElement :name :body )
( defstruct Taxonomy :date :url :version :name )
( defstruct ClassifiedElement :taxonomy :name )
( defstruct Standard :identifier :publishedWebsite :publisher :ratificationDate :version :withdrawalDate :taxonomy :name )
( defstruct MeasurableProperty :taxonomy :name )
( defstruct CapabilityRequirement :taxonomy :name )
( defstruct Effect :taxonomy :name )
( defstruct EnduringTask :taxonomy :name )
( defstruct OperationalConstraint :taxonomy :name )
( defstruct PostType :taxonomy :name )
( defstruct OrganisationType :taxonomy :name )
( defstruct RoleInOrganisation :taxonomy :name )
( defstruct LocationType :taxonomy :name )
( defstruct OperationalActivity :taxonomy :name )
( defstruct Node :taxonomy :name )
( defstruct InformationExchange :identifier :taxonomy :name )
( defstruct Competence :taxonomy :name )
( defstruct InformationElement :taxonomy :name )
( defstruct NodeConnectionType :taxonomy :name )
( defstruct System :taxonomy :name )
( defstruct DataElement :taxonomy :name )
( defstruct SystemFunction :systemUsageContext :taxonomy :name )
( defstruct SystemConnectionSpecification :taxonomy :name )
( defstruct ProjectType :taxonomy :name )
( defstruct Service :taxonomy :name )
( defstruct Unit :taxonomy :name )
( defstruct Dimension :taxonomy :name )
( defstruct OrganisationProjectRelationship :taxonomy :name )
( defstruct ProjectThreadType :taxonomy :name )
( defstruct TimeExpression :value )
( defstruct LiteralSpecification :value )
( defstruct Property :value )
