( defstruct LocatedElement :location )
( defstruct NamedElement :name :location )
( defstruct Structure :name :location )
( defstruct ProcContainerElement :name :location )
( defstruct Program :name :location )
( defstruct Monitor :program :name :location )
( defstruct Procedure :container :name :location )
( defstruct VariableDeclaration :type :structure :name :location )
( defstruct Parameter :direction :procedure :type :structure :name :location )
( defstruct Type :name :location )
( defstruct Expression :location )
( defstruct VariableExp :declaration :location )
( defstruct PropertyCallExp :source :name :location )
( defstruct OperatorCallExp :right :source :name :location )
( defstruct AttributeCallExp :source :name :location )
( defstruct ProcedureCallExp :source :name :location )
( defstruct LiteralExp :location )
( defstruct BooleanExp :symbol :location )
( defstruct IntegerExp :symbol :location )
( defstruct Statement :location )
( defstruct AssignmentStat :target :value :location )
( defstruct ConditionalStat :condition :thenStats :location )
( defstruct WhileStat :condition :doStats :location )
( defstruct ExpressionStat :expression :location )
