( defstruct DateTimeType :year :month :day :hour :minute :second )
( defstruct VersionType :n :nn )
( defstruct ValueType )
( defstruct StringValue :value )
( defstruct FloatValue :value )
( defstruct DateTimeTypeValue :value )
( defstruct BooleanValue :value )
( defstruct DocumentPropertiesCollection :dp_wordDocument )
( defstruct CustomDocumentPropertiesCollection :cdp_wordDocument :customDocumentProperties )
( defstruct CustomDocumentProperty :customDocumentProperty_cdpe :name :value )
( defstruct SmartTagType :smartTagType_ste :namespaceuri :name )
( defstruct SmartTagsCollection :st_wordDocument )
( defstruct StringProperty :val )
( defstruct StringType :val )
( defstruct WordDocument :body )
( defstruct DocPrElt :dpe_wordDocument )
( defstruct BodyElt :be_wordDocument )
( defstruct BlockLevelElt :ble_bodyElt :ble_note :ble_tableCellElt )
( defstruct BlockLevelChunkElt :ble_bodyElt :ble_note :ble_tableCellElt )
( defstruct ParaElt :ble_bodyElt :ble_note :ble_tableCellElt )
( defstruct ParaPrElt :ppe_pElt )
( defstruct ParaContentElt :pce_pElt )
( defstruct RunElt :pce_pElt )
( defstruct RunPrElt :rpe_rElt )
( defstruct RunContentElt :rce_rElt )
( defstruct BreakElt :rce_rElt )
( defstruct Text :rce_rElt :val )
( defstruct DelText :rce_rElt :val )
( defstruct InstrText :rce_rElt :val )
( defstruct DelInstrText :rce_rElt :val )
( defstruct NoBreakHyphen :rce_rElt )
( defstruct SoftHyphen :rce_rElt )
( defstruct AnnotationRef :rce_rElt )
( defstruct FootnoteRef :rce_rElt )
( defstruct EndnoteRef :rce_rElt )
( defstruct Separator :rce_rElt )
( defstruct ContinuationSeparator :rce_rElt )
( defstruct PgNum :rce_rElt )
( defstruct Cr :rce_rElt )
( defstruct Footnote :rce_rElt :n_blockLevelElts )
( defstruct Endnote :rce_rElt :n_blockLevelElts )
( defstruct NoteElt :n_blockLevelElts )
( defstruct Picture :rce_rElt )
( defstruct Symbol :rce_rElt :font :char )
( defstruct SymElt :font :char )
( defstruct Tab :rce_rElt )
( defstruct FldChar :rce_rElt :fldCharType :fldLock )
( defstruct FldCharElt :fldCharType :fldLock )
( defstruct TableElt :tblPr :tblGrid :tblContent :ble_bodyElt :ble_note :ble_tableCellElt )
( defstruct TablePrElt :tpe_tblElt )
( defstruct TableGridElt :tge_tblElt )
( defstruct TableContentElt :tce_tblElt )
( defstruct RowElt :re_tblContentElt :rowContent )
( defstruct TablePrExElt :tpee_rowElt )
( defstruct TableRowPrElt :tpe_rowElt )
( defstruct RowContentElt :rce_rowElt )
( defstruct TableCellElt :tce_rowContentElt :tce_content )
( defstruct TableCellPrElt :tcpe_tableCellElt )
( defstruct FontsListElt :fle_wordDocument )
( defstruct ListsElt :le_wordDocument )
( defstruct StylesElt :se_wordDocument )
( defstruct SectPrElt :spe_bodyElt )
( defstruct RunLevelElt :rle_tblContentElt :rle_rowContentElt :ble_bodyElt :ble_note :ble_tableCellElt )
( defstruct CfChunk :ble_bodyElt :ble_note :ble_tableCellElt )
( defstruct SimpleFieldElt :pce_pElt )
( defstruct HLinkElt :pce_pElt )
( defstruct SubDocElt :pce_pElt )
( defstruct PictureType )
( defstruct TabElt )
