( defstruct DateTimeType :year :month :day :hour :minute :second )
( defstruct ValueType :vt_data )
( defstruct StringValue :value :vt_data )
( defstruct NumberValue :value :vt_data )
( defstruct DateTimeTypeValue :value :vt_data )
( defstruct BooleanValue :value :vt_data )
( defstruct ErrorValue :vt_data )
( defstruct Workbook )
( defstruct Worksheet :ws_workbook :name )
( defstruct Table :t_worksheet )
( defstruct TableElement )
( defstruct ColOrRowElement )
( defstruct Column :c_table )
( defstruct Row :r_table )
( defstruct Cell :c_row )
( defstruct Data :d_cell :value )
