( defstruct StringProperty :val )
( defstruct StringType :val )
( defstruct WordDocument :body )
( defstruct BodyElt :be_wordDocument )
( defstruct BlockLevelElt :ble_bodyElt :ble_note )
( defstruct BlockLevelChunkElt :ble_bodyElt :ble_note )
( defstruct ParaElt :ble_bodyElt :ble_note )
( defstruct ParaContentElt :pce_pElt )
( defstruct RunElt :pce_pElt )
( defstruct RunContentElt :rce_rElt )
( defstruct BreakElt :rce_rElt )
( defstruct Text :rce_rElt :val )
( defstruct DelText :rce_rElt :val )
( defstruct InstrText :rce_rElt :val )
( defstruct DelInstrText :rce_rElt :val )
( defstruct NoBreakHyphen :rce_rElt )
( defstruct SoftHyphen :rce_rElt )
( defstruct AnnotationRef :rce_rElt )
( defstruct FootnoteRef :rce_rElt )
( defstruct EndnoteRef :rce_rElt )
( defstruct Separator :rce_rElt )
( defstruct ContinuationSeparator :rce_rElt )
( defstruct PgNum :rce_rElt )
( defstruct Cr :rce_rElt )
( defstruct Footnote :rce_rElt :n_blockLevelElts )
( defstruct Endnote :rce_rElt :n_blockLevelElts )
( defstruct NoteElt :n_blockLevelElts )
( defstruct Picture :rce_rElt )
( defstruct Symbol :rce_rElt :font :char )
( defstruct SymElt :font :char )
( defstruct Tab :rce_rElt )
( defstruct FldChar :rce_rElt :fldCharType :fldLock )
( defstruct FldCharElt :fldCharType :fldLock )
