( defstruct MetaClass )
( defstruct MetaModel )
( defstruct Module :name :mode :rules )
( defstruct Rule :isAbstract :isEntryPoint :name :module :sections )
( defstruct Inheritance :rule )
( defstruct Expression :operator :inheritance :rule :instruction )
( defstruct Section :kind :rule :instructions )
( defstruct Instruction :body :section )
( defstruct Variable :name :rule )
