( defstruct Value :type )
( defstruct Type )
( defstruct BasicValue :type )
( defstruct IntegerValue :val :type )
( defstruct RealValue :val :type )
( defstruct StringValue :val :type )
( defstruct BooleanValue :val :type )
( defstruct ObjectValue :object :type )
( defstruct Object )
( defstruct EnumValue :enumLiteral :type )
( defstruct EnumLiteral )
( defstruct UndefinedValue :type )
( defstruct CollectionValue :type )
( defstruct BagValue )
( defstruct SequenceValue )
( defstruct SetValue )
( defstruct Count :num )
