( defstruct OclExpression :resultType :varDec )
( defstruct SelfExp :resultType :varDec )
( defstruct ResultExp :resultType :varDec )
( defstruct VariableExp :var :resultType :varDec )
( defstruct OperationExp :resultType :varDec )
( defstruct QueryExp :argument :source :resultType :varDec )
( defstruct Type )
( defstruct VariableDeclaration :var :varType )
( defstruct VariableInitialisation :initExpression :varDec :iterateExp )
( defstruct ForAllExp )
( defstruct ExistsExp )
( defstruct SelectExp )
( defstruct RejectExp )
( defstruct CollectExp )
( defstruct IterateExp :varInit )
