( defstruct InvariantSchema )
( defstruct InformationObjectTemplate )
( defstruct InformationObjectType )
( defstruct InformationObject :IO_S )
( defstruct State :change :causeSC :S_IO )
( defstruct StateChange :startState :endState :specifier )
( defstruct DynamicSchema )
( defstruct StaticSchema :locationTime :SS_IO )
( defstruct Action )
( defstruct ActionType )
( defstruct ActionTemplate )
