( defstruct OWLOntology :owlGraph :owlStatement :type )
( defstruct OWLGraph :owlStatement :statement :type )
( defstruct OWLStatement :owlGraph :reificationKind :graph :RDFobject :RDFsubject :document :type )
( defstruct OWLUniverse :ontology :type )
( defstruct OWLClass :type :ontology :type )
( defstruct IntersectionClass :type :ontology :type )
( defstruct UnionClass :type :ontology :type )
( defstruct ComplementClass :type :ontology :type )
( defstruct EnumeratedClass :type :ontology :type )
( defstruct OWLRestriction :OWLOnProperty :type :ontology :type )
( defstruct HasValueRestriction :OWLOnProperty :type :ontology :type )
( defstruct AllValuesFromRestriction :OWLOnProperty :type :ontology :type )
( defstruct SomeValuesFromRestriction :OWLOnProperty :type :ontology :type )
( defstruct CardinalityRestriction :OWLCardinality :OWLOnProperty :type :ontology :type )
( defstruct MaxCardinalityRestriction :OWLMaxCardinality :OWLOnProperty :type :ontology :type )
( defstruct MinCardinalityRestriction :OWLMinCardinality :OWLOnProperty :type :ontology :type )
( defstruct OWLAnnotationProperty :type :ontology :type )
( defstruct OWLOntologyProperty :type :ontology :type )
( defstruct Property :type :ontology :type )
( defstruct FunctionalProperty :type :ontology :type )
( defstruct OWLDatatypeProperty :type :ontology :type )
( defstruct OWLObjectProperty :type :ontology :type )
( defstruct InverseFunctionalProperty :type :ontology :type )
( defstruct SymmetricProperty :type :ontology :type )
( defstruct TransitiveProperty :type :ontology :type )
( defstruct Individual :type :ontology :type )
( defstruct OWLAllDifferent :OWLDistinctMembers :type :ontology :type )
( defstruct OWLDataRange :type :ontology :type )
( defstruct Document :statement :type )
( defstruct LocalName :name :document )
( defstruct Namespace :document :namespaceURIRef )
( defstruct NamespaceDefinition :namespacePrefix :document :namespace )
( defstruct RDFSResource :type )
( defstruct RDFGraph :statement :type )
( defstruct List :type )
( defstruct Container :type )
( defstruct Alt :type )
( defstruct Bag :type )
( defstruct Seq :type )
( defstruct RDFProperty :type )
( defstruct ContainerMembershipProperty )
( defstruct RDFStatement :reificationKind :graph :RDFobject :RDFsubject :document :type )
( defstruct URIReferenceNode :type )
( defstruct BlankNode :type )
( defstruct RDFSClass :type )
( defstruct RDFSDataType :type )
( defstruct RDFSLiteral :lexicalForm :type )
( defstruct PlainLiteral :labeledResource :commentedResource :lexicalForm :type )
( defstruct TypedLiteral :datatypeURI :lexicalForm :type )
( defstruct XMLLiteral :datatypeURI :lexicalForm :type )
( defstruct URIReference )
( defstruct UniformResourceIdentifier :name )
