( defstruct Program :name )
( defstruct Variable :name :program :procedure :type )
( defstruct Type :name :program )
( defstruct Parameter :procedure_parameter :name :program :procedure :type )
( defstruct Instruction :block )
( defstruct Calculation :block )
( defstruct Control :block )
( defstruct Assignment :block )
( defstruct Block :procedure :loop :conditional :block )
( defstruct Conditional :blocks :block )
( defstruct Loop :block_loop :block )
( defstruct Procedure :name :program :block_procedure :block )
( defstruct Function :returnType :name :program :block_procedure :block )
( defstruct For :block_loop :block )
( defstruct While :block_loop :block )
( defstruct Repeat :block_loop :block )
