( defstruct FIPA-Platform Agent :agent )
( defstruct FIPA-platform Task :fipa_platform_Agent :task )
( defstruct Service )
( defstruct Agent :Name :Knowledge :fipa_platform_AgentA :role :requirement )
( defstruct Role :agentR :task :scenario )
( defstruct Task :Name :fipa_platform_TaskT )
( defstruct Communication :Name :Exchanged Knowledge :message :aip )
( defstruct Message :communication :Comm_Act )
( defstruct AIP :Name :performative )
( defstruct Performative :aip )
( defstruct Ressource :Name )
( defstruct Non functionnal Requirement )
( defstruct Requirement )
( defstruct Scenario )
( defstruct Ontology )
( defstruct Concept )
( defstruct Action )
( defstruct Predicate )
