( defstruct RelationSchip :associatePackages )
( defstruct ConstrainedRelationSchip )
( defstruct Aggregation :associatePackages )
( defstruct Composition :associatePackages )
( defstruct Association :associatePackages )
( defstruct Generalisation :associatePackages )
( defstruct Dependency :associatePackages )
( defstruct AssociationEnd )
( defstruct Package :parent )
( defstruct Steriotype )
( defstruct Class :operations )
( defstruct Constraint :caracteristic :theClass )
( defstruct Operation :inCharacteristic :behaviour )
( defstruct Characteristic :operations :theClass :relationSchip )
( defstruct BusnissRule :characteristic )
( defstruct MetaData :characteristic :operations :theClass )
( defstruct Source :metaData )
( defstruct Domain :descriptiveAttribute )
( defstruct DescriptiveAttribute :operations :theClass :relationSchip )
( defstruct Geometry :descriptiveAttributeg :operations :theClass :relationSchip )
( defstruct Temporality :descriptiveAttributet :operations :theClass :relationSchip )
( defstruct VisualInfo :operations :theClass :relationSchip )
( defstruct Value :enumeratedDomain )
( defstruct RangeDomain :descriptiveAttribute )
( defstruct EnumeratedDomain :value :descriptiveAttribute )
( defstruct PerceptorySteriotype )
