( defstruct LocatedElement :location )
( defstruct NamedElement :name :location )
( defstruct PetriNet :name :location )
( defstruct Element :net :name :location )
( defstruct Place :net :name :location )
( defstruct Transition :incomingArc :outgoingArc :net :name :location )
( defstruct Arc :weight :net :name :location )
( defstruct PlaceToTransition :from :to :weight :net :name :location )
( defstruct TransitionToPlace :from :to :weight :net :name :location )
( defstruct Execution :net )
( defstruct Token :placedAt :marking )
( defstruct Marking :exec )
( defstruct Movement :exec :fire :source :target )
