( defstruct LocatedElement )
( defstruct Eclipse :bundles )
( defstruct Bundle :symbolicName :singleton :manifestVersion :version )
( defstruct RequireBundleAttribute )
( defstruct AttResolution :value )
( defstruct AttVisibility :value )
( defstruct Range :isLeftInclusive :isRightInclusive :lowerBound :upperBound )
( defstruct Version :major :minor :micro :qualification )
( defstruct RequiredBundle :bundle )
( defstruct ImportedPackage :resolution :package )
( defstruct ExportedPackage :package :version :xFriends )
( defstruct Package :fqn )
( defstruct Xfriends :bundles )
( defstruct Xinternal :value :package :version :xFriends )
