( defstruct Element :location )
( defstruct NamedElement :name :location )
( defstruct RuleSet :location )
( defstruct Rule :name :location )
( defstruct RuleAction :location )
( defstruct RuleCondition :location )
( defstruct Binding :bindingOwner :location )
( defstruct RuleVariable :ruleVariableOwner :type :varName :location )
( defstruct DeleteAction :objValue :location )
( defstruct CreateAction :location :type :varName :location )
( defstruct AssignAction :objValue :aValue :location )
( defstruct InvokeAction :invocation :location )
( defstruct PropertyCallExp :type :location )
( defstruct OclExpression :type :location )
( defstruct IteratorExp :name :body :iterators :type :location )
( defstruct LoopExp :body :iterators :type :location )
( defstruct OperatorCallExp :operationName :type :location )
( defstruct OperationCallExp :operationName :type :location )
( defstruct CollectionOperationCallExp :operationName :type :location )
( defstruct StringExp :stringSymbol :type :location )
( defstruct BooleanExp :booleanSymbol :type :location )
( defstruct NumericExp :type :location )
( defstruct IntegerExp :integerSymbol :type :location )
( defstruct RealExp :realSymbol :type :location )
( defstruct PrimitiveExp :type :location )
( defstruct NavigationOrAttributeCallExp :name :type :location )
( defstruct Iterator :type :varName :location )
( defstruct VariableDeclaration :type :varName :location )
( defstruct VariableExp :referredVariable :type :location )
( defstruct TypeExp :type :location )
( defstruct AllInstanceExp :sourceType :type :location )
( defstruct OclType :name :location )
( defstruct StringType :name :location )
( defstruct Primitive :name :location )
( defstruct RealType :name :location )
( defstruct BooleanType :name :location )
( defstruct NumericType :name :location )
( defstruct IntegerType :name :location )
