( defstruct QoSComponent :operations )
( defstruct QoSProfile :for :provide :uses )
( defstruct QoSContraints :invariant :parallel_and_composition :parallel_or_composition :sequential_composition :values :parameter :domain )
( defstruct Operation )
( defstruct CompoundProfile :simpleProfile :for :provide :uses )
( defstruct SimpleProfile :compoundProfile :use :provides :for :provide :uses )
( defstruct ProfileTransition :from :to :compoundProfile )
( defstruct QoSStatement :contraints :relation )
( defstruct SingleQoSStatement :contraint :contraints :relation )
( defstruct CoumpoundQoSStatement :statement :contraints :relation )
( defstruct QoSContraint :qualification )
( defstruct QualificationKind :value :invariant :parallel_and_composition :parallel_or_composition :sequential_composition :values :parameter :domain )
( defstruct QoSCharacteristic :invariant :parallel_and_composition :parallel_or_composition :sequential_composition :values :parameter :domain )
( defstruct BooleanExpression :value )
( defstruct MappingExpression :value )
( defstruct StatisticalAttributekindKind )
( defstruct Parameter )
( defstruct DataType )
( defstruct Domain :direction )
( defstruct DirectionKind :value )
( defstruct Numeric :direction )
( defstruct Set :stringSet :direction )
( defstruct Enumeration :direction )
( defstruct StringSet :string )
