( defstruct QoSCharacteristic :invariant :parallel_and_composition :parallel_or_composition :sequential_composition :values :parameter :domain )
( defstruct BooleanExpression :value )
( defstruct MappingExpression :value )
( defstruct StatisticalAttributekindKind )
( defstruct Parameter )
( defstruct DataType )
( defstruct Domain :direction )
( defstruct DirectionKind :value )
( defstruct Numeric :direction )
( defstruct Set :stringSet :direction )
( defstruct Enumeration :direction )
( defstruct StringSet :string )
