( defstruct Resource :graph :type )
( defstruct Graph :graph :type )
( defstruct List :graph :type )
( defstruct Container :graph :type )
( defstruct Alt :graph :type )
( defstruct Bag :graph :type )
( defstruct Seq :graph :type )
( defstruct Property :graph :type )
( defstruct ContainerMembershipProperty )
( defstruct Statement :object :subject :isReifiedOnly :isReified :graph :type )
( defstruct URIReferenceNode :graph :type )
( defstruct BlankNode :graph :type )
( defstruct Class :graph :type )
( defstruct Datatype :graph :type )
( defstruct Literal :lexicalForm :graph :type )
( defstruct PlainLiteral :labeledResource :lexicalForm :graph :type )
( defstruct TypedLiteral :datatypeURI :lexicalForm :graph :type )
( defstruct RDFXMLLiteral :datatypeURI :lexicalForm :graph :type )
( defstruct URIReference )
( defstruct UniformResourceIdentifier :name )
