( defstruct Project :documents )
( defstruct TypedElement :type )
( defstruct ElementWithIL :name :label :type )
( defstruct Document :project :name :label :type )
( defstruct TextElement :description :name :label :type )
( defstruct Section :description :name :label :type )
( defstruct AbstractRequirement :description :name :label :type )
( defstruct Requirement :description :name :label :type )
( defstruct MacroRequirement :description :name :label :type )
( defstruct CoverLink :linkWith :type )
( defstruct Attribute :value :type )
