( defstruct LocatedElement )
( defstruct Root )
( defstruct VocabularyEntry :primaryRep )
( defstruct Caption )
( defstruct DefCaption :definition )
( defstruct DescCaption :description )
( defstruct SrcCaption :source )
( defstruct DBCaption :dictionaryBasis )
( defstruct GenCCaption :generalConcept )
( defstruct CTypCaption )
( defstruct Necessity :exp )
( defstruct Possibility :exp )
( defstruct RefSCaption :referenceScheme )
( defstruct NoteCaption :note )
( defstruct ExCaption )
( defstruct SynCaption )
( defstruct SynFCaption )
( defstruct SeeCaption )
( defstruct SFCaption )
( defstruct NSURICaption )
( defstruct PrimaryRepresentation )
( defstruct NotFactTypeRepresentation )
( defstruct TermRepresentation :term )
( defstruct NameRepresentation :hasThe :name )
( defstruct FactTypeFormRepresentation :primaryRep1 :verbExp :primaryRep2 )
( defstruct ConceptDefinition :exp )
( defstruct ConceptSource :source )
( defstruct Note :sentences )
( defstruct Sentence :words )
( defstruct NameSpaceURI :URI )
( defstruct Word :val )
( defstruct StringWord :val )
( defstruct QuotedStringWord :val )
( defstruct NameWord :val )
( defstruct SBVRExpression :hasPoint :firstProposition )
( defstruct SBVRPropWithKW :conjonction :endConj :proposition )
( defstruct ModalForm :modal :isNeg )
( defstruct SimpleSBVRProp :concept1 :verbs :concept2 )
( defstruct SubSBVRProp :join :verbs :concept2 )
( defstruct LinkSBVRConcept :link :concept )
( defstruct ConjConcept :conjonction :concept )
( defstruct Concept )
( defstruct NameConcept :name )
( defstruct ObjectConcept :operatoredConcept )
( defstruct StringConcept :stringWord )
( defstruct NounConcept :noun )
( defstruct Qualification :generalConcept )
( defstruct GeneralConcept )
( defstruct NameGConcept :name )
( defstruct NounGConcept :noun )
( defstruct Qualifier :op :endOperator )
( defstruct ModalBegin :endOperator )
( defstruct ModalBeginC :endOperator )
