( defstruct Man :language :title :type :date )
( defstruct Meta :meta :path :category :version_CSI :version_DOC :author :man )
( defstruct Short_Description :name )
( defstruct Calling_Sequence )
( defstruct Calling_Sequence_Item :calling_Sequence )
( defstruct Param )
( defstruct Param_Indent :param :param_Description :param_Item )
( defstruct Param_Item :param_Indent :param_Name :param_Description )
( defstruct Param_Name :param_Item )
( defstruct Param_Description :param_Item )
( defstruct Description )
( defstruct Description_Indent :description :description_Item )
( defstruct Description_Item :description_Indent )
( defstruct AIMG )
( defstruct See_Also )
( defstruct Exemple :exemple :xml_space )
( defstruct See_Also_Item :see_Also )
( defstruct A :psppp :authors_Item )
( defstruct Img :psppp )
( defstruct Biblio )
( defstruct Used_Functions )
( defstruct PSPPP )
( defstruct P :biblio )
( defstruct SP :biblio )
( defstruct PP :biblio )
( defstruct Itemize :label :item :section :authors_Item :description )
( defstruct Item :label :item :section :authors_Item :description )
( defstruct Table :table_New_Row :used_Functions )
( defstruct Table_New_Row :table_New_Column :table )
( defstruct Table_New_Column :table_New_Row )
( defstruct Link :link :psppp :see_Also_Item :authors_Item )
( defstruct Authors :authors_Item )
( defstruct Authors_Item :authors :itemize )
( defstruct Section :label :item :section :authors_Item :description )
