( defstruct SystemDefinitionModel :namespaceIdentity )
( defstruct Information :sdm )
( defstruct Import :sdm :alias :identity )
( defstruct ImportNamespaceIdentity :import :name )
( defstruct SDMCommunicationDefinition :sdm :clientDefinition :serverDefinition :extends :name )
( defstruct SDMContainmentDefinition :sdm :parentDefinition :memberDefinition :extends :name )
( defstruct SDMDelegationDefinition :sdm :proxyDefinition :delegateDefinition :extends :name )
( defstruct SDMReferenceDefinition :sdm :dependentDefinition :sourceDefinition :extends :name )
( defstruct SDMEndpointDefinition :sdm :name )
( defstruct SDMResourceDefinition :sdm :name )
( defstruct SDMSystemDefinition :sdm :name )
( defstruct SDMConstraintDefinition :sdm :name )
( defstruct SDMManager :sdm :assemblyName )
( defstruct ManagerDeclaration :assemblyName )
( defstruct ObjectDefinition :name )
( defstruct OBFlow :objectDefinition :designData :name :definition )
( defstruct OBRelationshipConstraint :objectDefinition :relationshipDefinition :targetRole :name )
( defstruct OBConstraint :objectDefinition :designData :name :definition )
( defstruct OBConstraintGroup :objectDefinition :name )
( defstruct OBEndpointDefinition :objectDefinition :name )
( defstruct OBSystemDefinition :objectDefinition :name )
( defstruct OBResourceDefinition :objectDefinition :name )
( defstruct OBCommunicationDefinition :objectDefinition :clientDefinition :serverDefinition :extends :name )
( defstruct OBContainmentDefinition :objectDefinition :parentDefinition :memberDefinition :extends :name )
( defstruct OBDelegationDefinition :objectDefinition :proxyDefinition :delegateDefinition :extends :name )
( defstruct OBReferenceDefinition :objectDefinition :dependentDefinition :sourceDefinition :extends :name )
( defstruct OBHostingDefinition :objectDefinition :guestDefinition :hostDefinition :simulationRoot :extends :name )
( defstruct OBEndpoint :objectDefinition :reference :designData :name :definition )
( defstruct OBSubsystem :objectDefinition :reference :designData :name :definition )
( defstruct OBResource :objectDefinition :reference :designData :name :definition )
( defstruct OBHosting :objectDefinition :guestMember :hostMember :designData :name :definition )
( defstruct OBContainment :objectDefinition :childMember :designData :name :definition )
( defstruct OBConnection :objectDefinition :clientMember :serverMember :designData :name :definition )
( defstruct OBDelegation :objectDefinition :proxyMember :delegateMember :designData :name :definition )
( defstruct OBReference :objectDefinition :dependentMember :sourceMember :designData :name :definition )
( defstruct SystemDefinition :name )
( defstruct EndpointDefinition :name )
( defstruct ResourceDefinition :name )
( defstruct RelationshipDefinition :extends :name )
( defstruct RDObjectConstraint :relationshipDefinition :primaryRole :primaryObjectDefinition :name )
( defstruct RDConstraint :relationshipDefinition :designData :name :definition )
( defstruct RDConstraintGroup :relationshipDefinition :name )
( defstruct RDFlow :relationshipDefinition :designData :name :definition )
( defstruct RDConnection :relationshipDefinition :clientMember :serverMember :designData :name :definition )
( defstruct RDHosting :relationshipDefinition :guestMember :hostMember :designData :name :definition )
( defstruct RDDelegation :relationshipDefinition :proxyMember :delegateMember :designData :name :definition )
( defstruct RDReference :relationshipDefinition :dependentMember :sourceMember :designData :name :definition )
( defstruct RDContainment :relationshipDefinition :childMember :designData :name :definition )
( defstruct CommunicationDefinition :clientDefinition :serverDefinition :extends :name )
( defstruct HostingDefinition :guestDefinition :hostDefinition :simulationRoot :extends :name )
( defstruct ContainmentDefinition :parentDefinition :memberDefinition :extends :name )
( defstruct DelegationDefinition :proxyDefinition :delegateDefinition :extends :name )
( defstruct ReferenceDefinition :dependentDefinition :sourceDefinition :extends :name )
( defstruct Member :designData :name :definition )
( defstruct MembSettingValue :member :settingValueAttributes )
( defstruct MembSettingValueList :member :settingValueAttributes )
( defstruct ObjectMember :reference :designData :name :definition )
( defstruct RelationshipMember :designData :name :definition )
( defstruct SystemMember :reference :designData :name :definition )
( defstruct EndpointMember :reference :designData :name :definition )
( defstruct ResourceMember :reference :designData :name :definition )
( defstruct HostingMember :guestMember :hostMember :designData :name :definition )
( defstruct CommunicationMember :clientMember :serverMember :designData :name :definition )
( defstruct ContainmentMember :childMember :designData :name :definition )
( defstruct DelegationMember :proxyMember :delegateMember :designData :name :definition )
( defstruct ReferenceMember :dependentMember :sourceMember :designData :name :definition )
( defstruct DesignData )
( defstruct NameSpace :designData :value )
( defstruct ObjectConstraint :primaryRole :primaryObjectDefinition :name )
( defstruct OCConstraint :objectConstraint :designData :name :definition )
( defstruct OCRelationshipConstraint :objectConstraint_OC :relationshipDefinition :targetRole :name )
( defstruct OCConstraintGroup :objectConstraint_OC :name )
( defstruct RelationshipConstraint :relationshipDefinition :targetRole :name )
( defstruct RCConstraint :relationshipConstraint :designData :name :definition )
( defstruct RCRelationshipConstraint :relationshipConstraint_RC :relationshipDefinition :targetRole :name )
( defstruct RCObjectConstraint :relationshipConstraint_RC :primaryRole :primaryObjectDefinition :name )
( defstruct RCConstraintGroup :relationshipConstraint_RC :name )
( defstruct ConstraintGroup :name )
( defstruct CGConstraint :constraintGroup :designData :name :definition )
( defstruct CGRelationshipConstraint :constraintGroup_CG :relationshipDefinition :targetRole :name )
( defstruct CGObjectConstraint :constraintGroup_CG :primaryRole :primaryObjectDefinition :name )
( defstruct StructuralConstraint :name )
( defstruct ConstraintDefinition :name )
( defstruct CDRelationshipConstraint :constraintDefinition :relationshipDefinition :targetRole :name )
( defstruct CDConstraintGroup :constraintDefinition :name )
( defstruct CDObjectConstraint :constraintDefinition :primaryRole :primaryObjectDefinition :name )
( defstruct CDConstraint :constraintDefinition :designData :name :definition )
( defstruct ConstraintMember :designData :name :definition )
( defstruct Definition :name )
( defstruct DefSettingDeclaration :definition_DSD :settingAttributes :designData :name :definition )
( defstruct DefSettingValue :definition :settingValueAttributes )
( defstruct DefSettingValueList :definition :settingValueAttributes )
( defstruct SimpleName :value )
( defstruct QualifiedName :value )
( defstruct Path :value )
( defstruct SettingPath :value )
( defstruct NamespaceIdentity :name )
( defstruct FlowDefinition :name )
( defstruct FlowMember :designData :name :definition )
( defstruct ValueTransfer :name :path )
( defstruct Output :name :path )
( defstruct Input :name :path )
( defstruct SettingDefinitions :manager :clrNameSpace )
( defstruct SettingMember :settingAttributes :designData :name :definition )
( defstruct SettingsAttributes :list :access :secure :deploymentTime :required :canBeNull :elementsCanBeNull :defaultRead :defaultWrite )
( defstruct Facet :name )
( defstruct SettingValue :settingValueAttributes )
( defstruct SettingValueList :settingValueAttributes )
( defstruct Value :null )
( defstruct SettingValueAttributes :path )
( defstruct Description )
( defstruct Entry :description :name )
( defstruct DescriptionEntry :name )
( defstruct Substitute )
( defstruct PathList )
( defstruct MaxOccurs :value )
( defstruct MinOccurs :value )
( defstruct FourPartVersionType :value )
( defstruct PublicKeyType :value )
( defstruct PublicKeyTokenType :value )
( defstruct CompilationHashType :value )
( defstruct Culture :value )
( defstruct CultureNeutral :value )
( defstruct Element :value )
