( defstruct Group :group )
( defstruct User :group )
( defstruct Subject :group )
( defstruct Role )
( defstruct Permission :actionAssignment )
( defstruct AuthorizationConstraint )
( defstruct AtomicAction :resource )
( defstruct CompositeAction :resource )
( defstruct Action :resource )
( defstruct Resource )
