( defstruct LogFile :file :instance :logger )
( defstruct Logger :instance :expression :logFile )
( defstruct Expression :loggingOn :logger )
( defstruct Literal :value :loggingOn :logger )
( defstruct VariableExpression :name :value :loggingOn :logger )
( defstruct NumberExpression :value :loggingOn :logger )
( defstruct UnaryOperator :operand :loggingOn :logger )
( defstruct UnaryPlusOp :operand :loggingOn :logger )
( defstruct UnaryMinusOp :operand :loggingOn :logger )
( defstruct BinaryOperator :operand1 :operand2 :loggingOn :logger )
( defstruct PlusOperator :operand1 :operand2 :loggingOn :logger )
( defstruct MinusOperator :operand1 :operand2 :loggingOn :logger )
