( defstruct ModelElement :name )
( defstruct Classifier :name )
( defstruct Operation :name )
( defstruct Service :name )
( defstruct BusinessObject :name )
( defstruct ServiceOperation :name )
( defstruct BusinessObjectOperation :name )
( defstruct BusinessRule :expr :name )
( defstruct Flow :source :target :name )
( defstruct Service2BusinessObjectFlow :source :target :name )
