( defstruct RootFolder )
( defstruct CompoundComponent :rootFolder :name :compoundComponent )
( defstruct PrimitiveComponent :name :compoundComponent )
( defstruct BaseComponent :name :compoundComponent )
( defstruct InputPort :baseComponent :name :associationPortBase_PortBasesrc :associationPortBase_PortBasedst )
( defstruct LocalPort :compoundComponent :name :associationPortBase_PortBasesrc :associationPortBase_PortBasedst )
( defstruct OutputPort :baseComponent :name :associationPortBase_PortBasesrc :associationPortBase_PortBasedst )
( defstruct PortBase :name :associationPortBase_PortBasesrc :associationPortBase_PortBasedst )
( defstruct Signal :name :baseComponent :associationPortBase_PortBase )
( defstruct AssociationPortBase_PortBase :srcPortBase :dstPortBase :signal )
