( defstruct Root )
( defstruct Element :objectName )
( defstruct Representation :meaning :objectName )
( defstruct Designation :text :meaning :objectName )
( defstruct Text :value :objectName )
( defstruct Meaning :objectName )
( defstruct Concept :objectName )
( defstruct NounConcept :objectName )
( defstruct ObjectType :objectName )
( defstruct IndividualConcept :objectName )
( defstruct DataType :objectName )
( defstruct NonEmptyString :value :objectName )
( defstruct NonNegativeInteger :value :objectName )
( defstruct FactType :objectName )
( defstruct BinaryFactType :role1 :role2 :objectName )
( defstruct IsPropertyOfFactType :role1 :role2 :objectName )
( defstruct AssociativeFactType :role1 :role2 :objectName )
( defstruct CategorizationFactType :role1 :role2 :objectName )
( defstruct ObjectificationFactType :role1 :role2 :objectName )
( defstruct Role :nounConcept :objectName )
( defstruct FactTypeRole :nounConcept :objectName )
( defstruct LogicalFormulation :objectName )
( defstruct AtomicFormulation :isBasedOn :objectName )
( defstruct BinaryAtomicFormulation :roleBinding1 :roleBinding2 :isBasedOn :objectName )
( defstruct NecessityFormulation :objectName )
( defstruct Quantification :introducedVariable :scopesOver :objectName )
( defstruct UniversalQuantification :introducedVariable :scopesOver :objectName )
( defstruct AtLeastNQuantification :minCardinality :introducedVariable :scopesOver :objectName )
( defstruct ExactlyNQuantification :cardinality :introducedVariable :scopesOver :objectName )
( defstruct AtMostNQuantification :maxCardinality :introducedVariable :scopesOver :objectName )
( defstruct BindableTarget :objectName )
( defstruct Variable :rangesOver :objectName )
( defstruct RoleBinding :occursIn :isOf :bindsTo :objectName )
