( defstruct LocatedElement :location )
( defstruct Program :service :location )
( defstruct Service :name :location )
( defstruct Session :location )
( defstruct Registration :location )
( defstruct Dialog :methods :location )
( defstruct Event :eventId :methods :location )
( defstruct Method :type :direction :methodName :statements :branches :location )
( defstruct Argument :type :name :location )
( defstruct MethodName :location )
( defstruct SIPMethodName :name :location )
( defstruct ControlMethodName :name :location )
( defstruct Branch :statements :location )
( defstruct DefaultBranch :statements :location )
( defstruct NamedBranch :name :statements :location )
( defstruct TypeExpression :location )
( defstruct SimpleType :type :location )
( defstruct SequenceType :type :location )
( defstruct DefinedType :typeName :location )
( defstruct Declaration :name :location )
( defstruct VariableDeclaration :type :name :location )
( defstruct FunctionDeclaration :returnType :name :location )
( defstruct RemoteFunctionDeclaration :functionLocation :returnType :name :location )
( defstruct LocalFunctionDeclaration :statements :returnType :name :location )
( defstruct StructureDeclaration :properties :name :location )
( defstruct StructureProperty :name :type :location )
( defstruct FunctionCall :function :location )
( defstruct Statement :location )
( defstruct CompoundStat :statements :location )
( defstruct SetStat :target :setValue :location )
( defstruct DeclarationStat :declaration :location )
( defstruct ReturnStat :location )
( defstruct IfStat :condition :thenStatements :location )
( defstruct WhenStat :idExp :whenHeaders :statements :location )
( defstruct ForeachStat :iteratorName :sequenceExp :statements :location )
( defstruct SelectStat :matchedExp :location )
( defstruct FunctionCallStat :functionCall :location )
( defstruct ContinueStat :location )
( defstruct BreakStat :location )
( defstruct PushStat :target :pushedValue :location )
( defstruct WhenHeader :headerId :type :name :location )
( defstruct SelectMember :location )
( defstruct SelectDefault :location )
( defstruct SelectCase :values :location )
( defstruct Expression :location )
( defstruct ConstantExp :value :location )
( defstruct OperatorExp :opName :leftExp :location )
( defstruct ForwardExp :isParallel :location )
( defstruct WithExp :exp :msgFields :location )
( defstruct BlockExp :exp :location )
( defstruct ReasonExp :location )
( defstruct BODYExp :location )
( defstruct RequestURIExp :location )
( defstruct PopExp :source :location )
( defstruct FunctionCallExp :functionCall :location )
( defstruct Place :location )
( defstruct SIPHeaderPlace :header :location )
( defstruct VariablePlace :location )
( defstruct PropertyCallPlace :propName :source :location )
( defstruct Variable :source :location )
( defstruct MessageField :exp :location )
( defstruct ReasonMessageField :exp :location )
( defstruct HeadedMessageField :headerId :exp :location )
( defstruct Constant :location )
( defstruct BooleanConstant :value :location )
( defstruct IntegerConstant :value :location )
( defstruct StringConstant :value :location )
( defstruct URIConstant :uri :location )
( defstruct SequenceConstant :location )
( defstruct ResponseConstant :response :location )
( defstruct Response :location )
( defstruct SuccessResponse :successKind :location )
( defstruct ErrorResponse :location )
( defstruct ClientErrorResponse :location )
( defstruct GlobalErrorResponse :location )
( defstruct RedirectionErrorResponse :location )
( defstruct ServerErrorResponse :location )
