( defstruct LocatedElement :location )
( defstruct NamedElement :name :location )
( defstruct Database :name :location )
( defstruct Table :database :name :location )
( defstruct TableElement :table :location )
( defstruct Column :name :type :canBeNull :table :location )
( defstruct Key :isUnique :columns :table :location )
( defstruct SimpleKey :isUnique :columns :table :location )
( defstruct PrimaryKey :isUnique :columns :table :location )
( defstruct ForeignKey :referencedTable :referencedColumns :isUnique :columns :table :location )
( defstruct Type :isUnsigned :name :location )
( defstruct Parameter :table :name :location )
( defstruct Value :location )
( defstruct IntegerVal :value :location )
( defstruct NullVal :location )
( defstruct StringVal :value :location )
