( defstruct Element )
( defstruct StructuralElement )
( defstruct Image )
( defstruct Svg )
( defstruct GroupingElement )
( defstruct G )
( defstruct Defs )
( defstruct Symbol )
( defstruct Use )
( defstruct GraphicalElement )
( defstruct Shape )
( defstruct TextElement )
( defstruct Rect )
( defstruct Circle )
( defstruct Ellipse )
( defstruct Line :between )
( defstruct Polyline )
( defstruct Polygon )
( defstruct Path :d )
( defstruct Point )
( defstruct Marker )
( defstruct Text :content )
( defstruct Tspan )
( defstruct Tref :xlinkHref )
( defstruct Attribute )
( defstruct Transform )
( defstruct Scale :sx :sy )
( defstruct Translate :tx :ty )
( defstruct Rotate :angle :cx :cy )
( defstruct Visibility :visible )
( defstruct FontWeight :bold )
( defstruct FontStyle :italic )
( defstruct Dimension :width :height )
( defstruct Coordinates :x :y )
( defstruct RelativeCoord :x :y )
( defstruct AbsoluteCoord :x :y )
( defstruct ReferencedFile :name )
( defstruct SvgFile :tag :name )
