( defstruct Bibliography )
( defstruct Publication :title :abstract :keywords :note :year )
( defstruct Article :author :journal :month :number :pages :volume :title :abstract :keywords :note :year )
( defstruct Book :month :number :volume :series :source :address :edition :isbn :price :editor :publisher :author :title :abstract :keywords :note :year )
( defstruct InBook :author :publisher :editor :month :number :pages :volume :series :chapter :type :address :title :abstract :keywords :note :year )
( defstruct Booklet :author :month :address :edition :howpublished :title :abstract :keywords :note :year )
( defstruct InCollection :editor :author :publisher :month :number :pages :address :edition :volume :series :chapter :type :booktitle :title :abstract :keywords :note :year )
( defstruct InProceedings :editor :author :month :number :pages :address :volume :series :booktitle :organization :publisher :title :abstract :keywords :note :year )
( defstruct Proceedings :editor :publisher :organization :month :number :volume :address :series :title :abstract :keywords :note :year )
( defstruct Manual :author :organization :month :address :edition :title :abstract :keywords :note :year )
( defstruct Misc :month :howpublished :title :abstract :keywords :note :year )
( defstruct Unpublished :author :month :title :abstract :keywords :note :year )
( defstruct Thesis :author :school :month :address :type :title :abstract :keywords :note :year )
( defstruct MasterThesis :author :school :month :address :type :title :abstract :keywords :note :year )
( defstruct PhDThesis :author :school :month :address :type :title :abstract :keywords :note :year )
( defstruct Report :title :abstract :keywords :note :year )
( defstruct ProjectReport :describesProject :title :abstract :keywords :note :year )
( defstruct TechnicalReport :series :organization :title :abstract :keywords :note :year )
( defstruct Event :name :date :eventTitle :location :atEvent :hasPartEvent )
( defstruct Conference :series :name :date :eventTitle :location :atEvent :hasPartEvent )
( defstruct Workshop :series :name :date :eventTitle :location :atEvent :hasPartEvent )
( defstruct Exhibition :name :date :eventTitle :location :atEvent :hasPartEvent )
( defstruct Lecture :givenBy :name :date :eventTitle :location :atEvent :hasPartEvent )
( defstruct Meeting :title :name :date :eventTitle :location :atEvent :hasPartEvent )
( defstruct ProjectMeeting :title :name :date :eventTitle :location :atEvent :hasPartEvent )
( defstruct Person :address :name :email :fax :homepage :phone :photo )
( defstruct Employee :affiliation :address :name :email :fax :homepage :phone :photo )
( defstruct Manager :affiliation :address :name :email :fax :homepage :phone :photo )
( defstruct AdministrativeStaff :affiliation :address :name :email :fax :homepage :phone :photo )
( defstruct TechnicalStaff :affiliation :address :name :email :fax :homepage :phone :photo )
( defstruct AcademicStaff :editor :headOf :headOfGroup :memberOfPC :organizerOrChairOf :worksAtProject :address :name :email :fax :homepage :phone :photo )
( defstruct Lecturer :editor :headOf :headOfGroup :memberOfPC :organizerOrChairOf :worksAtProject :address :name :email :fax :homepage :phone :photo )
( defstruct FacultyMember :editor :headOf :headOfGroup :memberOfPC :organizerOrChairOf :worksAtProject :address :name :email :fax :homepage :phone :photo )
( defstruct FullProfessor :editor :headOf :headOfGroup :memberOfPC :organizerOrChairOf :worksAtProject :address :name :email :fax :homepage :phone :photo )
( defstruct AssistantProfessor :editor :headOf :headOfGroup :memberOfPC :organizerOrChairOf :worksAtProject :address :name :email :fax :homepage :phone :photo )
( defstruct AssociateProfessor :editor :headOf :headOfGroup :memberOfPC :organizerOrChairOf :worksAtProject :address :name :email :fax :homepage :phone :photo )
( defstruct Student :studiesAt :address :name :email :fax :homepage :phone :photo )
( defstruct Undergraduate :studiesAt :address :name :email :fax :homepage :phone :photo )
( defstruct Graduate :studiesAt :address :name :email :fax :homepage :phone :photo )
( defstruct PhDStudent :worksAtProject :supervisor :studiesAt :address :name :email :fax :homepage :phone :photo )
( defstruct Organization :location :name )
( defstruct ResearchGroup :head :location :name )
( defstruct Association :location :name )
( defstruct Department :hasParts :location :name )
( defstruct Institute :cooperateWith :location :name )
( defstruct Enterprise :location :name )
( defstruct University :location :name )
( defstruct Project :name :carriedOutBy :financedBy :head :isAbout )
( defstruct ResearchProject :name :carriedOutBy :financedBy :head :isAbout )
( defstruct DevelopmentProject :name :carriedOutBy :financedBy :head :isAbout )
( defstruct SoftwareProject :product :name :carriedOutBy :financedBy :head :isAbout )
( defstruct Product :name :developedBy )
( defstruct SoftwareComponent :hasPrice :name :developedBy )
( defstruct Topic :name )
( defstruct ResearchTopic :dealWithIn :name )
