( defstruct ModelElement )
( defstruct SyncChart )
( defstruct ReferenceState :subSyncChart )
( defstruct Arc :isImmediate :priority :target :source )
( defstruct Vertex )
( defstruct PseudoState :kind )
( defstruct PseudoStateKind )
( defstruct State :isFinal )
( defstruct SimpleState :isFinal )
( defstruct CompositeState :canTerminate :isSuspendable :stg :isFinal :subSyncChart )
( defstruct Stg :withFinal :compositeState )
( defstruct Transition :kind :isImmediate :priority :target :source )
( defstruct TransitionKind )
( defstruct PseudoTransition :kind :isImmediate :priority :target :source )
( defstruct PseudoTransitionKind )
