( defstruct TextualPathExp :path )
( defstruct Path :transitions )
( defstruct Transition :isMultiple )
( defstruct AlternativeTrans :altPaths :isMultiple )
( defstruct PrimitiveTrans :name :isMultiple )
