( defstruct Actor )
( defstruct Decomposition :PointOfView )
( defstruct Contribution :metric :contributer :contributed :PointOfView )
( defstruct Goal )
( defstruct MeansEnd :end :PointOfView )
( defstruct Resource )
( defstruct Plan )
( defstruct BooleanDecomposition :type :booleanDecLinkD :PointOfView )
( defstruct BooleanDecLink :booleanDecompositionB )
( defstruct AndDecLink :booleanDecompositionB )
( defstruct OrDecLink :booleanDecompositionB )
