( defstruct BusinessTemplate )
( defstruct BusinessContact )
( defstruct BusinessService )
( defstruct BusinessEntity )
( defstruct IdentifierBag )
( defstruct TModel )
( defstruct OverviewDocument )
