( defstruct UEMLObject )
( defstruct UEMLModel )
( defstruct Geometry :object )
( defstruct Port )
( defstruct Flow :associationConnector )
( defstruct Activity :hasOutput :hasInput :activityType :target :origin )
( defstruct Object )
( defstruct InformationObject )
( defstruct Resource :resourceType )
( defstruct MaterialResource :resourceType )
( defstruct HumanResource :obliger :claimer :has_parties :resourceType )
( defstruct ResourceFlow :associationConnector )
( defstruct IOFlow :associationConnector )
( defstruct ControlFlow :associationConnector )
( defstruct TriggerFlow :associationConnector )
( defstruct ConstraintFlow :associationConnector )
( defstruct ResourceRole :in )
( defstruct RoleType )
( defstruct Anchor )
( defstruct OutputPort :activity )
( defstruct InputPort :activity )
( defstruct ConnectionOperator :target :origin )
( defstruct AssociationConnector :classAssociation )
( defstruct FlowObject :target :origin )
( defstruct Event :target :origin )
( defstruct ResourceType )
( defstruct ActivityType )
( defstruct PassiveObject :resourceType )
( defstruct Commitment :resource :task :agentO :agentC :contract :resourceType )
( defstruct Software :obliger :claimer :has_parties :resourceType )
( defstruct Organisation :obliger :claimer :has_parties :resourceType )
( defstruct Process :child :realises :hasOutput :hasInput :activityType :target :origin )
( defstruct Service :process :resourceType )
( defstruct Agent :obliger :claimer :has_parties :resourceType )
( defstruct Contract :process :agent :collection_of :resourceType )
( defstruct Task :hasOutput :hasInput :activityType :target :origin )
