( defstruct UEMLObject )
( defstruct UEMLModel )
( defstruct Geometry :object )
( defstruct Port )
( defstruct Flow :associationConnector )
( defstruct Activity :hasOutput :hasInput :activityType )
( defstruct Object )
( defstruct InformationObject )
( defstruct Resource :resourceType )
( defstruct MaterialResource :resourceType )
( defstruct HumanResource :resourceType )
( defstruct ResourceFlow :associationConnector )
( defstruct IOFlow :associationConnector )
( defstruct ControlFlow :associationConnector )
( defstruct TriggerFlow :associationConnector )
( defstruct ConstraintFlow :associationConnector )
( defstruct ResourceRole :in )
( defstruct RoleType )
( defstruct Anchor :target :origin )
( defstruct OutputPort :activity :target :origin )
( defstruct InputPort :activity :target :origin )
( defstruct ConnectionOperator :target :origin )
( defstruct AssociationConnector :classAssociation )
( defstruct ResourceType )
( defstruct ActivityType )
