( defstruct UEMLObject )
( defstruct UEMLModel )
( defstruct Geometry :object )
( defstruct Port )
( defstruct Flow :associationConnector )
( defstruct Activity :hasOutput :hasInput )
( defstruct Object )
( defstruct InformationObject )
( defstruct Resource )
( defstruct MaterialResource )
( defstruct HumanResource )
( defstruct ResourceFlow :associationConnector )
( defstruct IOFlow :associationConnector )
( defstruct ControlFlow :associationConnector )
( defstruct TriggerFlow :associationConnector )
( defstruct ConstraintFlow :associationConnector )
( defstruct ResourceRole :in )
( defstruct RoleType )
( defstruct Anchor :target :origin )
( defstruct OutputPort :activity :target :origin )
( defstruct InputPort :activity :target :origin )
( defstruct ConnectionOperator :target :origin )
( defstruct AssociationConnector :classAssociation )
( defstruct PassiveObject )
( defstruct Commitment :resource )
( defstruct Contract )
( defstruct Agent )
( defstruct Software )
( defstruct Organisation )
