( defstruct UEMLObject )
( defstruct UEMLModel )
( defstruct Geometry :object )
( defstruct Port )
( defstruct Flow :associationConnector )
( defstruct Activity :hasOutput )
( defstruct Object )
( defstruct InformationObject )
( defstruct Resource )
( defstruct MaterialResource )
( defstruct HumanResource )
( defstruct ResourceFlow :associationConnector )
( defstruct IOFlow :associationConnector )
( defstruct ControlFlow :associationConnector )
( defstruct TriggerFlow :associationConnector )
( defstruct ConstraintFlow :associationConnector )
( defstruct ResourceRole :in )
( defstruct RoleType )
( defstruct Anchor :target :origin )
( defstruct OutputPort :activity :target :origin )
( defstruct InputPort :target :origin )
( defstruct ConnectionOperator :target :origin )
( defstruct AssociationConnector :classAssociation )
( defstruct Process :child :realises :hasOutput )
( defstruct Service :process )
( defstruct Agent :obliger :claimer :has_parties )
( defstruct Contract :process :agent :collection_of )
( defstruct Task :hasOutput )
( defstruct Commitment :task :agentO :agentC :contract )
