( defstruct UEMLObject )
( defstruct UEMLModel )
( defstruct Geometry :object )
( defstruct Port )
( defstruct Flow :associationConnector )
( defstruct Activity :hasOutput :hasInput :target :origin )
( defstruct Object )
( defstruct InformationObject )
( defstruct Resource )
( defstruct MaterialResource )
( defstruct HumanResource )
( defstruct ResourceFlow :associationConnector )
( defstruct IOFlow :associationConnector )
( defstruct ControlFlow :associationConnector )
( defstruct TriggerFlow :associationConnector )
( defstruct ConstraintFlow :associationConnector )
( defstruct ResourceRole :in )
( defstruct RoleType )
( defstruct Anchor )
( defstruct OutputPort :activity )
( defstruct InputPort :activity )
( defstruct ConnectionOperator :target :origin )
( defstruct AssociationConnector :classAssociation )
( defstruct Task :hasOutput :hasInput :target :origin )
( defstruct FlowObject :target :origin )
( defstruct Event :target :origin )
( defstruct Process )
