( defstruct UIML )
( defstruct Header )
( defstruct MetaData :name :content )
( defstruct ExtensibleElement )
( defstruct Source )
( defstruct LocalSource :source )
( defstruct RemoteSource :location )
( defstruct Interface )
( defstruct Structure )
( defstruct Part )
( defstruct Style )
( defstruct Property )
( defstruct Content )
( defstruct Behavior )
( defstruct Repeat :iterator :parts )
( defstruct Constant )
( defstruct Reference )
( defstruct Rule :condition :action )
( defstruct Condition )
( defstruct EventCondition :event )
( defstruct EqualCondition :equal )
( defstruct OpCondition :op )
( defstruct Action )
( defstruct Action_1 )
( defstruct Action_2 )
( defstruct Call )
( defstruct Parameter )
( defstruct PropertyParameter :property )
( defstruct ReferenceParameter :reference )
( defstruct CallParameter :call )
( defstruct OperationParameter :op )
( defstruct EventParameter :event )
( defstruct ConstantParameter :constant )
( defstruct IteratorParameter :iterator )
( defstruct Iterator :id )
( defstruct ConstantIterator :constant :id )
( defstruct PropertyIterator :property :id )
( defstruct CallIterator :call :id )
( defstruct TextIterator :value :id )
( defstruct Event )
( defstruct Equal :event )
( defstruct EqualToConstant :constant :event )
( defstruct EqualToProperty :property :event )
( defstruct EqualToReference :reference :event )
( defstruct EqualToOperation :op :event )
( defstruct Operation :name )
( defstruct Restructure )
( defstruct Branch )
( defstruct WhenTrue )
( defstruct WhenFalse )
( defstruct ByDefault )
( defstruct Peer )
( defstruct Presentation :base )
( defstruct Logic )
( defstruct DComponent :id )
( defstruct DClass :id :mapsTo :mapsType )
( defstruct DProperty :id :mapsType :mapsTo )
( defstruct DMethod :id :mapsTo )
( defstruct DParam :value )
( defstruct Script :value )
( defstruct Listener )
( defstruct Template )
( defstruct BehaviorTemplate :behavior )
( defstruct DClassTemplate :dClass )
( defstruct DComponentTemplate :dComponent )
( defstruct ConstantTemplate :constant )
( defstruct ContentTemplate :content )
( defstruct InterfaceTemplate :interface )
( defstruct LogicTemplate :logic )
( defstruct PartTemplate :part )
( defstruct PeerTemplate :peer )
( defstruct PresentationTemplate :presentation )
( defstruct PropertyTemplate :property )
( defstruct RestructureTemplate :restructure )
( defstruct RuleTemplate :rule )
( defstruct ScriptTemplate :script )
( defstruct StructureTemplate :structure )
( defstruct StyleTemplate :style )
