( defstruct Element )
( defstruct MultiplicityElement )
( defstruct NamedElement )
( defstruct Namespace )
( defstruct OpaqueExpression )
( defstruct ValueSpecification )
( defstruct Expression )
( defstruct Comment )
( defstruct DirectedRelationship :source :target :relatedElement )
( defstruct Relationship :relatedElement )
( defstruct Class )
( defstruct Type )
( defstruct Property )
( defstruct Operation )
( defstruct TypedElement )
( defstruct Parameter )
( defstruct Package )
( defstruct Enumeration )
( defstruct DataType )
( defstruct EnumerationLiteral )
( defstruct PrimitiveType )
( defstruct Classifier )
( defstruct Feature )
( defstruct Constraint :specification )
( defstruct LiteralBoolean )
( defstruct LiteralSpecification )
( defstruct LiteralString )
( defstruct LiteralNull )
( defstruct LiteralInteger )
( defstruct LiteralUnlimitedNatural )
( defstruct BehavioralFeature )
( defstruct StructuralFeature )
( defstruct InstanceSpecification )
( defstruct Slot :owningInstance :definingFeature )
( defstruct InstanceValue :instance )
( defstruct RedefinableElement )
( defstruct Generalization :specific :general :source :target :relatedElement )
( defstruct PackageableElement )
( defstruct ElementImport :importedElement :importingNamespace :source :target :relatedElement )
( defstruct PackageImport :importedPackage :importingNamespace :source :target :relatedElement )
( defstruct Association :endType :memberEnd :relatedElement )
( defstruct PackageMerge :mergingPackage :mergedPackage :source :target :relatedElement )
( defstruct Stereotype )
( defstruct Profile )
( defstruct ProfileApplication :importedProfile :importedPackage :importingNamespace :source :target :relatedElement )
( defstruct Extension :metaclass :endType :memberEnd :relatedElement )
( defstruct ExtensionEnd )
( defstruct Behavior )
( defstruct BehavioredClassifier )
( defstruct Activity )
( defstruct Permission :client :supplier :source :target :relatedElement )
( defstruct Dependency :client :supplier :source :target :relatedElement )
( defstruct Usage :client :supplier :source :target :relatedElement )
( defstruct Abstraction :client :supplier :source :target :relatedElement )
( defstruct Realization :realizingClassifier :client :supplier :source :target :relatedElement )
( defstruct Substitution :contract :substitutingClassifier :realizingClassifier :client :supplier :source :target :relatedElement )
( defstruct GeneralizationSet )
( defstruct AssociationClass :endType :memberEnd :relatedElement )
( defstruct InformationItem )
( defstruct InformationFlow :conveyed :source :target :relatedElement )
( defstruct Model )
( defstruct ConnectorEnd )
( defstruct ConnectableElement )
( defstruct Connector :end )
( defstruct StructuredClassifier )
( defstruct ActivityEdge :source :target :guard :weight )
( defstruct ActivityGroup )
( defstruct ActivityNode )
( defstruct Action )
( defstruct ObjectNode :upperBound )
( defstruct ControlNode )
( defstruct ControlFlow :source :target :guard :weight )
( defstruct ObjectFlow :source :target :guard :weight )
( defstruct InitialNode )
( defstruct FinalNode )
( defstruct ActivityFinalNode )
( defstruct DecisionNode )
( defstruct MergeNode )
( defstruct ExecutableNode )
( defstruct OutputPin :upperBound )
( defstruct InputPin :upperBound )
( defstruct Pin :upperBound )
( defstruct ActivityParameterNode :parameter :upperBound )
( defstruct ValuePin :value :upperBound )
( defstruct Interface )
( defstruct Implementation :contract :implementingClassifier :realizingClassifier :client :supplier :source :target :relatedElement )
( defstruct Artifact )
( defstruct Manifestation :utilizedElement :client :supplier :source :target :relatedElement )
( defstruct Actor )
( defstruct Extend :extendedCase :extension :extensionLocation :source :target :relatedElement )
( defstruct UseCase )
( defstruct ExtensionPoint :useCase )
( defstruct Include :includingCase :addition :source :target :relatedElement )
( defstruct CollaborationOccurrence :type )
( defstruct Collaboration )
( defstruct Port )
( defstruct EncapsulatedClassifier )
( defstruct CallTrigger :operation )
( defstruct MessageTrigger )
( defstruct ChangeTrigger :changeExpression )
( defstruct Trigger )
( defstruct Reception )
( defstruct Signal )
( defstruct SignalTrigger )
( defstruct TimeTrigger :when )
( defstruct AnyTrigger )
( defstruct Variable :scope )
( defstruct StructuredActivityNode )
( defstruct ConditionalNode :clause )
( defstruct Clause :decider )
( defstruct LoopNode :decider )
( defstruct Interaction )
( defstruct InteractionFragment )
( defstruct Lifeline :represents :interaction )
( defstruct Message :interaction )
( defstruct GeneralOrdering :before :after )
( defstruct MessageEnd )
( defstruct EventOccurrence )
( defstruct ExecutionOccurrence :start :finish )
( defstruct StateInvariant :invariant )
( defstruct Stop )
( defstruct TemplateSignature :parameter :template )
( defstruct TemplateParameter :signature :parameteredElement )
( defstruct TemplateableElement )
( defstruct StringExpression )
( defstruct ParameterableElement )
( defstruct TemplateBinding :boundElement :signature :source :target :relatedElement )
( defstruct TemplateParameterSubstitution :formal :templateBinding :actual )
( defstruct OperationTemplateParameter :signature :parameteredElement )
( defstruct ClassifierTemplateParameter :signature :parameteredElement )
( defstruct ParameterableClassifier )
( defstruct RedefinableTemplateSignature :parameter :template )
( defstruct TemplateableClassifier )
( defstruct ConnectableElementTemplateParameter :signature :parameteredElement )
( defstruct ForkNode )
( defstruct JoinNode :joinSpec )
( defstruct FlowFinalNode )
( defstruct CentralBufferNode :upperBound )
( defstruct ActivityPartition )
( defstruct ExpansionNode :upperBound )
( defstruct ExpansionRegion :inputElement )
( defstruct ExceptionHandler :protectedNode :handlerBody :exceptionInput :exceptionType )
( defstruct InteractionOccurrence :refersTo )
( defstruct Gate )
( defstruct PartDecomposition :refersTo )
( defstruct InteractionOperand )
( defstruct InteractionConstraint :specification )
( defstruct CombinedFragment :operand )
( defstruct Continuation )
( defstruct StateMachine :region )
( defstruct Region )
( defstruct Pseudostate )
( defstruct State )
( defstruct Vertex )
( defstruct ConnectionPointReference )
( defstruct Transition :container :source :target )
( defstruct FinalState )
( defstruct CreateObjectAction :classifier :result )
( defstruct DestroyObjectAction :target )
( defstruct TestIdentityAction :first :second :result )
( defstruct ReadSelfAction :result )
( defstruct StructuralFeatureAction :structuralFeature :object )
( defstruct ReadStructuralFeatureAction :result :structuralFeature :object )
( defstruct WriteStructuralFeatureAction :value :structuralFeature :object )
( defstruct ClearStructuralFeatureAction :structuralFeature :object )
( defstruct RemoveStructuralFeatureValueAction :value :structuralFeature :object )
( defstruct AddStructuralFeatureValueAction :value :structuralFeature :object )
( defstruct LinkAction :endData )
( defstruct LinkEndData :end )
( defstruct ReadLinkAction :result :endData )
( defstruct LinkEndCreationData :end )
( defstruct CreateLinkAction :endData )
( defstruct WriteLinkAction :endData )
( defstruct DestroyLinkAction :endData )
( defstruct ClearAssociationAction :object :association )
( defstruct VariableAction :variable )
( defstruct ReadVariableAction :result :variable )
( defstruct WriteVariableAction :value :variable )
( defstruct ClearVariableAction :variable )
( defstruct AddVariableValueAction :value :variable )
( defstruct RemoveVariableValueAction :value :variable )
( defstruct ApplyFunctionAction :function )
( defstruct PrimitiveFunction )
( defstruct CallAction )
( defstruct InvocationAction )
( defstruct SendSignalAction :target :signal )
( defstruct BroadcastSignalAction :signal )
( defstruct SendObjectAction :target :request )
( defstruct CallOperationAction :operation :target )
( defstruct CallBehaviorAction :behavior )
( defstruct TimeExpression )
( defstruct Duration )
( defstruct TimeObservationAction :value :structuralFeature :object )
( defstruct DurationInterval )
( defstruct Interval )
( defstruct TimeConstraint :specification )
( defstruct IntervalConstraint :specification )
( defstruct TimeInterval )
( defstruct DurationObservationAction :value :structuralFeature :object )
( defstruct DurationConstraint :specification )
( defstruct DataStoreNode :upperBound )
( defstruct InterruptibleActivityRegion )
( defstruct ParameterSet :parameter )
( defstruct Component )
( defstruct Deployment :location :client :supplier :source :target :relatedElement )
( defstruct DeployedArtifact )
( defstruct DeploymentTarget )
( defstruct Node )
( defstruct Device )
( defstruct ExecutionEnvironment )
( defstruct CommunicationPath :endType :memberEnd :relatedElement )
( defstruct ProtocolConformance :specificMachine :generalMachine :source :target :relatedElement )
( defstruct ProtocolStateMachine :region )
( defstruct ProtocolTransition :container :source :target )
( defstruct ReadExtentAction :result :classifier )
( defstruct ReclassifyObjectAction :object )
( defstruct ReadIsClassifiedObjectAction :classifier :result :object )
( defstruct StartOwnedBehaviorAction :object )
( defstruct QualifierValue :qualifier :value )
( defstruct ReadLinkObjectEndAction :object :end :result )
( defstruct ReadLinkObjectEndQualifierAction :object :result :qualifier )
( defstruct CreateLinkObjectAction :result :endData )
( defstruct AcceptEventAction )
( defstruct AcceptCallAction :returnInformation )
( defstruct ReplyAction :replyToCall :returnInformation )
( defstruct RaiseExceptionAction :exception )
( defstruct DeploymentSpecification )
