( defstruct Class :parent :child :dependency )
( defstruct Generalization )
( defstruct Dependency :supplier :client :stereotype )
( defstruct Stereotype :baseClass :extendedElement )
( defstruct StateMachine :context :top )
( defstruct State :internal )
( defstruct CompositeState :subvertex :internal )
( defstruct SimpleState :internal )
( defstruct FinalState :internal )
( defstruct StateVertex )
( defstruct PseudoState )
( defstruct Transition :source :target )
( defstruct Event )
