( defstruct ReuseContract :supplier :client )
( defstruct Dependency )
( defstruct ProviderClause )
( defstruct Package )
( defstruct ReuserClause )
( defstruct CompositeProvider :subcontract )
( defstruct BasicProvider )
( defstruct CompositeReuser )
( defstruct BasicReuser )
