( defstruct Classifier )
( defstruct Instance :classifier )
( defstruct Actor )
( defstruct UseCase :includeAddition :includeBase :extendExtension :extendBase )
( defstruct UseCaseInstance :classifier )
( defstruct RelationShip )
( defstruct Include :addition :base )
( defstruct Extend :condition :extension :base :extensionPoint )
( defstruct BooleanExpression :value )
( defstruct ModelElement )
( defstruct ExtensionPoint :location )
( defstruct LocationReference :value )
