( defstruct Package :isRoot :isLeaf :isAbstract :isSpecification :isSpecification )
( defstruct Model :isRoot :isLeaf :isAbstract :isSpecification :isSpecification )
( defstruct Subsystem :isInstantiable :isRoot :isLeaf :isAbstract :isSpecification :isSpecification :isRoot :isLeaf :isAbstract :isSpecification :isSpecification )
( defstruct ElementImport :package :importedElement :isSpecification )
( defstruct Element )
( defstruct ModelElement :isSpecification )
( defstruct GeneralizableElement :isRoot :isLeaf :isAbstract :isSpecification )
( defstruct Namespace :isSpecification )
( defstruct Classifier :isRoot :isLeaf :isAbstract :isSpecification :isSpecification )
( defstruct Feature :ownerScope :isSpecification )
( defstruct Relationship :isSpecification )
( defstruct Generalization :parent :child :isSpecification )
