( defstruct MultiplicityType :lower :upper :isOrdered :isUnique )
( defstruct ModelElement :name )
( defstruct Feature :ownerScope :visibility :name )
( defstruct NameSpace :name )
( defstruct GeneralizableElement :isRoot :isLeaf :isAbstract :name )
( defstruct Classifier :name :isRoot :isLeaf :isAbstract :name )
( defstruct Class :isActive :name :isRoot :isLeaf :isAbstract :name )
( defstruct StructuralFeature :multiplicity :isChangeable :targetScope :ownerScope :visibility :name )
( defstruct Attribute :initialValue :multiplicity :isChangeable :targetScope :ownerScope :visibility :name )
( defstruct BehavioralFeature :isQuery :ownerScope :visibility :name )
( defstruct Operation :isRoot :isLeaf :isAbstract :specification :isQuery :ownerScope :visibility :name )
