( defstruct NamedElement :name )
( defstruct File :owner :group :name )
( defstruct Directory :owner :group :name )
( defstruct FileSystemRoot :owner :group :name )
( defstruct TextFile :owner :group :name )
