( defstruct Requirement )
( defstruct NonFunctionnelRequirement )
( defstruct FunctionnelRequirement )
( defstruct UseCase :meet_by )
( defstruct Goal :to_meet )
( defstruct Role )
( defstruct HumanRole )
( defstruct SystemRole )
( defstruct EventRole )
( defstruct Manage :meet_by )
( defstruct Resource )
( defstruct ScenarioDescription :useCase )
( defstruct Condition )
( defstruct Pre )
( defstruct Post )
