( defstruct Task :service )
( defstruct User :useCase )
( defstruct Actor :useCase )
( defstruct Goal :service :actor )
( defstruct UseCase )
( defstruct Service :useCase :goal :task )
( defstruct Scenario )
( defstruct Context :preCondition :postCondition :useCase )
( defstruct PreCondition )
( defstruct PostCondition )
( defstruct Episode )
( defstruct Event :episode )
( defstruct Action :episode )
( defstruct Responce :episode )
( defstruct Stimilus :episode )
( defstruct Parameter :stimilus :responce )
