( defstruct ClientPage :hyperlink )
( defstruct ClientPageModule :consistsOf :representsSMP )
( defstruct LogicInterface :represents :generatedBy :consistsOf :representsSMP )
( defstruct DesignElement :represents :consistsOf :representsSMP )
( defstruct HyperLink )
( defstruct ServerPage :module )
( defstruct ServerPageModule :contains :link :containsModule )
( defstruct DesignModule :contains :link :containsModule )
( defstruct LogicModule :useCase :logicElement :contains :link :containsModule )
( defstruct Link :page :posts )
( defstruct BeginUseCase :useCase :page :posts )
( defstruct UseCase :logicElem :page :posts )
( defstruct LogicElement :uses :generatedBy :next )
( defstruct Alternative :uses :generatedBy :next )
( defstruct UserDecision :allows :uses :generatedBy :next )
( defstruct ServerDecision :evaluatesResultOf :uses :generatedBy :next )
( defstruct Processor :outputData :uses :generatedBy :next )
( defstruct Renderer :renders :uses :generatedBy :next )
( defstruct Data )
