( defstruct WorkDefinition :owner )
( defstruct ProcessPerformer )
( defstruct Role )
( defstruct WorkProduct :responsible )
( defstruct Lifecycle :phases :owner )
( defstruct Phase :lifeCycle :iterations :owner )
( defstruct Iteration :phase :activities :owner )
( defstruct Activity :iteration :owner )
( defstruct Step )
