( defstruct LocatedElement :location )
( defstruct Network :location )
( defstruct Services :name :URL :descriptions :location )
( defstruct WebService :name :URL :descriptions :location )
( defstruct RSS :name :URL :descriptions :location )
