( defstruct Page :title :graphContainer :pageResources )
( defstruct NameSpace :namespace :identifier )
( defstruct PageResource )
( defstruct GraphicalContainer )
( defstruct WinFXElement :namespace )
( defstruct PerspectiveElement :namespace )
( defstruct ResourceDictionary :source )
( defstruct Grid )
( defstruct Object3D )
( defstruct Workshop3D :namespace )
( defstruct Element3D )
( defstruct UI3Delement :transform :material :name )
( defstruct XyzAxis3D :length :namespace )
( defstruct Box3D :transform :material :name :namespace )
( defstruct Square3D :transform :material :name :namespace )
( defstruct Name :name :namespace )
