( defstruct ValuedElement :value )
( defstruct CDATA :value )
( defstruct PCDATA :value )
( defstruct NMTOKEN :value )
( defstruct IDREF :value )
( defstruct IDREFS )
( defstruct ID :value )
( defstruct EMPTY )
( defstruct ContentType :value )
( defstruct ContentTypes :contentTypes )
( defstruct Charset :value )
( defstruct Charsets :charsets )
( defstruct LanguageCode :value )
( defstruct Character :value )
( defstruct Number :value )
( defstruct LinkTypes :value )
( defstruct MediaDesc :value )
( defstruct URI :value )
( defstruct UriList :uris )
( defstruct Datetime :value )
( defstruct ScriptExpression :value )
( defstruct StyleSheet :value )
( defstruct Text :value )
( defstruct Length :value )
( defstruct MultiLength :value )
( defstruct Pixels :value )
( defstruct Coords :lengths )
( defstruct CoreAttrs )
( defstruct I18n )
( defstruct Events )
( defstruct Attrs )
( defstruct Focus )
( defstruct Specialpre )
( defstruct Special )
( defstruct Fontstyle )
( defstruct Phrase )
( defstruct Inlineforms )
( defstruct Miscinline )
( defstruct Misc )
( defstruct inline )
( defstruct Inline )
( defstruct Heading )
( defstruct Lists )
( defstruct Blocktext )
( defstruct block )
( defstruct Block )
( defstruct Flow )
( defstruct AContent )
( defstruct PreContent )
( defstruct FormContent )
( defstruct ButtonContent )
( defstruct Html :i18n :xmlns :head :body )
( defstruct HeadMisc )
( defstruct Head :i18n :headelement :html )
( defstruct HeadElement )
( defstruct TitleHeadElement :title :baseTitleHeadElement )
( defstruct BaseTitleHeadElement :base )
( defstruct BaseHeadElement :base :titleBaseHeadElement )
( defstruct TitleBaseHeadElement :title )
( defstruct Title :i18n :value )
( defstruct Base :href )
( defstruct Meta :i18n )
( defstruct Link )
( defstruct Style :i18n :type :xml:space :value )
( defstruct Script :type :xml:space :value )
( defstruct Noscript :block )
( defstruct Body :html )
( defstruct Div )
( defstruct P )
( defstruct H1 )
( defstruct H2 )
( defstruct H3 )
( defstruct H4 )
( defstruct H5 )
( defstruct H6 )
( defstruct Ul :li )
( defstruct Ol :li )
( defstruct Li )
( defstruct Dl :dlElements )
( defstruct DlElement )
( defstruct Dt )
( defstruct Dd )
( defstruct Address )
( defstruct Hr )
( defstruct Pre :xml:space )
( defstruct Blockquote )
( defstruct Ins )
( defstruct Del )
( defstruct A :shape )
( defstruct Span )
( defstruct Bdo :dir )
( defstruct Br )
( defstruct Em )
( defstruct Strong )
( defstruct Dfn )
( defstruct Code )
( defstruct Samp )
( defstruct Kbd )
( defstruct Var )
( defstruct Cite )
( defstruct Abbr )
( defstruct Acronym )
( defstruct Q )
( defstruct Sub )
( defstruct Sup )
( defstruct Tt )
( defstruct I )
( defstruct B )
( defstruct Big )
( defstruct Small )
( defstruct ObjectElement )
( defstruct Object )
( defstruct Param :valuetype )
( defstruct Img :src :alt )
( defstruct MapContent :mapElements )
( defstruct MapElement )
( defstruct MapElementContent )
( defstruct Map :mapelement :id )
( defstruct Area :shape :alt )
( defstruct Form :action :method :enctype )
( defstruct Label :for )
( defstruct Input :type )
( defstruct Select :selectelement )
( defstruct SelectElement )
( defstruct Optgroup :options :label )
( defstruct Option :value )
( defstruct Textarea :rows :cols :value )
( defstruct FieldsetElement )
( defstruct Fieldset )
( defstruct Legend )
( defstruct Button :type )
( defstruct Cellhalign )
( defstruct Cellvalign )
( defstruct Table :caption :colelement :thead :tfoot :tableelement )
( defstruct ColElement )
( defstruct TableElement :tbody :tr )
( defstruct Caption )
( defstruct Thead :tr )
( defstruct Tfoot :tr )
( defstruct Tbody :tr )
( defstruct Colgroup :span )
( defstruct Col :span )
( defstruct Tr :trelements )
( defstruct TrElement )
( defstruct Th :rowspan :colspan )
( defstruct Td :rowspan :colspan )
