( defstruct Element :id )
( defstruct Package :id )
( defstruct MessageFlow :id )
( defstruct Association :id )
( defstruct Pool :boundaryVisible :id )
( defstruct Lane :id )
( defstruct Participant :id )
( defstruct Artifact :id )
( defstruct DataObject :requiredForStart :producedAtCompletion :id )
( defstruct Group :id )
( defstruct Annotation :id )
( defstruct TypeDeclaration :id )
( defstruct Application :id )
( defstruct ParametrizedApplication :id )
( defstruct ReferencedApplication :id )
( defstruct Activity :startMode :finishMode :id )
( defstruct Task :startMode :finishMode :id )
( defstruct TaskService :startMode :finishMode :id )
( defstruct TaskReceive :instantiate :startMode :finishMode :id )
( defstruct TaskManual :startMode :finishMode :id )
( defstruct TaskReference :taskRef :startMode :finishMode :id )
( defstruct TaskScript :script :startMode :finishMode :id )
( defstruct TaskSend :startMode :finishMode :id )
( defstruct TaskUser :startMode :finishMode :id )
( defstruct TaskApplication :startMode :finishMode :id )
( defstruct Route :startMode :finishMode :id )
( defstruct SubFlow :startMode :finishMode :id )
( defstruct BlockActivity :activitySet :startMode :finishMode :id )
( defstruct Event :triggerKind :startMode :finishMode :id )
( defstruct Trigger )
( defstruct ResultCompensation )
( defstruct ResultError :errorCode )
( defstruct ResultMultiple )
( defstruct TriggerResultLink :processRef )
( defstruct TriggerResultMessage )
( defstruct TriggerIntermediateMultiple )
( defstruct TriggerMultiple )
( defstruct TriggerRule :ruleName )
( defstruct TriggerTimer )
( defstruct StartEvent :triggerKind :startMode :finishMode :id )
( defstruct IntermediateEvent :triggerKind :startMode :finishMode :id )
( defstruct EndEvent :triggerKind :startMode :finishMode :id )
( defstruct Gateway :startMode :finishMode :id )
( defstruct Process :dataField :id )
( defstruct Transition :to :from :id )
( defstruct ActivitySet :id )
( defstruct ExternalReference :location )
( defstruct Object :id )
( defstruct ExternalPackage :href :id )
( defstruct Category :id )
( defstruct DataField :dataType :id )
( defstruct Script :type )
