( defstruct XQueryProgram )
( defstruct Expression :returnEx )
( defstruct ExecutableExpression :xQueryProgram :functionDeclaration :returnEx )
( defstruct Node :name :returnEx )
( defstruct FLWOR :for :let :where :orderBy :return :xQueryProgram :functionDeclaration :returnEx )
( defstruct FunctionCall :name :xQueryProgram :functionDeclaration :returnEx )
( defstruct FunctionDeclaration :name :expression :xQueryProgram :functionDeclaration :returnEx )
( defstruct ElementNode :name :returnEx )
( defstruct AttributeNode :value :name :returnEx )
( defstruct TextNode :name :returnEx )
( defstruct ReturnXPath :value :returnEx )
( defstruct XPath :functionCall :for :let :value :returnEx )
( defstruct BooleanExp :where :functionCall :for :let :value :returnEx )
( defstruct For :var :flwor :expression )
( defstruct Let :var :flwor :expression )
( defstruct Where :flwor :expression )
( defstruct OrderBy :flwor )
( defstruct Return :flwor )
