( defstruct AnnotedElement )
( defstruct Annotation :annotedElement )
( defstruct Documentation :text )
( defstruct ApplicationInfo :text )
( defstruct NamedElement :name )
( defstruct XSchema :namespace )
( defstruct XSchemaContentElement :name )
( defstruct Parameters :name )
( defstruct Element :name :container :complexType :minOccurs :maxOccurs )
( defstruct Occurable :minOccurs :maxOccurs )
( defstruct AbstractContent :container :complexType :minOccurs :maxOccurs )
( defstruct Container :container :complexType :minOccurs :maxOccurs )
( defstruct AtomicContent :container :complexType :minOccurs :maxOccurs )
( defstruct ElementRef :referencedElement :container :complexType :minOccurs :maxOccurs )
( defstruct GroupRef :referencedGroup :container :complexType :minOccurs :maxOccurs )
( defstruct All :container :complexType :minOccurs :maxOccurs )
( defstruct Group :name :container :complexType :minOccurs :maxOccurs )
( defstruct Choice :container :complexType :minOccurs :maxOccurs )
( defstruct Sequence :container :complexType :minOccurs :maxOccurs )
( defstruct AbstractAttributeGroupContent :container :complexType :minOccurs :maxOccurs )
( defstruct AttributeGroup :container :complexType :minOccurs :maxOccurs :name )
( defstruct AttributeGroupRef :referencedAttributeGroup :container :complexType :minOccurs :maxOccurs )
( defstruct AtomicAttributeGroupContent :container :complexType :minOccurs :maxOccurs )
( defstruct Attribute :name :container :complexType :minOccurs :maxOccurs )
( defstruct AttributeRef :referencedAttribute :container :complexType :minOccurs :maxOccurs )
( defstruct AbstractType :container :name )
( defstruct SimpleType :container :name )
( defstruct ComplexType :container :name )
( defstruct ComplexTypeSimpleContent :base :container :name )
( defstruct ComplexTypeComplexContent :base :container :name )
