( defstruct Node :name )
( defstruct ElementNode :name )
( defstruct AttributeNode :name )
( defstruct RootNode :document :name )
( defstruct TextNode :value :name )
( defstruct XSLTNode :name )
( defstruct XSLTRootNode :document :name )
( defstruct Document :documentName :document )
( defstruct ApplyTemplates :select :name )
( defstruct If :test :name )
( defstruct Template :match :name )
( defstruct ValueOf :select :name )
( defstruct When :test :name )
( defstruct Choose :when :otherwise :name )
( defstruct Otherwise :name )
( defstruct Sort :select :name )
