( defstruct LocatedElement )
( defstruct Model )
( defstruct Class :name )
( defstruct ModelElement :model )
( defstruct ColorableElement :model )
( defstruct ClassReference :class :model )
( defstruct Relationship :source :target :model )
( defstruct ClassDefinition )
( defstruct Association :type :navigableSource :sourceVisibility :navigableTarget :targetVisibility :source :target :model )
( defstruct Inheritance :source :target :model )
( defstruct Cardinality :upperBound )
( defstruct ClassMember :visibility :name )
( defstruct Attribute :visibility :name )
( defstruct Method :visibility :name )
( defstruct Note :model )
( defstruct NoteAssociation :note :source :target :model )
