<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="BIBTEXML">
  <Article id="ISI2005" abstract="" year="2005" month="" title="{Modeles, Protocoles et Architectures pour Transactions Mobiles Adaptables}" journal="Journal on Ingenierie des Systemes d'Information, Hermes ed, Special Issue on Mobilite dans les Systemes d'Information et de Bases de Donnees" volume="10" number="6" pages="95-121" note="">
    <authors name="Patricia Serrano-Alvarado "/>
    <authors name=" Claudia L. Roncancio "/>
    <authors name=" Michel Adiba "/>
    <authors name=" Cyril Labbe"/>
  </Article>
  <Article id="JDIM05:Lepape" abstract="" year="2005" month="" title="{D}ata {Q}uality {M}anagement in a {D}atabase {C}luster with {L}azy {R}eplication" journal="Journal of Digital Information Management" volume="3" number="2" pages="82-87" note="">
    <authors name="C. Le Pape, S. Ganearski "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="GenieLogATL05" abstract="" year="2005" month="June" title="AMMA : vers une plate-forme generique d'ingenierie des modeles" journal="Genie Logiciel" volume="" number="73" pages="8-15" note="ISBN=0295-6322">
    <authors name="Freddy Allilaire "/>
    <authors name=" Jean Bezivin "/>
    <authors name=" Marcos Didonet Del Fabro "/>
    <authors name=" Frederic Jouault "/>
    <authors name=" David Touzet "/>
    <authors name=" Patrick Valduriez"/>
  </Article>
  <Article id="IC:Objet2002" abstract="" year="2002" month="nov" title="Sources d'informations et de connaissances : de la gestion locale e la recherche distribuee" journal="RSTI, L'Objet" volume="8" number="4" pages="47-69" note="">
    <authors name="S. Cazalens "/>
    <authors name=" E. Desmontils "/>
    <authors name=" C. Jacquin "/>
    <authors name=" P. Lamarre"/>
  </Article>
  <Article id="Sunye02" abstract="" year="2002" month="" title="Using {UML} Action Semantics for Model Execution and Transformation" journal="Information Systems Journal" volume="27" number="6" pages="445-457" note="">
    <authors name="G. Sunye "/>
    <authors name=" A. Le Guennec "/>
    <authors name=" J.-M. Jezequel"/>
  </Article>
  <Article id="SoSym2005" abstract="" year="2005" month="" title="Platform independent Web Application Modeling and Development with Netsilon" journal="Software and System Modeling (SoSym)" volume="4" number="4" pages="424-442" note="ISBN=1619-1366">
    <authors name="Pierre-Alain Muller "/>
    <authors name=" Philippe Studer "/>
    <authors name=" Frederic Fondement "/>
    <authors name=" Jean Bezivin"/>
  </Article>
  <Article id="VLDBJ2000:PacittiS" abstract="" year="2000" month="" title="Update Propagation Strategies to Improve Freshness in Lazy Master Replicated Databases" journal="The VLDB Journal" volume="8" number="3-4" pages="" note="">
    <authors name="E. Pacitti "/>
    <authors name=" E. Simon"/>
  </Article>
  <Article id="DAPD2006:Akbarinia" abstract="" year="2006" month="" title="Reducing Network Traffic in Unstructured P2P Systems Using Top-K Queries" journal="Distributed and Parallel Databases" volume="" number="" pages="" note="A paraetre, Version '{e}lectronique http://dx.doi.org/10.1007/s10619-006-8313-5">
    <authors name="R. Akbarinia "/>
    <authors name=" E. Pacitti "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="VLDBJ2001:ValduriezetAl" abstract="" year="2001" month="" title="{PicoDBMS}: Scaling down database techniques for the Smartcard" journal="The VLDB Journal, special issue on Best Papers from VLDB2000" volume="10" number="2-3" pages="" note="">
    <authors name="P. Pucheral "/>
    <authors name=" L. Bouganim "/>
    <authors name=" P. Valduriez "/>
    <authors name=" C. Bobineau"/>
  </Article>
  <Article id="IC:Cazalens:AFIA2001" abstract="" year="2001" month="" title="Une experience de specification d'organisation d'agents deployes sur Internet" journal="Actes de l'atelier SMA, Plate-forme AFIA 2001" volume="" number="" pages="37--46" note="">
    <authors name="S. Cazalens "/>
    <authors name=" P. Lamarre"/>
  </Article>
  <Article id="TKDE1998:Valduriez" abstract="" year="1998" month="" title="Scaling Access to Heterogeneous Data Sources with DISCO" journal="IEEE Trans. on Knowledge and Data Engineering" volume="10" number="5" pages="" note="">
    <authors name="A. Tomasic "/>
    <authors name=" L. Raschid "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="bezivin0015" abstract="Le MDA qui fait l'objet de notre dossier connaet de nombreuses et frequentes avancees. Cet article fait le point sur les developpements les plus recents en la matiere." year="2004" month="September/October" title="Les evolutions recentes en ingenierie des modeles" journal="IT Expert Journal" volume="" number="51" pages="1-4" note="ISBN=1270-4881">
    <authors name="Bezivin, J."/>
  </Article>
  <Article id="DPD2001:PacittiMS" abstract="" year="2001" month="" title="Replica Consistency in Lazy Master Replicated Databases" journal="Distributed and Parallel Databases" volume="9" number="3" pages="" note="">
    <authors name="E. Pacitti "/>
    <authors name=" P. Minet "/>
    <authors name=" E. Simon"/>
  </Article>
  <Article id="IJCSSE2005" abstract="" year="2005" month="" title="{An Adaptable Mobile Transaction Model for Mobile Environments}" journal="International Journal of Computer Systems Science and Engineering (IJCSSE), Special Issue on Mobile Databases" volume="20" number="3" pages="13 pages" note="ISSN 0267-6192">
    <authors name="Patricia Serrano-Alvarado "/>
    <authors name=" Claudia L. Roncancio "/>
    <authors name=" Michel Adiba "/>
    <authors name=" Cyril Labbe"/>
  </Article>
  <Article id="Lamarre:2005" abstract="" year="2005" month="" title="A flexible mediation process for large distributed information systems" journal="International Journal of Cooperative Information Systems" volume="" number="" pages="" note="">
    <authors name="Philippe Lamarre "/>
    <authors name=" S"/>
    <authors name="ra Lemp "/>
    <authors name=" Sylvie Cazalens "/>
    <authors name=" Patrick Valduriez"/>
  </Article>
  <Article id="TSI2003:ValduriezEtAl" abstract="" year="2003" month="" title="Mobilit'e et bases de donn'ees : 'etat de l'art et perspectives" journal="Techniques et Sciences de l'Informatique (TSI)" volume="22" number="3-4" pages="" note="">
    <authors name="G. Bernard "/>
    <authors name=" J. Ben-Othman "/>
    <authors name=" L. Bouganim "/>
    <authors name=" G. Canals "/>
    <authors name=" B. Defude "/>
    <authors name=" J. Ferri'e "/>
    <authors name=" S.Ganearski "/>
    <authors name=" R. Guerraoui "/>
    <authors name=" P. Molli "/>
    <authors name=" P. Pucheral "/>
    <authors name=" C. Roncancio "/>
    <authors name=" P. Serrano-Alvarado "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="Novatica2004a:Bezivin" abstract="" year="2004" month="April" title="In search of a Basic Principle for Model-Driven Engineering" journal="Novatica -- Special Issue on {UML} (Unified Modeling Language)" volume="5" number="2" pages="21-24" note="">
    <authors name="J. Bezivin"/>
  </Article>
  <Article id="SoSym2004:Bezivin" abstract="" year="2005" month="May" title="On the Unification Power of Models" journal="Software and System Modeling (SoSym)" volume="4" number="2" pages="171-188" note="">
    <authors name="J. Bezivin"/>
  </Article>
  <Article id="IS2006:Gancarski" abstract="" year="2006" month="" title="The Leganet System. Freshness-Aware Transaction Routing in a Database Cluster" journal="Information Systems" volume="" number="" pages="" note="version electronique sur http://www.sciencedirect.com/">
    <authors name="S. Ganearski "/>
    <authors name=" H. Naacke "/>
    <authors name=" E. Pacitti "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="ASMobilite" abstract="" year="2003" month="" title="{Mobilit'e et Bases de Donn'ees : Etat de l'Art et Perspectives (Partie I et II)}" journal="Chronique Technique et science informatiques (TSI)" volume="22" number="3 and 4" pages="50 pages" note="">
    <authors name="G. Bernard "/>
    <authors name=" J. Ben-Othman "/>
    <authors name=" L. Bouganim "/>
    <authors name=" G. Canals "/>
    <authors name=" B. Defude "/>
    <authors name=" J. Ferri'e "/>
    <authors name=" S. Ganearski "/>
    <authors name=" R. Guerraoui "/>
    <authors name=" P. Molli "/>
    <authors name=" P. Pucheral "/>
    <authors name=" C. Roncancio "/>
    <authors name=" P. Serrano-Alvarado "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="JOOP2001:Bezivin" abstract="" year="2001" month="dec" title="Tooling the {MDA} framework: a new software maintenance and evolution scheme proposal" journal="Journal of Object-Oriented Programming, JOOP" volume="" number="" pages="" note="">
    <authors name="J. B'ezivin "/>
    <authors name=" N. Ploquin"/>
  </Article>
  <Article id="ASMobiliteSIGMOD" abstract="" year="2004" month="June" title="{Mobile Databases: a Selection of Open Issues and Research Directions)}" journal="ACM SIGMOD Record" volume="33" number="2" pages="78-83" note="ISSN 0163-5808">
    <authors name="G. Bernard "/>
    <authors name=" J. Ben-Othman "/>
    <authors name=" L. Bouganim "/>
    <authors name=" G. Canals "/>
    <authors name=" B. Defude "/>
    <authors name=" J. Ferri'e "/>
    <authors name=" S. Ganearski "/>
    <authors name=" R. Guerraoui "/>
    <authors name=" P. Molli "/>
    <authors name=" P. Pucheral "/>
    <authors name=" C. Roncancio "/>
    <authors name=" P. Serrano-Alvarado "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="ARIMA06:Faye" abstract="" year="2006" month="" title="Un systeme Pair-e-Pair de mediation de donnees" journal="Africaine de la Rechrche en Informatique et Mathematique Appliquees (ARIMA)" volume="4" number="" pages="" note="">
    <authors name="D. Faye "/>
    <authors name=" G. Nachouki "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="Pacitti02a" abstract="" year="2002" month="" title="Algorithms for Optimistic Replication on the Web" journal="Journal of the Brazilian Computing Society" volume="8" number="2" pages="" note="">
    <authors name="E. Pacitti "/>
    <authors name=" O. Dedieu"/>
  </Article>
  <Article id="MTSurvey" abstract="" year="2004" month="" title="A Survey of Mobile Transactions" journal="Kluwer Academic Publishers Distributed and Parallel Databases (DAPD)" volume="16" number="2" pages="193-230" note="ISSN 0926-8782">
    <authors name="P. Serrano-Alvarado "/>
    <authors name=" C. Roncancio "/>
    <authors name=" M. Adiba"/>
  </Article>
  <Article id="SIGMODR2003:ValduriezEtAl" abstract="" year="2004" month="" title="Mobile Databases: a report on open issues and research directions" journal="ACM SIGMOD Record" volume="" number="" pages="" note="? para?tre">
    <authors name="G. Bernard "/>
    <authors name=" J. Ben-Othman "/>
    <authors name=" L. Bouganim "/>
    <authors name=" G. Canals "/>
    <authors name=" B. Defude "/>
    <authors name=" J. Ferri'e "/>
    <authors name=" S.Ganearski "/>
    <authors name=" R. Guerraoui "/>
    <authors name=" P. Molli "/>
    <authors name=" P. Pucheral "/>
    <authors name=" C. Roncancio "/>
    <authors name=" P. Serrano-Alvarado "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="Objet2004:Bezivin" abstract="" year="2004" month="" title="Sur les principes de base de l'ingenierie des modeles logiciels" journal="L'Objet" volume="10" number="4" pages="145-157" note="colloque en l'honneur de J.-F. Perrot">
    <authors name="J. Bezivin"/>
  </Article>
  <Article id="IJHPCN2006:Furtado" abstract="" year="2006" month="" title="Adaptive Hybrid Partitioning for OLAP Query Processing in a Database Cluster" journal="Int. Journal of High Performance Computing and Networking" volume="" number="" pages="" note="special issue on Best Papers from SBAC2005">
    <authors name="C. Furtado "/>
    <authors name=" A. Lima "/>
    <authors name=" E. Pacitti "/>
    <authors name=" P. Valduriez "/>
    <authors name=" M. Mattoso"/>
  </Article>
  <Article id="Novatica2004a:BezivinBreton" abstract="" year="2004" month="sep" title="Applying the basic principles of model engineering to the field of process engineering" journal="Novatica -- Special Issue on Software Process Technologies" volume="5" number="171" pages="27-33" note="">
    <authors name="J. Bezivin "/>
    <authors name=" E. Breton"/>
  </Article>
  <Article id="NISJ1998:PacittiValduriez" abstract="" year="1998" month="" title="Replicated Databases: concepts, Architectures and Techniques" journal="Networking and Information Systems Journal" volume="1" number="4-5" pages="519-546" note="">
    <authors name="E. Pacitti "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="ISI2004:Valduriez" abstract="" year="2004" month="" title="Routage de Transactions dans un Cluster de Bases de Donnees Autonomes" journal="Ingenierie des Systemes d'Information" volume="9" number="1" pages="85--107" note="">
    <authors name="H. Naacke "/>
    <authors name=" F. Dang Ngoc "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="DAPD2005:Pacitti" abstract="" year="2005" month="" title="Preventive {R}eplication in a {D}atabase {C}luster." journal="Distributed and {P}arallel {D}atabases" volume="18" number="3" pages="223-251" note="ISSN 0926-8782">
    <authors name="E. Pacitti "/>
    <authors name=" C. Coulon "/>
    <authors name=" P. Valduriez "/>
    <authors name=" T. {&quot;O}zsu"/>
  </Article>
  <Article id="DPD99:ValduriezBF" abstract="" year="1999" month="" title="Load Balancing for Parallel Query Execution on NUMA Multiprocesseurs" journal="Distributed and Parallel Databases" volume="7" number="1" pages="" note="">
    <authors name="L. Bouganim "/>
    <authors name=" D. Florescu "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="SIGMODRec:Bouganim01" abstract="" year="2001" month="" title="The Ecobase project: database and web technologies for environmental information systems" journal="SIGMOD Rec." volume="30" number="3" pages="70--75" note="">
    <authors name="L. Bouganim "/>
    <authors name=" M. Claudia Cavalcanti "/>
    <authors name=" F. Fabret "/>
    <authors name=" M. L. Campos "/>
    <authors name=" F. Llirbat "/>
    <authors name=" M. Mattoso "/>
    <authors name=" R. Melo "/>
    <authors name=" A. M. Moura "/>
    <authors name=" E. Pacitti "/>
    <authors name=" F. Porto "/>
    <authors name=" M. Simoes "/>
    <authors name=" E. Simon "/>
    <authors name=" A. Tanaka "/>
    <authors name=" P. Valduriez"/>
  </Article>
  <Article id="RTSI2005" abstract="" year="2005" month="" title="Approche MDA pour le developpement d'applications internet sur des plates-formes service web. Modelisation, transformation et prototypage." journal="RTSI serie ISI" volume="10" number="3" pages="67-90" note="ISBN=1633-1311">
    <authors name="Hammoudi, S. "/>
    <authors name=" Lopes, D. "/>
    <authors name=" Bezivin, J."/>
  </Article>
</xmi:XMI>
