<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="BIBTEXML">
  <Book id="PDDS1999:ValduriezO" abstract="" editor="" publisher="Prentice Hall" year="1999" month="" title="Principles of Distributed Database Systems, 2nd edition" volume="" number="" series="" address="" edition="" note="">
    <authors name="T. &quot;Ozsu "/>
    <authors name=" P. Valduriez"/>
  </Book>
  <Book id="Book2004:Bezivin" abstract="" editor="" publisher="editions Lavoisier" year="2004" month="may" title="Ingenierie des modeles Logiciels et Systemes -- Ouvrage ARAGO 30" volume="" number="" series="" address="" edition="" note="">
    <authors name="J. Bezivin"/>
  </Book>
</xmi:XMI>
