<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="BIBTEXML">
  <InBook id="GDS2006:Akbarinia" abstract="" editor="R. Baldoni and G. Cortese and F. Davide" publisher="IOS Press" year="2006" month="" title="Global Data Management" volume="" number="" series="" address="" edition="First" note="A paraetre" chapter="Design and Implementation of Atlas P2P Architecture" type="">
    <authors name="R. Akbarinia "/>
    <authors name=" V. Martins "/>
    <authors name=" E. Pacitti "/>
    <authors name=" P. Valduriez"/>
  </InBook>
  <InBook id="BookMDA06" abstract="" editor="Jean-Marie Favre, Jacky Estublier, Mireille Blay-Fornarino" publisher="Herm{`e}s Sciences" year="2006" month="" title="Evolution, Retro-ingenierie, et IDM" volume="" number="" series="" address="" edition="" note="To be published" chapter="" type="">
    <authors name="Jean-Marie Favre "/>
    <authors name=" Jean Bezivin "/>
    <authors name=" Ian Bull"/>
  </InBook>
  <InBook id="DBDS2003:ValduriezO" abstract="" editor="A. Tucker" publisher="CRC Press" year="2004" month="" title="Handbook of Computer Science and Engineering, 2nd Edition" volume="" number="" series="" address="" edition="" note="&#x9;oappear" chapter="Distributed and Parallel Database Systems" type="">
    <authors name="T. &quot;Ozsu "/>
    <authors name=" P. Valduriez"/>
  </InBook>
  <InBook id="MDEbook05" abstract="" editor="Sebastien Gerard, Jean-Philippe Babau and Jo{&quot;e}l Champeau" publisher="Hermes Sciences Publishing" year="2005" month="" title="Model Engineering: From Principles to Platforms" volume="" number="" series="" address="" edition="" note="" chapter="1" type="">
    <authors name="Jean Bezivin "/>
    <authors name=" Frederic Jouault "/>
    <authors name=" David Touzet"/>
  </InBook>
</xmi:XMI>
