<?xml version="1.0" encoding="ISO-8859-1"?>
<MastersThesis xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="BIBTEXML" id="Master2001:ploquin" abstract="" year="2001" month="sep" title="Etude des differents modes d'interoperabilite en genie logiciel" school="University of Nantes" type="" address="" note="in french">
  <authors name="N. Ploquin"/>
</MastersThesis>
