<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="BIBTEXML">
  <Misc id="Bezivin0014" abstract="" authors="/3" title="{MDA}: From Hype to Hope, and Reality (Guest Talk)" howpublished="" month="" year="2003" note=""/>
  <Misc id="Bezivin0009" abstract="" authors="/4" title="Aspect-Oriented Modeling: Oxymoron or Pleonasme (Keynote Speech)" howpublished="" month="jul" year="2003" note=""/>
  <Misc id="Bezivin0008" abstract="" authors="/5 /6" title="MDA : Vers un important changement de paradigme en genie logiciel" howpublished="" month="jul" year="2003" note=""/>
  <Author name="J. Bezivin"/>
  <Author name="J. Bezivin"/>
  <Author name="J. Bezivin "/>
  <Author name=" X. Blanc"/>
</xmi:XMI>
