<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="BIBTEXML">
  <PhdThesis id="PHD-Martins06" abstract="" year="2006" month="D'{e}cembre" title="R'{e}conciliation s'{e}mantique des donn'{e}es dans les syst'{e}mes pair-`{a}-pair" school="Universit'{e} de Nantes" type="" address="Nantes, France" note="">
    <authors name="V. Martins"/>
  </PhdThesis>
  <PhdThesis id="PhD2003:Peltier" abstract="" year="2003" month="" title="Techniques de transformation de mod`eles bas'ees sur la m'eta-mod'elisation" school="University of Nantes" type="" address="" note="">
    <authors name="M. Peltier"/>
  </PhdThesis>
  <PhdThesis id="PHD2006:Coulon" abstract="" year="2006" month="Octobre" title="Replication preventive dans une grape de bases de donnees" school="Universite de Nantes" type="" address="" note="">
    <authors name="C. Coulon"/>
  </PhdThesis>
  <PhdThesis id="MobileTransactionsThese04" abstract="" year="2004" month="February" title="{Transactions Adaptables pour les Environnements Mobiles}" school="Universit'e Joseph Fourier" type="" address="Grenoble, France" note="193 pages">
    <authors name="P. Serrano-Alvarado"/>
  </PhdThesis>
  <PhdThesis id="PhD2003:Gaumer" abstract="" year="2003" month="" title="Resume de donnees en Extraction de Connaissances e partir des Donnees (ECD). Application aux donnees relationnelles et textuelles" school="University of Nantes" type="" address="" note="">
    <authors name="G. Gaumer"/>
  </PhdThesis>
</xmi:XMI>
