<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="BIBTEXML">
  <Proceedings id="Bezivin_2004OCLMDE" abstract="" year="2004" month="" title="OCL and Model Driven Engineering Workshop Report" editor="N. Jardim Nunes, B.Selic, A. Silva, and A. Toval" series="" address="" organization="" publisher="Springer, Berlin, LNCS" note="ISBN=3-540-25081-6"/>
  <Proceedings id="OOPSLA04:BezEtAl" abstract="" year="2004" month="" title="Legacy Transformation: Capturing Business Knowledge from Legacy Systems ( OOPSLA 2004 workshop)" editor="J. Bezivin and S. de Cesare and G. Holland and M. Lycett and C. Partridge" series="" address="" organization="" publisher="" note=""/>
  <Proceedings id="Mellor0001" abstract="" year="2003" month="jun" title="MDA Components: is there a Need and a Markete" editor="S. Mellor and L. Rioux and J. Bezivin" series="" address="OMG Document ad/03-06-01: OFTA/MDA users SIG/MDA working Group report" organization="" publisher="" note=""/>
  <Proceedings id="Bezivin:2005" abstract="" year="2005" month="" title="Language Engineering for Model-driven Software Development" editor="Jean Bezivin and Reiko Heckel" series="Dagstuhl Seminar Proceedings" address="Dagstuhl, Germany" organization="" publisher="Internationales Begegnungs- und Forschungszentrum (IBFI), Schloss Dagstuhl, Germany" note=""/>
  <Proceedings id="WMDD2004" abstract="" year="2004" month="June" title="Workshop on Model Driven Development (WMDD 2004)" editor="" series="" address="" organization="" publisher="Springer-Verlag" note="ISBN=3-540-23988-X"/>
</xmi:XMI>
