<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="BIBTEXML">
  <TechReport id="ATL2003:BezivinBVD" abstract="" institution="IRIN" year="2003" month="" title="The {ATL} Transformation-Based Model Management Framework" type="" number="" address="" note="">
    <authors name="B'ezivin "/>
    <authors name=" E. Breton "/>
    <authors name=" P. Valduriez "/>
    <authors name=" G. Dup'e"/>
  </TechReport>
  <TechReport id="MTS-Overview2001" abstract="" institution="Logiciels Syst`emes R'eseaux IMAG" year="2001" month="July" title="{Mobile Transaction Supports for DBMS: An Overview}" type="" number="RR 1039-I-LSR 16" address="Grenoble, France" note="">
    <authors name="P. Serrano-Alvarado "/>
    <authors name=" C. L. Roncancio "/>
    <authors name=" M. Adiba"/>
  </TechReport>
  <TechReport id="Bezivin0015" abstract="" institution="LINA, Universite de Nantes" year="2004" month="mar" title="An Experiment in Mapping Web Services to Implementation Platforms" type="" number="04.01" address="" note="">
    <authors name="J. Bezivin "/>
    <authors name=" S. Hammoudi "/>
    <authors name=" D. Lopes "/>
    <authors name=" F. Jouault"/>
  </TechReport>
  <TechReport id="RR0602" abstract="" institution="LINA" year="2006" month="" title="Extending AMMA for Supporting Dynamic Semantics Specifications of DSLs" type="" number="06.02" address="" note="">
    <authors name="Davide Di Ruscio "/>
    <authors name=" Frederic Jouault "/>
    <authors name=" Ivan Kurtev "/>
    <authors name=" Jean Bezivin "/>
    <authors name=" Alfonso Pierantonio"/>
  </TechReport>
  <TechReport id="LINARR3Bezivin04" abstract="" institution="LINA" year="2004" month="" title="The AMMA platform support for modeling in the large and modelling in the small" type="" number="04.09" address="" note="">
    <authors name="Jean Bezivin "/>
    <authors name=" Frederic Jouault "/>
    <authors name=" Peter Rosenthal "/>
    <authors name=" Patrick Valduriez"/>
  </TechReport>
  <TechReport id="RRLINA200501" abstract="" institution="LINA" year="2005" month="" title="An Introduction to the ATLAS Model Management Architecture" type="" number="05-01" address="" note="">
    <authors name="Jean Bezivin "/>
    <authors name=" Frederic Jouault "/>
    <authors name=" David Touzet"/>
  </TechReport>
  <TechReport id="RRLINA200408" abstract="" institution="LINA" year="2004" month="" title="An Eclipse-based IDE for the ATL model transformation language" type="" number="04.08" address="" note="">
    <authors name="Jean Bezivin "/>
    <authors name=" Frederic Jouault "/>
    <authors name=" Patrick Valduriez"/>
  </TechReport>
  <TechReport id="RR0603" abstract="" institution="LINA" year="2006" month="" title="A Practical Experiment to Give Dynamic Semantics to a DSL for Telephony Services Development" type="" number="06.03" address="" note="">
    <authors name="Davide Di Ruscio "/>
    <authors name=" Frederic Jouault "/>
    <authors name=" Ivan Kurtev "/>
    <authors name=" Jean Bezivin "/>
    <authors name=" Alfonso Pierantonio"/>
  </TechReport>
</xmi:XMI>
